;#######################################################
;
; Generated by MAPeD-NES Copyright 2017-2022 0x8BitDev
;
;#######################################################

; export options:
;	- tiles 4x4/(columns)
;	- attributes per block
;	- properties per block
;	- mode: bidirectional scrolling
;	- layout: adjacent screens (no marks)
;	- no entities


MAP_DATA_MAGIC = $2884A

; data flags:
MAP_FLAG_TILES2X2                 = $01
MAP_FLAG_TILES4X4                 = $02
MAP_FLAG_RLE                      = $04
MAP_FLAG_DIR_COLUMNS              = $08
MAP_FLAG_DIR_ROWS                 = $10
MAP_FLAG_MODE_MULTIDIR_SCROLL     = $20
MAP_FLAG_MODE_BIDIR_SCROLL        = $40
MAP_FLAG_MODE_STATIC_SCREENS      = $80
MAP_FLAG_ENTITIES                 = $100
MAP_FLAG_ENTITY_SCREEN_COORDS     = $200
MAP_FLAG_ENTITY_MAP_COORS         = $400
MAP_FLAG_LAYOUT_ADJACENT_SCREENS  = $800
MAP_FLAG_LAYOUT_ADJACENT_SCR_INDS = $1000
MAP_FLAG_LAYOUT_MATRIX            = $2000
MAP_FLAG_MARKS                    = $4000
MAP_FLAG_ATTRS_PER_BLOCK          = $8000
MAP_FLAG_ATTRS_PER_CHR            = $10000
MAP_FLAG_PROP_ID_PER_BLOCK        = $20000
MAP_FLAG_PROP_ID_PER_CHR          = $40000

SCR_BLOCKS2x2_WIDTH	= 16	; number of screen blocks (2x2) in width
SCR_BLOCKS2x2_HEIGHT	= 15	; number of screen blocks (2x2) in height

; *** GLOBAL DATA ***

; chr0:	.incbin "tilemap_chr0.bin"		; (4048)

tilemap_Blocks:	.incbin "tilemap_Blocks.bin"	; (484) blocks array of all exported data banks ( 4 bytes per block )
tilemap_Props:	.incbin "tilemap_Props.bin"	; (121) block properties array of all exported data banks ( 1 byte per block; data offset = props offset / 4 )

tilemap_BlocksPropsOffs:
	.word 0		; (chr0)

tilemap_Tiles:	.incbin "tilemap_Tiles.bin"	; (940) tiles (4x4) array of all exported data banks ( 4 bytes per tile )

tilemap_TilesOffs:
	.word 0		; (chr0)

tilemap_Attrs:	.incbin "tilemap_Attrs.bin"	; (235) attributes array of all exported data banks ( 1 byte per attribute ), data offset = tiles offset / 4
tilemap_TilesScr:	.incbin "tilemap_TilesScr.bin"	; (1472) tiles (4x4) array for each screen ( 64 bytes per screen \ 1 byte per tile )
tilemap_Plts:	.incbin "tilemap_Plts.bin"	; (16) palettes array of all exported data banks ( data offset = chr_id * 16 )

; *** Lev0 ***

Lev0_StartScr:	.word Lev0Scr48

Lev0Scr12:
	.byte 0	; chr_id

	.byte 0	; screen index

	.word 0	; left adjacent screen
	.word 0	; up adjacent screen
	.word Lev0Scr13	; right adjacent screen
	.word Lev0Scr28	; down adjacent screen

Lev0Scr13:
	.byte 0

	.byte 1

	.word Lev0Scr12
	.word 0
	.word Lev0Scr14
	.word 0

Lev0Scr14:
	.byte 0

	.byte 2

	.word Lev0Scr13
	.word 0
	.word Lev0Scr15
	.word 0

Lev0Scr15:
	.byte 0

	.byte 3

	.word Lev0Scr14
	.word 0
	.word 0
	.word 0

Lev0Scr21:
	.byte 0

	.byte 4

	.word 0
	.word 0
	.word Lev0Scr22
	.word Lev0Scr37

Lev0Scr22:
	.byte 0

	.byte 5

	.word Lev0Scr21
	.word 0
	.word Lev0Scr23
	.word 0

Lev0Scr23:
	.byte 0

	.byte 6

	.word Lev0Scr22
	.word 0
	.word Lev0Scr24
	.word 0

Lev0Scr24:
	.byte 0

	.byte 7

	.word Lev0Scr23
	.word 0
	.word Lev0Scr25
	.word 0

Lev0Scr25:
	.byte 0

	.byte 8

	.word Lev0Scr24
	.word 0
	.word Lev0Scr26
	.word 0

Lev0Scr26:
	.byte 0

	.byte 9

	.word Lev0Scr25
	.word 0
	.word 0
	.word Lev0Scr42

Lev0Scr28:
	.byte 0

	.byte 10

	.word 0
	.word Lev0Scr12
	.word 0
	.word Lev0Scr44

Lev0Scr37:
	.byte 0

	.byte 11

	.word 0
	.word Lev0Scr21
	.word 0
	.word Lev0Scr53

Lev0Scr42:
	.byte 0

	.byte 12

	.word 0
	.word Lev0Scr26
	.word 0
	.word Lev0Scr58

Lev0Scr44:
	.byte 0

	.byte 13

	.word 0
	.word Lev0Scr28
	.word 0
	.word Lev0Scr60

Lev0Scr48:
	.byte 0

	.byte 14

	.word 0
	.word 0
	.word Lev0Scr49
	.word 0

Lev0Scr49:
	.byte 0

	.byte 15

	.word Lev0Scr48
	.word 0
	.word Lev0Scr50
	.word 0

Lev0Scr50:
	.byte 0

	.byte 16

	.word Lev0Scr49
	.word 0
	.word Lev0Scr51
	.word 0

Lev0Scr51:
	.byte 0

	.byte 17

	.word Lev0Scr50
	.word 0
	.word Lev0Scr52
	.word 0

Lev0Scr52:
	.byte 0

	.byte 18

	.word Lev0Scr51
	.word 0
	.word Lev0Scr53
	.word 0

Lev0Scr53:
	.byte 0

	.byte 19

	.word Lev0Scr52
	.word Lev0Scr37
	.word 0
	.word 0

Lev0Scr58:
	.byte 0

	.byte 20

	.word 0
	.word Lev0Scr42
	.word Lev0Scr59
	.word 0

Lev0Scr59:
	.byte 0

	.byte 21

	.word Lev0Scr58
	.word 0
	.word Lev0Scr60
	.word 0

Lev0Scr60:
	.byte 0

	.byte 22

	.word Lev0Scr59
	.word Lev0Scr44
	.word 0
	.word 0


MapsArr:
	.word Lev0_StartScr

