;#######################################################
;
; Generated by MAPeD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################


; *** GLOBAL DATA ***

_chr0:	.incbin "_tilemap__chr0.bin"		; (7776)


_mpd_CHRs_size:
	.word 7776	; (_chr0)

_mpd_Props:	.incbin "_tilemap_Props.bin"	; (816) block properties array of all exported data banks ( 4 bytes per block )

_mpd_PropsOffs:
	.word 0	; (chr0)
	.word 816	; data end

_mpd_BlocksOffs:
	.word 0	; (chr0)

_mpd_Attrs:	.incbin "_tilemap_Attrs.bin"	; (1632) 2x2 tiles attributes array of all exported data banks ( 2 bytes per attribute )
_mpd_TilesScr:	.incbin "_tilemap_TilesScr.bin"	; (3584) 2x2 tiles array for each screen ( 224 bytes per screen \ 1 byte per tile )
_mpd_Plts:	.incbin "_tilemap_Plts.bin"	; (512) palettes array of all exported data banks ( data offset = chr_id * 512 )
