//#######################################################
//
// Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
//
//#######################################################

#incasm( "anm_test.asm" )

#define ANM_TEST_SPR_VADDR	8192
#define ANM_TEST_PALETTE_SLOT	16


#ifndef	DEF_TYPE_SPD_SPRITE
#define	DEF_TYPE_SPD_SPRITE
typedef struct
{
	const unsigned short*	attrs;
	unsigned char		bank;
	unsigned short		size;
	unsigned char		SG_ind;
} spd_SPRITE;
#endif	//DEF_TYPE_SPD_SPRITE


extern unsigned short*	anm_test_SG_arr;
const unsigned char	anm_test_SG_cnt	= 1;	// graphics banks count
const unsigned short	anm_test_palette_size	= 1;	// active palettes

extern unsigned short*	anm_test_palette;
const unsigned short	anm_test_frames_cnt	= 6;
extern spd_SPRITE	anm_test_frames_data[];

#define	SPR_MARTHA_PUNCH01	0
#define	SPR_MARTHA_PUNCH02	1
#define	SPR_MARTHA_PUNCH03	2
#define	SPR_MARTHA_PUNCH04	3
#define	SPR_MARTHA_PUNCH05	4
#define	SPR_MARTHA_PUNCH06_REF04	5

extern spd_SPRITE*	martha_punch01_frame;
extern spd_SPRITE*	martha_punch02_frame;
extern spd_SPRITE*	martha_punch03_frame;
extern spd_SPRITE*	martha_punch04_frame;
extern spd_SPRITE*	martha_punch05_frame;
extern spd_SPRITE*	martha_punch06_ref04_frame;

