//#######################################################
//
// Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
//
//#######################################################

#incasm( "anm_test.asm" )

#define ANM_TEST_SPR_VADDR	0x2000

#ifndef	DEF_TYPE_SPD_SPRITE
#define	DEF_TYPE_SPD_SPRITE
typedef struct
{
	const unsigned short	size;
	const unsigned char	SG_ind;
	const unsigned short	attrs[];
} spd_SPRITE;
#endif	//DEF_TYPE_SPD_SPRITE


#define	ANM_TEST_SG_CNT	1	// graphics banks count
extern unsigned short*	anm_test_SG_arr;

#define	ANM_TEST_PALETTE_SIZE	1	// active palettes
#define ANM_TEST_PALETTE_SLOT	16

extern unsigned short*	anm_test_palette_slot0;
extern unsigned short*	anm_test_palette;

#define	ANM_TEST_FRAMES_CNT	6
extern unsigned char*	anm_test_frames_data;

#define	SPR_MARTHA_PUNCH01	0
#define	SPR_MARTHA_PUNCH02	1
#define	SPR_MARTHA_PUNCH03	2
#define	SPR_MARTHA_PUNCH04	3
#define	SPR_MARTHA_PUNCH05	4
#define	SPR_MARTHA_PUNCH06_REF04	5

extern spd_SPRITE*	martha_punch01;
extern spd_SPRITE*	martha_punch02;
extern spd_SPRITE*	martha_punch03;
extern spd_SPRITE*	martha_punch04;
extern spd_SPRITE*	martha_punch05;
extern spd_SPRITE*	martha_punch06_ref04;

