;#######################################################
;
; Generated by SPReD-NES Copyright 2017-2019 0x8BitDev
;
;#######################################################

SPR_MODE_8X16 = 0


;chr0:	.incbin "marco_gfx_chr0.bin"	; 1024 of 1024 bytes
;chr1:	.incbin "marco_gfx_chr1.bin"	; 848 of 1024 bytes
;chr2:	.incbin "marco_gfx_chr2.bin"	; 896 of 1024 bytes
;chr3:	.incbin "marco_gfx_chr3.bin"	; 736 of 1024 bytes
;chr4:	.incbin "marco_gfx_chr4.bin"	; 624 of 1024 bytes
;chr5:	.incbin "marco_gfx_chr5.bin"	; 992 of 1024 bytes
;chr6:	.incbin "marco_gfx_chr6.bin"	; 1024 of 1024 bytes


sprite_palette:
	.byte $21, $1D, $17, $38, $21, $14, $24, $34, $21, $0D, $08, $18, $21, $0D, $18, $28


n_frames:
	.byte $3A
frames_data:
marco_idle01_RIGHT_frame:
	.word marco_idle01_RIGHT
	.byte marco_idle01_RIGHT_end - marco_idle01_RIGHT	; data size
	.byte 0		; CHR bank index (chr0)
marco_idle02_RIGHT_frame:
	.word marco_idle02_RIGHT
	.byte marco_idle02_RIGHT_end - marco_idle02_RIGHT
	.byte 0
marco_idle03_RIGHT_frame:
	.word marco_idle03_RIGHT
	.byte marco_idle03_RIGHT_end - marco_idle03_RIGHT
	.byte 0
marco_idle04_RIGHT_frame:
	.word marco_idle04_RIGHT
	.byte marco_idle04_RIGHT_end - marco_idle04_RIGHT
	.byte 0
marco_idle05_RIGHT_frame:
	.word marco_idle05_RIGHT
	.byte marco_idle05_RIGHT_end - marco_idle05_RIGHT
	.byte 0
marco_idle06_RIGHT_frame:
	.word marco_idle06_RIGHT
	.byte marco_idle06_RIGHT_end - marco_idle06_RIGHT
	.byte 0
marco_duck01_RIGHT_frame:
	.word marco_duck01_RIGHT
	.byte marco_duck01_RIGHT_end - marco_duck01_RIGHT
	.byte 5
marco_duck02_RIGHT_frame:
	.word marco_duck02_RIGHT
	.byte marco_duck02_RIGHT_end - marco_duck02_RIGHT
	.byte 5
marco_duck03_RIGHT_frame:
	.word marco_duck03_RIGHT
	.byte marco_duck03_RIGHT_end - marco_duck03_RIGHT
	.byte 0
marco_duck04_RIGHT_frame:
	.word marco_duck04_RIGHT
	.byte marco_duck04_RIGHT_end - marco_duck04_RIGHT
	.byte 5
marco_duck05_RIGHT_frame:
	.word marco_duck05_RIGHT
	.byte marco_duck05_RIGHT_end - marco_duck05_RIGHT
	.byte 5
marco_duck06_RIGHT_frame:
	.word marco_duck06_RIGHT
	.byte marco_duck06_RIGHT_end - marco_duck06_RIGHT
	.byte 6
marco_duck07_RIGHT_frame:
	.word marco_duck07_RIGHT
	.byte marco_duck07_RIGHT_end - marco_duck07_RIGHT
	.byte 6
marco_duck08_RIGHT_frame:
	.word marco_duck08_RIGHT
	.byte marco_duck08_RIGHT_end - marco_duck08_RIGHT
	.byte 5
marco_duck09_RIGHT_frame:
	.word marco_duck09_RIGHT
	.byte marco_duck09_RIGHT_end - marco_duck09_RIGHT
	.byte 5
marco_duck10_RIGHT_frame:
	.word marco_duck10_RIGHT
	.byte marco_duck10_RIGHT_end - marco_duck10_RIGHT
	.byte 0
marco_run01_RIGHT_frame:
	.word marco_run01_RIGHT
	.byte marco_run01_RIGHT_end - marco_run01_RIGHT
	.byte 6
marco_run02_RIGHT_frame:
	.word marco_run02_RIGHT
	.byte marco_run02_RIGHT_end - marco_run02_RIGHT
	.byte 6
marco_run03_RIGHT_frame:
	.word marco_run03_RIGHT
	.byte marco_run03_RIGHT_end - marco_run03_RIGHT
	.byte 1
marco_run04_RIGHT_frame:
	.word marco_run04_RIGHT
	.byte marco_run04_RIGHT_end - marco_run04_RIGHT
	.byte 1
marco_run05_RIGHT_frame:
	.word marco_run05_RIGHT
	.byte marco_run05_RIGHT_end - marco_run05_RIGHT
	.byte 1
marco_run06_RIGHT_frame:
	.word marco_run06_RIGHT
	.byte marco_run06_RIGHT_end - marco_run06_RIGHT
	.byte 6
marco_run07_RIGHT_frame:
	.word marco_run07_RIGHT
	.byte marco_run07_RIGHT_end - marco_run07_RIGHT
	.byte 2
marco_run08_RIGHT_frame:
	.word marco_run08_RIGHT
	.byte marco_run08_RIGHT_end - marco_run08_RIGHT
	.byte 2
marco_run09_RIGHT_frame:
	.word marco_run09_RIGHT
	.byte marco_run09_RIGHT_end - marco_run09_RIGHT
	.byte 2
marco_shoot01_RIGHT_frame:
	.word marco_shoot01_RIGHT
	.byte marco_shoot01_RIGHT_end - marco_shoot01_RIGHT
	.byte 3
marco_shoot02_RIGHT_frame:
	.word marco_shoot02_RIGHT
	.byte marco_shoot02_RIGHT_end - marco_shoot02_RIGHT
	.byte 3
marco_shoot03_RIGHT_frame:
	.word marco_shoot03_RIGHT
	.byte marco_shoot03_RIGHT_end - marco_shoot03_RIGHT
	.byte 4
marco_shoot04_RIGHT_frame:
	.word marco_shoot04_RIGHT
	.byte marco_shoot04_RIGHT_end - marco_shoot04_RIGHT
	.byte 4
marco_idle01_LEFT_frame:
	.word marco_idle01_LEFT
	.byte marco_idle01_LEFT_end - marco_idle01_LEFT
	.byte 0
marco_idle02_LEFT_frame:
	.word marco_idle02_LEFT
	.byte marco_idle02_LEFT_end - marco_idle02_LEFT
	.byte 0
marco_idle03_LEFT_frame:
	.word marco_idle03_LEFT
	.byte marco_idle03_LEFT_end - marco_idle03_LEFT
	.byte 0
marco_idle04_LEFT_frame:
	.word marco_idle04_LEFT
	.byte marco_idle04_LEFT_end - marco_idle04_LEFT
	.byte 0
marco_idle05_LEFT_frame:
	.word marco_idle05_LEFT
	.byte marco_idle05_LEFT_end - marco_idle05_LEFT
	.byte 0
marco_idle06_LEFT_frame:
	.word marco_idle06_LEFT
	.byte marco_idle06_LEFT_end - marco_idle06_LEFT
	.byte 0
marco_duck01_LEFT_frame:
	.word marco_duck01_LEFT
	.byte marco_duck01_LEFT_end - marco_duck01_LEFT
	.byte 5
marco_duck02_LEFT_frame:
	.word marco_duck02_LEFT
	.byte marco_duck02_LEFT_end - marco_duck02_LEFT
	.byte 5
marco_duck03_LEFT_frame:
	.word marco_duck03_LEFT
	.byte marco_duck03_LEFT_end - marco_duck03_LEFT
	.byte 0
marco_duck04_LEFT_frame:
	.word marco_duck04_LEFT
	.byte marco_duck04_LEFT_end - marco_duck04_LEFT
	.byte 5
marco_duck05_LEFT_frame:
	.word marco_duck05_LEFT
	.byte marco_duck05_LEFT_end - marco_duck05_LEFT
	.byte 5
marco_duck06_LEFT_frame:
	.word marco_duck06_LEFT
	.byte marco_duck06_LEFT_end - marco_duck06_LEFT
	.byte 6
marco_duck07_LEFT_frame:
	.word marco_duck07_LEFT
	.byte marco_duck07_LEFT_end - marco_duck07_LEFT
	.byte 6
marco_duck08_LEFT_frame:
	.word marco_duck08_LEFT
	.byte marco_duck08_LEFT_end - marco_duck08_LEFT
	.byte 5
marco_duck09_LEFT_frame:
	.word marco_duck09_LEFT
	.byte marco_duck09_LEFT_end - marco_duck09_LEFT
	.byte 5
marco_duck10_LEFT_frame:
	.word marco_duck10_LEFT
	.byte marco_duck10_LEFT_end - marco_duck10_LEFT
	.byte 0
marco_run01_LEFT_frame:
	.word marco_run01_LEFT
	.byte marco_run01_LEFT_end - marco_run01_LEFT
	.byte 6
marco_run02_LEFT_frame:
	.word marco_run02_LEFT
	.byte marco_run02_LEFT_end - marco_run02_LEFT
	.byte 6
marco_run03_LEFT_frame:
	.word marco_run03_LEFT
	.byte marco_run03_LEFT_end - marco_run03_LEFT
	.byte 1
marco_run04_LEFT_frame:
	.word marco_run04_LEFT
	.byte marco_run04_LEFT_end - marco_run04_LEFT
	.byte 1
marco_run05_LEFT_frame:
	.word marco_run05_LEFT
	.byte marco_run05_LEFT_end - marco_run05_LEFT
	.byte 1
marco_run06_LEFT_frame:
	.word marco_run06_LEFT
	.byte marco_run06_LEFT_end - marco_run06_LEFT
	.byte 6
marco_run07_LEFT_frame:
	.word marco_run07_LEFT
	.byte marco_run07_LEFT_end - marco_run07_LEFT
	.byte 2
marco_run08_LEFT_frame:
	.word marco_run08_LEFT
	.byte marco_run08_LEFT_end - marco_run08_LEFT
	.byte 2
marco_run09_LEFT_frame:
	.word marco_run09_LEFT
	.byte marco_run09_LEFT_end - marco_run09_LEFT
	.byte 2
marco_shoot01_LEFT_frame:
	.word marco_shoot01_LEFT
	.byte marco_shoot01_LEFT_end - marco_shoot01_LEFT
	.byte 3
marco_shoot02_LEFT_frame:
	.word marco_shoot02_LEFT
	.byte marco_shoot02_LEFT_end - marco_shoot02_LEFT
	.byte 3
marco_shoot03_LEFT_frame:
	.word marco_shoot03_LEFT
	.byte marco_shoot03_LEFT_end - marco_shoot03_LEFT
	.byte 4
marco_shoot04_LEFT_frame:
	.word marco_shoot04_LEFT
	.byte marco_shoot04_LEFT_end - marco_shoot04_LEFT
	.byte 4


marco_idle01_RIGHT:
	.byte $DA, $00, $00, $F5
	.byte $DA, $01, $00, $FD
	.byte $DA, $02, $00, $05
	.byte $E2, $03, $02, $F5
	.byte $E2, $04, $00, $FD
	.byte $E2, $05, $00, $05
	.byte $EA, $06, $02, $F5
	.byte $EA, $07, $00, $FD
	.byte $EA, $08, $00, $05
	.byte $EA, $09, $00, $0D
	.byte $F2, $0A, $02, $F5
	.byte $F2, $0B, $02, $FD
	.byte $F2, $0C, $02, $05
	.byte $F2, $0D, $00, $0D
	.byte $FA, $0E, $02, $F5
	.byte $FA, $0F, $02, $FD
	.byte $FA, $10, $02, $05
marco_idle01_RIGHT_end:

marco_idle02_RIGHT:
	.byte $DA, $11, $00, $F5
	.byte $DA, $12, $00, $FD
	.byte $DA, $13, $00, $05
	.byte $E2, $14, $02, $F5
	.byte $E2, $15, $00, $FD
	.byte $E2, $16, $00, $05
	.byte $EA, $17, $02, $F5
	.byte $EA, $18, $00, $FD
	.byte $EA, $19, $00, $05
	.byte $EA, $1A, $00, $0D
	.byte $F2, $1B, $02, $F5
	.byte $F2, $1C, $02, $FD
	.byte $F2, $1D, $02, $05
	.byte $F2, $1E, $00, $0D
	.byte $FA, $1F, $02, $F5
	.byte $FA, $20, $02, $FD
	.byte $FA, $21, $02, $05
marco_idle02_RIGHT_end:

marco_idle03_RIGHT:
	.byte $DA, $22, $00, $F5
	.byte $DA, $23, $00, $FD
	.byte $DA, $24, $00, $05
	.byte $E2, $25, $02, $F5
	.byte $E2, $26, $00, $FD
	.byte $E2, $27, $00, $05
	.byte $EA, $28, $02, $F5
	.byte $EA, $29, $00, $FD
	.byte $EA, $2A, $00, $05
	.byte $EA, $2B, $00, $0D
	.byte $F2, $2C, $02, $F5
	.byte $F2, $2D, $02, $FD
	.byte $F2, $2E, $02, $05
	.byte $F2, $2F, $00, $0D
	.byte $FA, $30, $02, $F5
	.byte $FA, $31, $02, $FD
	.byte $FA, $32, $02, $05
marco_idle03_RIGHT_end:

marco_idle04_RIGHT:
	.byte $DA, $22, $00, $F5
	.byte $DA, $23, $00, $FD
	.byte $DA, $24, $00, $05
	.byte $E2, $25, $02, $F5
	.byte $E2, $26, $00, $FD
	.byte $E2, $27, $00, $05
	.byte $EA, $28, $02, $F5
	.byte $EA, $29, $00, $FD
	.byte $EA, $2A, $00, $05
	.byte $EA, $2B, $00, $0D
	.byte $F2, $2C, $02, $F5
	.byte $F2, $2D, $02, $FD
	.byte $F2, $2E, $02, $05
	.byte $F2, $2F, $00, $0D
	.byte $FA, $30, $02, $F5
	.byte $FA, $31, $02, $FD
	.byte $FA, $32, $02, $05
marco_idle04_RIGHT_end:

marco_idle05_RIGHT:
	.byte $DA, $11, $00, $F5
	.byte $DA, $12, $00, $FD
	.byte $DA, $13, $00, $05
	.byte $E2, $14, $02, $F5
	.byte $E2, $15, $00, $FD
	.byte $E2, $16, $00, $05
	.byte $EA, $17, $02, $F5
	.byte $EA, $18, $00, $FD
	.byte $EA, $19, $00, $05
	.byte $EA, $1A, $00, $0D
	.byte $F2, $1B, $02, $F5
	.byte $F2, $1C, $02, $FD
	.byte $F2, $1D, $02, $05
	.byte $F2, $1E, $00, $0D
	.byte $FA, $1F, $02, $F5
	.byte $FA, $20, $02, $FD
	.byte $FA, $21, $02, $05
marco_idle05_RIGHT_end:

marco_idle06_RIGHT:
	.byte $DA, $00, $00, $F5
	.byte $DA, $01, $00, $FD
	.byte $DA, $02, $00, $05
	.byte $E2, $03, $02, $F5
	.byte $E2, $04, $00, $FD
	.byte $E2, $05, $00, $05
	.byte $EA, $06, $02, $F5
	.byte $EA, $07, $00, $FD
	.byte $EA, $08, $00, $05
	.byte $EA, $09, $00, $0D
	.byte $F2, $0A, $02, $F5
	.byte $F2, $0B, $02, $FD
	.byte $F2, $0C, $02, $05
	.byte $F2, $0D, $00, $0D
	.byte $FA, $0E, $02, $F5
	.byte $FA, $0F, $02, $FD
	.byte $FA, $10, $02, $05
marco_idle06_RIGHT_end:

marco_duck01_RIGHT:
	.byte $D7, $00, $00, $F4
	.byte $D7, $01, $00, $FC
	.byte $D7, $02, $00, $04
	.byte $DF, $03, $02, $F4
	.byte $DF, $04, $00, $FC
	.byte $DF, $05, $00, $04
	.byte $E7, $06, $02, $F4
	.byte $E7, $07, $00, $FC
	.byte $E7, $08, $00, $04
	.byte $EF, $09, $02, $F4
	.byte $EF, $0A, $02, $FC
	.byte $EF, $0B, $00, $04
	.byte $EF, $0C, $00, $0C
	.byte $F7, $0D, $02, $F4
	.byte $F7, $0E, $02, $FC
	.byte $F7, $0F, $02, $04
	.byte $FF, $10, $02, $F4
	.byte $FF, $11, $02, $FC
	.byte $FF, $12, $02, $04
marco_duck01_RIGHT_end:

marco_duck02_RIGHT:
	.byte $DA, $13, $02, $F5
	.byte $DA, $14, $00, $FD
	.byte $DA, $15, $00, $05
	.byte $E2, $16, $02, $F5
	.byte $E2, $17, $00, $FD
	.byte $E2, $18, $00, $05
	.byte $EA, $19, $02, $F5
	.byte $EA, $1A, $00, $FD
	.byte $EA, $1B, $00, $05
	.byte $EA, $1C, $00, $0D
	.byte $F2, $1D, $02, $F5
	.byte $F2, $1E, $02, $FD
	.byte $F2, $1F, $02, $05
	.byte $F2, $20, $00, $0D
	.byte $FA, $21, $02, $F5
	.byte $FA, $22, $02, $FD
	.byte $FA, $23, $02, $05
marco_duck02_RIGHT_end:

marco_duck03_RIGHT:
	.byte $E8, $33, $02, $F0
	.byte $E8, $34, $02, $F8
	.byte $E8, $35, $00, $00
	.byte $E8, $36, $00, $08
	.byte $F0, $37, $02, $F0
	.byte $F0, $38, $02, $F8
	.byte $F0, $39, $00, $00
	.byte $F0, $3A, $00, $08
	.byte $F8, $3B, $02, $F0
	.byte $F8, $3C, $02, $F8
	.byte $F8, $3D, $00, $00
	.byte $F8, $3E, $00, $08
	.byte $F8, $3F, $00, $10
marco_duck03_RIGHT_end:

marco_duck04_RIGHT:
	.byte $E8, $24, $02, $F0
	.byte $E8, $25, $02, $F8
	.byte $E8, $26, $00, $00
	.byte $E8, $27, $00, $08
	.byte $F0, $28, $02, $F0
	.byte $F0, $29, $02, $F8
	.byte $F0, $2A, $00, $00
	.byte $F0, $2B, $00, $08
	.byte $F8, $2C, $02, $F0
	.byte $F8, $2D, $02, $F8
	.byte $F8, $2E, $00, $00
	.byte $F8, $2F, $00, $08
	.byte $F8, $30, $00, $10
marco_duck04_RIGHT_end:

marco_duck05_RIGHT:
	.byte $E8, $31, $02, $F0
	.byte $E8, $32, $02, $F8
	.byte $E8, $33, $00, $00
	.byte $E8, $34, $00, $08
	.byte $F0, $35, $02, $F0
	.byte $F0, $36, $02, $F8
	.byte $F0, $37, $00, $00
	.byte $F0, $38, $00, $08
	.byte $F8, $39, $02, $F0
	.byte $F8, $3A, $02, $F8
	.byte $F8, $3B, $00, $00
	.byte $F8, $3C, $00, $08
	.byte $F8, $3D, $00, $10
marco_duck05_RIGHT_end:

marco_duck06_RIGHT:
	.byte $E8, $00, $02, $F0
	.byte $E8, $01, $02, $F8
	.byte $E8, $02, $00, $00
	.byte $E8, $03, $00, $08
	.byte $F0, $04, $02, $F0
	.byte $F0, $05, $02, $F8
	.byte $F0, $06, $00, $00
	.byte $F0, $07, $00, $08
	.byte $F8, $08, $02, $F0
	.byte $F8, $09, $02, $F8
	.byte $F8, $0A, $00, $00
	.byte $F8, $0B, $00, $08
	.byte $F8, $0C, $00, $10
marco_duck06_RIGHT_end:

marco_duck07_RIGHT:
	.byte $E8, $00, $02, $F0
	.byte $E8, $01, $02, $F8
	.byte $E8, $02, $00, $00
	.byte $E8, $03, $00, $08
	.byte $F0, $04, $02, $F0
	.byte $F0, $05, $02, $F8
	.byte $F0, $06, $00, $00
	.byte $F0, $07, $00, $08
	.byte $F8, $08, $02, $F0
	.byte $F8, $09, $02, $F8
	.byte $F8, $0A, $00, $00
	.byte $F8, $0B, $00, $08
	.byte $F8, $0C, $00, $10
marco_duck07_RIGHT_end:

marco_duck08_RIGHT:
	.byte $E8, $31, $02, $F0
	.byte $E8, $32, $02, $F8
	.byte $E8, $33, $00, $00
	.byte $E8, $34, $00, $08
	.byte $F0, $35, $02, $F0
	.byte $F0, $36, $02, $F8
	.byte $F0, $37, $00, $00
	.byte $F0, $38, $00, $08
	.byte $F8, $39, $02, $F0
	.byte $F8, $3A, $02, $F8
	.byte $F8, $3B, $00, $00
	.byte $F8, $3C, $00, $08
	.byte $F8, $3D, $00, $10
marco_duck08_RIGHT_end:

marco_duck09_RIGHT:
	.byte $E8, $24, $02, $F0
	.byte $E8, $25, $02, $F8
	.byte $E8, $26, $00, $00
	.byte $E8, $27, $00, $08
	.byte $F0, $28, $02, $F0
	.byte $F0, $29, $02, $F8
	.byte $F0, $2A, $00, $00
	.byte $F0, $2B, $00, $08
	.byte $F8, $2C, $02, $F0
	.byte $F8, $2D, $02, $F8
	.byte $F8, $2E, $00, $00
	.byte $F8, $2F, $00, $08
	.byte $F8, $30, $00, $10
marco_duck09_RIGHT_end:

marco_duck10_RIGHT:
	.byte $E8, $33, $02, $F0
	.byte $E8, $34, $02, $F8
	.byte $E8, $35, $00, $00
	.byte $E8, $36, $00, $08
	.byte $F0, $37, $02, $F0
	.byte $F0, $38, $02, $F8
	.byte $F0, $39, $00, $00
	.byte $F0, $3A, $00, $08
	.byte $F8, $3B, $02, $F0
	.byte $F8, $3C, $02, $F8
	.byte $F8, $3D, $00, $00
	.byte $F8, $3E, $00, $08
	.byte $F8, $3F, $00, $10
marco_duck10_RIGHT_end:

marco_run01_RIGHT:
	.byte $D8, $0D, $00, $FD
	.byte $D8, $0E, $00, $05
	.byte $E0, $0F, $02, $F5
	.byte $E0, $10, $00, $FD
	.byte $E0, $11, $00, $05
	.byte $E8, $12, $02, $F5
	.byte $E8, $13, $00, $FD
	.byte $E8, $14, $00, $05
	.byte $E8, $15, $00, $0D
	.byte $F0, $16, $02, $F5
	.byte $F0, $17, $02, $FD
	.byte $F0, $18, $02, $05
	.byte $F0, $19, $00, $0D
	.byte $F8, $1A, $02, $F5
	.byte $F8, $1B, $02, $FD
	.byte $F8, $1C, $02, $05
marco_run01_RIGHT_end:

marco_run02_RIGHT:
	.byte $D7, $1D, $00, $FD
	.byte $D7, $1E, $00, $05
	.byte $DF, $1F, $02, $F5
	.byte $DF, $20, $00, $FD
	.byte $DF, $21, $00, $05
	.byte $E7, $22, $02, $F5
	.byte $E7, $23, $00, $FD
	.byte $E7, $24, $00, $05
	.byte $E7, $25, $00, $0D
	.byte $EF, $26, $02, $F5
	.byte $EF, $27, $02, $FD
	.byte $EF, $28, $02, $05
	.byte $EF, $29, $00, $0D
	.byte $F7, $2A, $02, $F5
	.byte $F7, $2B, $02, $FD
	.byte $F7, $2C, $02, $05
	.byte $FF, $2D, $00, $F5
	.byte $FF, $2E, $00, $FD
	.byte $FF, $2F, $00, $05
marco_run02_RIGHT_end:

marco_run03_RIGHT:
	.byte $D6, $00, $00, $F5
	.byte $D6, $01, $00, $FD
	.byte $D6, $02, $00, $05
	.byte $DE, $03, $02, $F5
	.byte $DE, $04, $00, $FD
	.byte $DE, $05, $00, $05
	.byte $E6, $06, $02, $F5
	.byte $E6, $07, $00, $FD
	.byte $E6, $08, $00, $05
	.byte $E6, $09, $00, $0D
	.byte $EE, $0A, $02, $F5
	.byte $EE, $0B, $02, $FD
	.byte $EE, $0C, $02, $05
	.byte $EE, $0D, $00, $0D
	.byte $F6, $0E, $02, $F5
	.byte $F6, $0F, $02, $FD
	.byte $F6, $10, $02, $05
marco_run03_RIGHT_end:

marco_run04_RIGHT:
	.byte $D5, $11, $00, $FA
	.byte $D5, $12, $00, $02
	.byte $D5, $13, $00, $0A
	.byte $DD, $14, $02, $F2
	.byte $DD, $15, $00, $FA
	.byte $DD, $16, $00, $02
	.byte $E5, $17, $02, $F2
	.byte $E5, $18, $00, $FA
	.byte $E5, $19, $00, $02
	.byte $E5, $1A, $00, $0A
	.byte $ED, $1B, $02, $F2
	.byte $ED, $1C, $02, $FA
	.byte $ED, $1D, $02, $02
	.byte $ED, $1E, $00, $0A
	.byte $F5, $1F, $02, $F2
	.byte $F5, $20, $02, $FA
	.byte $F5, $21, $02, $02
	.byte $F5, $22, $02, $0A
	.byte $FD, $23, $02, $F2
marco_run04_RIGHT_end:

marco_run05_RIGHT:
	.byte $D8, $24, $00, $F4
	.byte $D8, $25, $00, $FC
	.byte $D8, $26, $00, $04
	.byte $E0, $27, $02, $F4
	.byte $E0, $28, $00, $FC
	.byte $E0, $29, $00, $04
	.byte $E8, $2A, $02, $F4
	.byte $E8, $2B, $00, $FC
	.byte $E8, $2C, $00, $04
	.byte $E8, $2D, $00, $0C
	.byte $F0, $2E, $02, $F4
	.byte $F0, $2F, $02, $FC
	.byte $F0, $30, $00, $04
	.byte $F0, $31, $00, $0C
	.byte $F8, $32, $02, $F4
	.byte $F8, $33, $02, $FC
	.byte $F8, $34, $02, $04
marco_run05_RIGHT_end:

marco_run06_RIGHT:
	.byte $D8, $30, $00, $F4
	.byte $D8, $31, $00, $FC
	.byte $D8, $32, $00, $04
	.byte $E0, $33, $02, $F4
	.byte $E0, $34, $00, $FC
	.byte $E0, $35, $00, $04
	.byte $E8, $36, $02, $F4
	.byte $E8, $37, $00, $FC
	.byte $E8, $38, $00, $04
	.byte $E8, $39, $00, $0C
	.byte $F0, $3A, $02, $F4
	.byte $F0, $3B, $02, $FC
	.byte $F0, $3C, $00, $04
	.byte $F0, $3D, $00, $0C
	.byte $F8, $3E, $02, $F4
	.byte $F8, $3F, $02, $FC
marco_run06_RIGHT_end:

marco_run07_RIGHT:
	.byte $D7, $00, $02, $F5
	.byte $D7, $01, $00, $FD
	.byte $D7, $02, $00, $05
	.byte $DF, $03, $02, $F5
	.byte $DF, $04, $00, $FD
	.byte $DF, $05, $00, $05
	.byte $E7, $06, $02, $F5
	.byte $E7, $07, $00, $FD
	.byte $E7, $08, $00, $05
	.byte $E7, $09, $00, $0D
	.byte $EF, $0A, $02, $F5
	.byte $EF, $0B, $02, $FD
	.byte $EF, $0C, $00, $05
	.byte $EF, $0D, $00, $0D
	.byte $F7, $0E, $02, $F5
	.byte $F7, $0F, $02, $FD
	.byte $F7, $10, $02, $05
marco_run07_RIGHT_end:

marco_run08_RIGHT:
	.byte $D6, $11, $00, $F1
	.byte $D6, $12, $00, $F9
	.byte $D6, $13, $00, $01
	.byte $D6, $14, $00, $09
	.byte $DE, $15, $02, $F1
	.byte $DE, $16, $02, $F9
	.byte $DE, $17, $00, $01
	.byte $DE, $18, $00, $09
	.byte $E6, $19, $02, $F1
	.byte $E6, $1A, $02, $F9
	.byte $E6, $1B, $00, $01
	.byte $E6, $1C, $00, $09
	.byte $E6, $1D, $00, $11
	.byte $EE, $1E, $02, $F1
	.byte $EE, $1F, $02, $F9
	.byte $EE, $20, $02, $01
	.byte $EE, $21, $00, $09
	.byte $EE, $22, $00, $11
	.byte $F6, $23, $02, $F1
	.byte $F6, $24, $02, $F9
	.byte $F6, $25, $02, $01
	.byte $F6, $26, $02, $09
marco_run08_RIGHT_end:

marco_run09_RIGHT:
	.byte $D8, $27, $00, $F5
	.byte $D8, $28, $00, $FD
	.byte $D8, $29, $00, $05
	.byte $E0, $2A, $02, $F5
	.byte $E0, $2B, $00, $FD
	.byte $E0, $2C, $00, $05
	.byte $E8, $2D, $02, $F5
	.byte $E8, $2E, $00, $FD
	.byte $E8, $2F, $00, $05
	.byte $E8, $30, $00, $0D
	.byte $F0, $31, $02, $F5
	.byte $F0, $32, $02, $FD
	.byte $F0, $33, $02, $05
	.byte $F0, $34, $00, $0D
	.byte $F8, $35, $02, $F5
	.byte $F8, $36, $02, $FD
	.byte $F8, $37, $02, $05
marco_run09_RIGHT_end:

marco_shoot01_RIGHT:
	.byte $DB, $00, $02, $F5
	.byte $DB, $01, $00, $FD
	.byte $DB, $02, $00, $05
	.byte $DB, $03, $00, $15
	.byte $DB, $04, $00, $1D
	.byte $E3, $05, $02, $F5
	.byte $E3, $06, $00, $FD
	.byte $E3, $07, $00, $05
	.byte $E3, $08, $00, $0D
	.byte $E3, $09, $00, $15
	.byte $E3, $0A, $00, $1D
	.byte $E3, $0B, $00, $25
	.byte $EB, $0C, $02, $F5
	.byte $EB, $0D, $02, $FD
	.byte $EB, $0E, $00, $05
	.byte $EB, $0F, $00, $0D
	.byte $F3, $10, $02, $F5
	.byte $F3, $11, $02, $FD
	.byte $F3, $12, $02, $05
	.byte $FB, $13, $02, $F5
	.byte $FB, $14, $02, $FD
	.byte $FB, $15, $02, $05
marco_shoot01_RIGHT_end:

marco_shoot02_RIGHT:
	.byte $DB, $16, $02, $F5
	.byte $DB, $17, $00, $FD
	.byte $DB, $18, $00, $05
	.byte $DB, $19, $00, $0D
	.byte $DB, $1A, $00, $15
	.byte $DB, $1B, $00, $1D
	.byte $DB, $1C, $00, $25
	.byte $E3, $1D, $02, $F5
	.byte $E3, $1E, $00, $FD
	.byte $E3, $1F, $00, $05
	.byte $E3, $20, $00, $0D
	.byte $E3, $21, $00, $15
	.byte $E3, $22, $00, $1D
	.byte $E3, $23, $00, $25
	.byte $EB, $24, $02, $F5
	.byte $EB, $25, $03, $FD
	.byte $EB, $26, $00, $05
	.byte $EB, $27, $00, $0D
	.byte $F3, $28, $02, $F5
	.byte $F3, $29, $03, $FD
	.byte $F3, $2A, $03, $05
	.byte $FB, $2B, $02, $F5
	.byte $FB, $2C, $03, $FD
	.byte $FB, $2D, $03, $05
marco_shoot02_RIGHT_end:

marco_shoot03_RIGHT:
	.byte $DB, $00, $02, $F4
	.byte $DB, $01, $00, $FC
	.byte $DB, $02, $00, $04
	.byte $DB, $03, $00, $0C
	.byte $DB, $04, $00, $14
	.byte $E3, $05, $02, $F4
	.byte $E3, $06, $00, $FC
	.byte $E3, $07, $00, $04
	.byte $E3, $08, $00, $0C
	.byte $E3, $09, $00, $14
	.byte $EB, $0A, $02, $F4
	.byte $EB, $0B, $03, $FC
	.byte $EB, $0C, $00, $04
	.byte $EB, $0D, $00, $0C
	.byte $F3, $0E, $02, $F4
	.byte $F3, $0F, $02, $FC
	.byte $F3, $10, $03, $04
	.byte $FB, $11, $02, $F4
	.byte $FB, $12, $02, $FC
	.byte $FB, $13, $03, $04
marco_shoot03_RIGHT_end:

marco_shoot04_RIGHT:
	.byte $D9, $14, $00, $FC
	.byte $D9, $15, $00, $04
	.byte $D9, $16, $00, $0C
	.byte $D9, $17, $00, $14
	.byte $E1, $18, $02, $F4
	.byte $E1, $19, $00, $FC
	.byte $E1, $1A, $00, $04
	.byte $E1, $1B, $00, $0C
	.byte $E1, $1C, $00, $14
	.byte $E9, $1D, $02, $F4
	.byte $E9, $1E, $00, $FC
	.byte $E9, $1F, $00, $04
	.byte $E9, $20, $00, $0C
	.byte $F1, $21, $02, $F4
	.byte $F1, $22, $02, $FC
	.byte $F1, $23, $02, $04
	.byte $F9, $24, $02, $F4
	.byte $F9, $25, $02, $FC
	.byte $F9, $26, $02, $04
marco_shoot04_RIGHT_end:

marco_idle01_LEFT:
	.byte $DA, $00, $40, $03
	.byte $DA, $01, $40, $FB
	.byte $DA, $02, $40, $F3
	.byte $E2, $03, $42, $03
	.byte $E2, $04, $40, $FB
	.byte $E2, $05, $40, $F3
	.byte $EA, $06, $42, $03
	.byte $EA, $07, $40, $FB
	.byte $EA, $08, $40, $F3
	.byte $EA, $09, $40, $EB
	.byte $F2, $0A, $42, $03
	.byte $F2, $0B, $42, $FB
	.byte $F2, $0C, $42, $F3
	.byte $F2, $0D, $40, $EB
	.byte $FA, $0E, $42, $03
	.byte $FA, $0F, $42, $FB
	.byte $FA, $10, $42, $F3
marco_idle01_LEFT_end:

marco_idle02_LEFT:
	.byte $DA, $11, $40, $03
	.byte $DA, $12, $40, $FB
	.byte $DA, $13, $40, $F3
	.byte $E2, $14, $42, $03
	.byte $E2, $15, $40, $FB
	.byte $E2, $16, $40, $F3
	.byte $EA, $17, $42, $03
	.byte $EA, $18, $40, $FB
	.byte $EA, $19, $40, $F3
	.byte $EA, $1A, $40, $EB
	.byte $F2, $1B, $42, $03
	.byte $F2, $1C, $42, $FB
	.byte $F2, $1D, $42, $F3
	.byte $F2, $1E, $40, $EB
	.byte $FA, $1F, $42, $03
	.byte $FA, $20, $42, $FB
	.byte $FA, $21, $42, $F3
marco_idle02_LEFT_end:

marco_idle03_LEFT:
	.byte $DA, $22, $40, $03
	.byte $DA, $23, $40, $FB
	.byte $DA, $24, $40, $F3
	.byte $E2, $25, $42, $03
	.byte $E2, $26, $40, $FB
	.byte $E2, $27, $40, $F3
	.byte $EA, $28, $42, $03
	.byte $EA, $29, $40, $FB
	.byte $EA, $2A, $40, $F3
	.byte $EA, $2B, $40, $EB
	.byte $F2, $2C, $42, $03
	.byte $F2, $2D, $42, $FB
	.byte $F2, $2E, $42, $F3
	.byte $F2, $2F, $40, $EB
	.byte $FA, $30, $42, $03
	.byte $FA, $31, $42, $FB
	.byte $FA, $32, $42, $F3
marco_idle03_LEFT_end:

marco_idle04_LEFT:
	.byte $DA, $22, $40, $03
	.byte $DA, $23, $40, $FB
	.byte $DA, $24, $40, $F3
	.byte $E2, $25, $42, $03
	.byte $E2, $26, $40, $FB
	.byte $E2, $27, $40, $F3
	.byte $EA, $28, $42, $03
	.byte $EA, $29, $40, $FB
	.byte $EA, $2A, $40, $F3
	.byte $EA, $2B, $40, $EB
	.byte $F2, $2C, $42, $03
	.byte $F2, $2D, $42, $FB
	.byte $F2, $2E, $42, $F3
	.byte $F2, $2F, $40, $EB
	.byte $FA, $30, $42, $03
	.byte $FA, $31, $42, $FB
	.byte $FA, $32, $42, $F3
marco_idle04_LEFT_end:

marco_idle05_LEFT:
	.byte $DA, $11, $40, $03
	.byte $DA, $12, $40, $FB
	.byte $DA, $13, $40, $F3
	.byte $E2, $14, $42, $03
	.byte $E2, $15, $40, $FB
	.byte $E2, $16, $40, $F3
	.byte $EA, $17, $42, $03
	.byte $EA, $18, $40, $FB
	.byte $EA, $19, $40, $F3
	.byte $EA, $1A, $40, $EB
	.byte $F2, $1B, $42, $03
	.byte $F2, $1C, $42, $FB
	.byte $F2, $1D, $42, $F3
	.byte $F2, $1E, $40, $EB
	.byte $FA, $1F, $42, $03
	.byte $FA, $20, $42, $FB
	.byte $FA, $21, $42, $F3
marco_idle05_LEFT_end:

marco_idle06_LEFT:
	.byte $DA, $00, $40, $03
	.byte $DA, $01, $40, $FB
	.byte $DA, $02, $40, $F3
	.byte $E2, $03, $42, $03
	.byte $E2, $04, $40, $FB
	.byte $E2, $05, $40, $F3
	.byte $EA, $06, $42, $03
	.byte $EA, $07, $40, $FB
	.byte $EA, $08, $40, $F3
	.byte $EA, $09, $40, $EB
	.byte $F2, $0A, $42, $03
	.byte $F2, $0B, $42, $FB
	.byte $F2, $0C, $42, $F3
	.byte $F2, $0D, $40, $EB
	.byte $FA, $0E, $42, $03
	.byte $FA, $0F, $42, $FB
	.byte $FA, $10, $42, $F3
marco_idle06_LEFT_end:

marco_duck01_LEFT:
	.byte $D7, $00, $40, $04
	.byte $D7, $01, $40, $FC
	.byte $D7, $02, $40, $F4
	.byte $DF, $03, $42, $04
	.byte $DF, $04, $40, $FC
	.byte $DF, $05, $40, $F4
	.byte $E7, $06, $42, $04
	.byte $E7, $07, $40, $FC
	.byte $E7, $08, $40, $F4
	.byte $EF, $09, $42, $04
	.byte $EF, $0A, $42, $FC
	.byte $EF, $0B, $40, $F4
	.byte $EF, $0C, $40, $EC
	.byte $F7, $0D, $42, $04
	.byte $F7, $0E, $42, $FC
	.byte $F7, $0F, $42, $F4
	.byte $FF, $10, $42, $04
	.byte $FF, $11, $42, $FC
	.byte $FF, $12, $42, $F4
marco_duck01_LEFT_end:

marco_duck02_LEFT:
	.byte $DA, $13, $42, $03
	.byte $DA, $14, $40, $FB
	.byte $DA, $15, $40, $F3
	.byte $E2, $16, $42, $03
	.byte $E2, $17, $40, $FB
	.byte $E2, $18, $40, $F3
	.byte $EA, $19, $42, $03
	.byte $EA, $1A, $40, $FB
	.byte $EA, $1B, $40, $F3
	.byte $EA, $1C, $40, $EB
	.byte $F2, $1D, $42, $03
	.byte $F2, $1E, $42, $FB
	.byte $F2, $1F, $42, $F3
	.byte $F2, $20, $40, $EB
	.byte $FA, $21, $42, $03
	.byte $FA, $22, $42, $FB
	.byte $FA, $23, $42, $F3
marco_duck02_LEFT_end:

marco_duck03_LEFT:
	.byte $E8, $33, $42, $08
	.byte $E8, $34, $42, $00
	.byte $E8, $35, $40, $F8
	.byte $E8, $36, $40, $F0
	.byte $F0, $37, $42, $08
	.byte $F0, $38, $42, $00
	.byte $F0, $39, $40, $F8
	.byte $F0, $3A, $40, $F0
	.byte $F8, $3B, $42, $08
	.byte $F8, $3C, $42, $00
	.byte $F8, $3D, $40, $F8
	.byte $F8, $3E, $40, $F0
	.byte $F8, $3F, $40, $E8
marco_duck03_LEFT_end:

marco_duck04_LEFT:
	.byte $E8, $24, $42, $08
	.byte $E8, $25, $42, $00
	.byte $E8, $26, $40, $F8
	.byte $E8, $27, $40, $F0
	.byte $F0, $28, $42, $08
	.byte $F0, $29, $42, $00
	.byte $F0, $2A, $40, $F8
	.byte $F0, $2B, $40, $F0
	.byte $F8, $2C, $42, $08
	.byte $F8, $2D, $42, $00
	.byte $F8, $2E, $40, $F8
	.byte $F8, $2F, $40, $F0
	.byte $F8, $30, $40, $E8
marco_duck04_LEFT_end:

marco_duck05_LEFT:
	.byte $E8, $31, $42, $08
	.byte $E8, $32, $42, $00
	.byte $E8, $33, $40, $F8
	.byte $E8, $34, $40, $F0
	.byte $F0, $35, $42, $08
	.byte $F0, $36, $42, $00
	.byte $F0, $37, $40, $F8
	.byte $F0, $38, $40, $F0
	.byte $F8, $39, $42, $08
	.byte $F8, $3A, $42, $00
	.byte $F8, $3B, $40, $F8
	.byte $F8, $3C, $40, $F0
	.byte $F8, $3D, $40, $E8
marco_duck05_LEFT_end:

marco_duck06_LEFT:
	.byte $E8, $00, $42, $08
	.byte $E8, $01, $42, $00
	.byte $E8, $02, $40, $F8
	.byte $E8, $03, $40, $F0
	.byte $F0, $04, $42, $08
	.byte $F0, $05, $42, $00
	.byte $F0, $06, $40, $F8
	.byte $F0, $07, $40, $F0
	.byte $F8, $08, $42, $08
	.byte $F8, $09, $42, $00
	.byte $F8, $0A, $40, $F8
	.byte $F8, $0B, $40, $F0
	.byte $F8, $0C, $40, $E8
marco_duck06_LEFT_end:

marco_duck07_LEFT:
	.byte $E8, $00, $42, $08
	.byte $E8, $01, $42, $00
	.byte $E8, $02, $40, $F8
	.byte $E8, $03, $40, $F0
	.byte $F0, $04, $42, $08
	.byte $F0, $05, $42, $00
	.byte $F0, $06, $40, $F8
	.byte $F0, $07, $40, $F0
	.byte $F8, $08, $42, $08
	.byte $F8, $09, $42, $00
	.byte $F8, $0A, $40, $F8
	.byte $F8, $0B, $40, $F0
	.byte $F8, $0C, $40, $E8
marco_duck07_LEFT_end:

marco_duck08_LEFT:
	.byte $E8, $31, $42, $08
	.byte $E8, $32, $42, $00
	.byte $E8, $33, $40, $F8
	.byte $E8, $34, $40, $F0
	.byte $F0, $35, $42, $08
	.byte $F0, $36, $42, $00
	.byte $F0, $37, $40, $F8
	.byte $F0, $38, $40, $F0
	.byte $F8, $39, $42, $08
	.byte $F8, $3A, $42, $00
	.byte $F8, $3B, $40, $F8
	.byte $F8, $3C, $40, $F0
	.byte $F8, $3D, $40, $E8
marco_duck08_LEFT_end:

marco_duck09_LEFT:
	.byte $E8, $24, $42, $08
	.byte $E8, $25, $42, $00
	.byte $E8, $26, $40, $F8
	.byte $E8, $27, $40, $F0
	.byte $F0, $28, $42, $08
	.byte $F0, $29, $42, $00
	.byte $F0, $2A, $40, $F8
	.byte $F0, $2B, $40, $F0
	.byte $F8, $2C, $42, $08
	.byte $F8, $2D, $42, $00
	.byte $F8, $2E, $40, $F8
	.byte $F8, $2F, $40, $F0
	.byte $F8, $30, $40, $E8
marco_duck09_LEFT_end:

marco_duck10_LEFT:
	.byte $E8, $33, $42, $08
	.byte $E8, $34, $42, $00
	.byte $E8, $35, $40, $F8
	.byte $E8, $36, $40, $F0
	.byte $F0, $37, $42, $08
	.byte $F0, $38, $42, $00
	.byte $F0, $39, $40, $F8
	.byte $F0, $3A, $40, $F0
	.byte $F8, $3B, $42, $08
	.byte $F8, $3C, $42, $00
	.byte $F8, $3D, $40, $F8
	.byte $F8, $3E, $40, $F0
	.byte $F8, $3F, $40, $E8
marco_duck10_LEFT_end:

marco_run01_LEFT:
	.byte $D8, $0D, $40, $FB
	.byte $D8, $0E, $40, $F3
	.byte $E0, $0F, $42, $03
	.byte $E0, $10, $40, $FB
	.byte $E0, $11, $40, $F3
	.byte $E8, $12, $42, $03
	.byte $E8, $13, $40, $FB
	.byte $E8, $14, $40, $F3
	.byte $E8, $15, $40, $EB
	.byte $F0, $16, $42, $03
	.byte $F0, $17, $42, $FB
	.byte $F0, $18, $42, $F3
	.byte $F0, $19, $40, $EB
	.byte $F8, $1A, $42, $03
	.byte $F8, $1B, $42, $FB
	.byte $F8, $1C, $42, $F3
marco_run01_LEFT_end:

marco_run02_LEFT:
	.byte $D7, $1D, $40, $FB
	.byte $D7, $1E, $40, $F3
	.byte $DF, $1F, $42, $03
	.byte $DF, $20, $40, $FB
	.byte $DF, $21, $40, $F3
	.byte $E7, $22, $42, $03
	.byte $E7, $23, $40, $FB
	.byte $E7, $24, $40, $F3
	.byte $E7, $25, $40, $EB
	.byte $EF, $26, $42, $03
	.byte $EF, $27, $42, $FB
	.byte $EF, $28, $42, $F3
	.byte $EF, $29, $40, $EB
	.byte $F7, $2A, $42, $03
	.byte $F7, $2B, $42, $FB
	.byte $F7, $2C, $42, $F3
	.byte $FF, $2D, $40, $03
	.byte $FF, $2E, $40, $FB
	.byte $FF, $2F, $40, $F3
marco_run02_LEFT_end:

marco_run03_LEFT:
	.byte $D6, $00, $40, $03
	.byte $D6, $01, $40, $FB
	.byte $D6, $02, $40, $F3
	.byte $DE, $03, $42, $03
	.byte $DE, $04, $40, $FB
	.byte $DE, $05, $40, $F3
	.byte $E6, $06, $42, $03
	.byte $E6, $07, $40, $FB
	.byte $E6, $08, $40, $F3
	.byte $E6, $09, $40, $EB
	.byte $EE, $0A, $42, $03
	.byte $EE, $0B, $42, $FB
	.byte $EE, $0C, $42, $F3
	.byte $EE, $0D, $40, $EB
	.byte $F6, $0E, $42, $03
	.byte $F6, $0F, $42, $FB
	.byte $F6, $10, $42, $F3
marco_run03_LEFT_end:

marco_run04_LEFT:
	.byte $D5, $11, $40, $FE
	.byte $D5, $12, $40, $F6
	.byte $D5, $13, $40, $EE
	.byte $DD, $14, $42, $06
	.byte $DD, $15, $40, $FE
	.byte $DD, $16, $40, $F6
	.byte $E5, $17, $42, $06
	.byte $E5, $18, $40, $FE
	.byte $E5, $19, $40, $F6
	.byte $E5, $1A, $40, $EE
	.byte $ED, $1B, $42, $06
	.byte $ED, $1C, $42, $FE
	.byte $ED, $1D, $42, $F6
	.byte $ED, $1E, $40, $EE
	.byte $F5, $1F, $42, $06
	.byte $F5, $20, $42, $FE
	.byte $F5, $21, $42, $F6
	.byte $F5, $22, $42, $EE
	.byte $FD, $23, $42, $06
marco_run04_LEFT_end:

marco_run05_LEFT:
	.byte $D8, $24, $40, $04
	.byte $D8, $25, $40, $FC
	.byte $D8, $26, $40, $F4
	.byte $E0, $27, $42, $04
	.byte $E0, $28, $40, $FC
	.byte $E0, $29, $40, $F4
	.byte $E8, $2A, $42, $04
	.byte $E8, $2B, $40, $FC
	.byte $E8, $2C, $40, $F4
	.byte $E8, $2D, $40, $EC
	.byte $F0, $2E, $42, $04
	.byte $F0, $2F, $42, $FC
	.byte $F0, $30, $40, $F4
	.byte $F0, $31, $40, $EC
	.byte $F8, $32, $42, $04
	.byte $F8, $33, $42, $FC
	.byte $F8, $34, $42, $F4
marco_run05_LEFT_end:

marco_run06_LEFT:
	.byte $D8, $30, $40, $04
	.byte $D8, $31, $40, $FC
	.byte $D8, $32, $40, $F4
	.byte $E0, $33, $42, $04
	.byte $E0, $34, $40, $FC
	.byte $E0, $35, $40, $F4
	.byte $E8, $36, $42, $04
	.byte $E8, $37, $40, $FC
	.byte $E8, $38, $40, $F4
	.byte $E8, $39, $40, $EC
	.byte $F0, $3A, $42, $04
	.byte $F0, $3B, $42, $FC
	.byte $F0, $3C, $40, $F4
	.byte $F0, $3D, $40, $EC
	.byte $F8, $3E, $42, $04
	.byte $F8, $3F, $42, $FC
marco_run06_LEFT_end:

marco_run07_LEFT:
	.byte $D7, $00, $42, $03
	.byte $D7, $01, $40, $FB
	.byte $D7, $02, $40, $F3
	.byte $DF, $03, $42, $03
	.byte $DF, $04, $40, $FB
	.byte $DF, $05, $40, $F3
	.byte $E7, $06, $42, $03
	.byte $E7, $07, $40, $FB
	.byte $E7, $08, $40, $F3
	.byte $E7, $09, $40, $EB
	.byte $EF, $0A, $42, $03
	.byte $EF, $0B, $42, $FB
	.byte $EF, $0C, $40, $F3
	.byte $EF, $0D, $40, $EB
	.byte $F7, $0E, $42, $03
	.byte $F7, $0F, $42, $FB
	.byte $F7, $10, $42, $F3
marco_run07_LEFT_end:

marco_run08_LEFT:
	.byte $D6, $11, $40, $07
	.byte $D6, $12, $40, $FF
	.byte $D6, $13, $40, $F7
	.byte $D6, $14, $40, $EF
	.byte $DE, $15, $42, $07
	.byte $DE, $16, $42, $FF
	.byte $DE, $17, $40, $F7
	.byte $DE, $18, $40, $EF
	.byte $E6, $19, $42, $07
	.byte $E6, $1A, $42, $FF
	.byte $E6, $1B, $40, $F7
	.byte $E6, $1C, $40, $EF
	.byte $E6, $1D, $40, $E7
	.byte $EE, $1E, $42, $07
	.byte $EE, $1F, $42, $FF
	.byte $EE, $20, $42, $F7
	.byte $EE, $21, $40, $EF
	.byte $EE, $22, $40, $E7
	.byte $F6, $23, $42, $07
	.byte $F6, $24, $42, $FF
	.byte $F6, $25, $42, $F7
	.byte $F6, $26, $42, $EF
marco_run08_LEFT_end:

marco_run09_LEFT:
	.byte $D8, $27, $40, $03
	.byte $D8, $28, $40, $FB
	.byte $D8, $29, $40, $F3
	.byte $E0, $2A, $42, $03
	.byte $E0, $2B, $40, $FB
	.byte $E0, $2C, $40, $F3
	.byte $E8, $2D, $42, $03
	.byte $E8, $2E, $40, $FB
	.byte $E8, $2F, $40, $F3
	.byte $E8, $30, $40, $EB
	.byte $F0, $31, $42, $03
	.byte $F0, $32, $42, $FB
	.byte $F0, $33, $42, $F3
	.byte $F0, $34, $40, $EB
	.byte $F8, $35, $42, $03
	.byte $F8, $36, $42, $FB
	.byte $F8, $37, $42, $F3
marco_run09_LEFT_end:

marco_shoot01_LEFT:
	.byte $DB, $00, $42, $03
	.byte $DB, $01, $40, $FB
	.byte $DB, $02, $40, $F3
	.byte $DB, $03, $40, $E3
	.byte $DB, $04, $40, $DB
	.byte $E3, $05, $42, $03
	.byte $E3, $06, $40, $FB
	.byte $E3, $07, $40, $F3
	.byte $E3, $08, $40, $EB
	.byte $E3, $09, $40, $E3
	.byte $E3, $0A, $40, $DB
	.byte $E3, $0B, $40, $D3
	.byte $EB, $0C, $42, $03
	.byte $EB, $0D, $42, $FB
	.byte $EB, $0E, $40, $F3
	.byte $EB, $0F, $40, $EB
	.byte $F3, $10, $42, $03
	.byte $F3, $11, $42, $FB
	.byte $F3, $12, $42, $F3
	.byte $FB, $13, $42, $03
	.byte $FB, $14, $42, $FB
	.byte $FB, $15, $42, $F3
marco_shoot01_LEFT_end:

marco_shoot02_LEFT:
	.byte $DB, $16, $42, $03
	.byte $DB, $17, $40, $FB
	.byte $DB, $18, $40, $F3
	.byte $DB, $19, $40, $EB
	.byte $DB, $1A, $40, $E3
	.byte $DB, $1B, $40, $DB
	.byte $DB, $1C, $40, $D3
	.byte $E3, $1D, $42, $03
	.byte $E3, $1E, $40, $FB
	.byte $E3, $1F, $40, $F3
	.byte $E3, $20, $40, $EB
	.byte $E3, $21, $40, $E3
	.byte $E3, $22, $40, $DB
	.byte $E3, $23, $40, $D3
	.byte $EB, $24, $42, $03
	.byte $EB, $25, $43, $FB
	.byte $EB, $26, $40, $F3
	.byte $EB, $27, $40, $EB
	.byte $F3, $28, $42, $03
	.byte $F3, $29, $43, $FB
	.byte $F3, $2A, $43, $F3
	.byte $FB, $2B, $42, $03
	.byte $FB, $2C, $43, $FB
	.byte $FB, $2D, $43, $F3
marco_shoot02_LEFT_end:

marco_shoot03_LEFT:
	.byte $DB, $00, $42, $04
	.byte $DB, $01, $40, $FC
	.byte $DB, $02, $40, $F4
	.byte $DB, $03, $40, $EC
	.byte $DB, $04, $40, $E4
	.byte $E3, $05, $42, $04
	.byte $E3, $06, $40, $FC
	.byte $E3, $07, $40, $F4
	.byte $E3, $08, $40, $EC
	.byte $E3, $09, $40, $E4
	.byte $EB, $0A, $42, $04
	.byte $EB, $0B, $43, $FC
	.byte $EB, $0C, $40, $F4
	.byte $EB, $0D, $40, $EC
	.byte $F3, $0E, $42, $04
	.byte $F3, $0F, $42, $FC
	.byte $F3, $10, $43, $F4
	.byte $FB, $11, $42, $04
	.byte $FB, $12, $42, $FC
	.byte $FB, $13, $43, $F4
marco_shoot03_LEFT_end:

marco_shoot04_LEFT:
	.byte $D9, $14, $40, $FC
	.byte $D9, $15, $40, $F4
	.byte $D9, $16, $40, $EC
	.byte $D9, $17, $40, $E4
	.byte $E1, $18, $42, $04
	.byte $E1, $19, $40, $FC
	.byte $E1, $1A, $40, $F4
	.byte $E1, $1B, $40, $EC
	.byte $E1, $1C, $40, $E4
	.byte $E9, $1D, $42, $04
	.byte $E9, $1E, $40, $FC
	.byte $E9, $1F, $40, $F4
	.byte $E9, $20, $40, $EC
	.byte $F1, $21, $42, $04
	.byte $F1, $22, $42, $FC
	.byte $F1, $23, $42, $F4
	.byte $F9, $24, $42, $04
	.byte $F9, $25, $42, $FC
	.byte $F9, $26, $42, $F4
marco_shoot04_LEFT_end:

