;#######################################################
;
; Generated by SPReD-SMS Copyright 2017-2022 0x8BitDev
;
;#######################################################

.define	IMAGE_SPR_MODE_8X16	0
.define	IMAGE_SPR_CHR_BPP	4
.define	IMAGE_SPR_CHRS_OFFSET	0	; first CHR index in a CHR bank


;chr0:	.incbin "image_chr0.bin"	; 1280 bytes

;image_CHR_arr:	
;	.word 1280, chr0


image_palette:
	.byte $00, $30, $20, $20, $00, $34, $04, $3F, $0B, $3A, $25, $15, $3A, $03, $02, $15


image_num_frames:
	.byte $01
image_frames_data:
sonic_frame:
	.word sonic


	; #1: Y pos, #2: X pos, #3: CHR index

sonic:
	.byte sonic_end - sonic - 2	; data size
	.byte 0		; GFX bank index (chr0)

	.byte $00, $10, $00
	.byte $00, $18, $01
	.byte $00, $20, $02
	.byte $08, $00, $03
	.byte $08, $08, $04
	.byte $08, $10, $05
	.byte $08, $18, $06
	.byte $08, $20, $07
	.byte $08, $28, $08
	.byte $10, $00, $09
	.byte $10, $08, $0A
	.byte $10, $10, $0B
	.byte $10, $18, $0C
	.byte $10, $20, $0D
	.byte $10, $28, $0E
	.byte $10, $30, $0F
	.byte $18, $00, $10
	.byte $18, $08, $11
	.byte $18, $10, $12
	.byte $18, $18, $13
	.byte $18, $20, $14
	.byte $18, $28, $15
	.byte $20, $00, $16
	.byte $20, $08, $17
	.byte $20, $10, $18
	.byte $20, $18, $19
	.byte $20, $20, $1A
	.byte $20, $28, $1B
	.byte $28, $00, $1C
	.byte $28, $08, $1D
	.byte $28, $10, $1E
	.byte $28, $18, $1F
	.byte $28, $20, $20
	.byte $28, $28, $21
	.byte $30, $00, $22
	.byte $30, $08, $23
	.byte $30, $10, $24
	.byte $30, $18, $25
	.byte $38, $10, $26
	.byte $38, $18, $27
sonic_end:

