;#######################################################
;
; Generated by MAPeD-NES Copyright 2017-2020 0x8BitDev
;
;#######################################################

; export options:
;	- tiles 4x4/(columns)
;	- attributes per block
;	- properties per block
;	- mode: bidirectional scrolling
;	- layout: adjacent screen indices (no marks)
;	- no entities


MAP_DATA_MAGIC = $2904A

; data flags:
MAP_FLAG_TILES2X2                 = $01
MAP_FLAG_TILES4X4                 = $02
MAP_FLAG_RLE                      = $04
MAP_FLAG_DIR_COLUMNS              = $08
MAP_FLAG_DIR_ROWS                 = $10
MAP_FLAG_MODE_MULTIDIR_SCROLL     = $20
MAP_FLAG_MODE_BIDIR_SCROLL        = $40
MAP_FLAG_MODE_STATIC_SCREENS      = $80
MAP_FLAG_ENTITIES                 = $100
MAP_FLAG_ENTITY_SCREEN_COORDS     = $200
MAP_FLAG_ENTITY_MAP_COORS         = $400
MAP_FLAG_LAYOUT_ADJACENT_SCREENS  = $800
MAP_FLAG_LAYOUT_ADJACENT_SCR_INDS = $1000
MAP_FLAG_LAYOUT_MATRIX            = $2000
MAP_FLAG_MARKS                    = $4000
MAP_FLAG_ATTRS_PER_BLOCK          = $8000
MAP_FLAG_ATTRS_PER_CHR            = $10000
MAP_FLAG_PROP_ID_PER_BLOCK        = $20000
MAP_FLAG_PROP_ID_PER_CHR          = $40000

; *** GLOBAL DATA ***

; chr0:	.incbin "tilemap_chr0.bin"		; (1904)
; chr1:	.incbin "tilemap_chr1.bin"		; (2048)

tilemap_Blocks:	.incbin "tilemap_Blocks.bin"	; (388) blocks array of all exported data banks ( 4 bytes per block )
tilemap_Props:	.incbin "tilemap_Props.bin"	; (97) block properties array of all exported data banks ( 1 byte per block; data offset = props offset / 4 )

tilemap_BlocksPropsOffs:
	.word 0	; (chr0)
	.word 192	; (chr1)

tilemap_Tiles:	.incbin "tilemap_Tiles.bin"	; (776) tiles (4x4) array of all exported data banks ( 4 bytes per tile )

tilemap_TilesOffs:
	.word 0	; (chr0)
	.word 144	; (chr1)

tilemap_Attrs:	.incbin "tilemap_Attrs.bin"	; (194) attributes array of all exported data banks ( 1 byte per attribute ), data offset = tiles offset / 4
tilemap_TilesScr:	.incbin "tilemap_TilesScr.bin"	; (832) tiles (4x4) array for each screen ( 64 bytes per screen \ 1 byte per tile )
tilemap_Plts:	.incbin "tilemap_Plts.bin"	; (32) palettes array of all exported data banks ( data offset = chr_id * 16 )

; *** Lev0 ***

Lev0_StartScr:	.word Lev0Scr18

Lev0Scr5:
	.byte 1	; chr_id

	.byte 7	; screen index

; adjacent screen indices ( the valid values are $00 - $FE, $FF - means no screen )
; use the Lev0_ScrArr array to get a screen description by adjacent screen index
	.byte $FF	; left adjacent screen index
	.byte $FF	; up adjacent screen index
	.byte $06	; right adjacent screen index
	.byte $0E	; down adjacent screen index

Lev0Scr6:
	.byte 1

	.byte 8

	.byte $05
	.byte $FF
	.byte $07
	.byte $FF

Lev0Scr7:
	.byte 1

	.byte 9

	.byte $06
	.byte $FF
	.byte $FF
	.byte $10

Lev0Scr14:
	.byte 1

	.byte 6

	.byte $FF
	.byte $05
	.byte $FF
	.byte $17

Lev0Scr16:
	.byte 1

	.byte 10

	.byte $FF
	.byte $07
	.byte $FF
	.byte $19

Lev0Scr18:
	.byte 0

	.byte 1

	.byte $FF
	.byte $FF
	.byte $13
	.byte $FF

Lev0Scr19:
	.byte 0

	.byte 0

	.byte $12
	.byte $FF
	.byte $14
	.byte $FF

Lev0Scr20:
	.byte 1

	.byte 2

	.byte $13
	.byte $FF
	.byte $15
	.byte $FF

Lev0Scr21:
	.byte 1

	.byte 3

	.byte $14
	.byte $FF
	.byte $16
	.byte $FF

Lev0Scr22:
	.byte 1

	.byte 4

	.byte $15
	.byte $FF
	.byte $17
	.byte $FF

Lev0Scr23:
	.byte 1

	.byte 5

	.byte $16
	.byte $0E
	.byte $FF
	.byte $FF

Lev0Scr25:
	.byte 1

	.byte 11

	.byte $FF
	.byte $10
	.byte $1A
	.byte $FF

Lev0Scr26:
	.byte 1

	.byte 12

	.byte $19
	.byte $FF
	.byte $FF
	.byte $FF

; screens array
Lev0_ScrArr:
	.word $00
	.word $00
	.word $00
	.word $00
	.word $00
	.word Lev0Scr5
	.word Lev0Scr6
	.word Lev0Scr7
	.word $00
	.word $00
	.word $00
	.word $00
	.word $00
	.word $00
	.word Lev0Scr14
	.word $00
	.word Lev0Scr16
	.word $00
	.word Lev0Scr18
	.word Lev0Scr19
	.word Lev0Scr20
	.word Lev0Scr21
	.word Lev0Scr22
	.word Lev0Scr23
	.word $00
	.word Lev0Scr25
	.word Lev0Scr26
