;############################################################
;
; Generated by MAPeD-PCE (x64) Copyright 2017-2023 0x8BitDev
;
;############################################################

; *** LAYOUTS DATA ***

; *** Lev0 ***

_Lev0_TilesCnt	= 256	; map tiles count
_Lev0_StartScr	= 30	; start screen
_Lev0_WScrCnt	= 10	; number of screens in width
_Lev0_HScrCnt	= 4	; number of screens in height

_Lev0_Layout:	
	.word _Lev0Scr0
	.word _Lev0Scr1
	.word _Lev0Scr2
	.word _Lev0Scr3
	.word _Lev0Scr4
	.word _Lev0Scr5
	.word _Lev0Scr6
	.word _Lev0Scr7
	.word _Lev0Scr8
	.word _Lev0Scr9
	.word _Lev0Scr10
	.word _Lev0Scr11
	.word _Lev0Scr12
	.word _Lev0Scr13
	.word _Lev0Scr14
	.word _Lev0Scr15
	.word _Lev0Scr16
	.word _Lev0Scr17
	.word _Lev0Scr18
	.word _Lev0Scr19
	.word _Lev0Scr20
	.word _Lev0Scr21
	.word _Lev0Scr22
	.word _Lev0Scr23
	.word _Lev0Scr24
	.word _Lev0Scr25
	.word _Lev0Scr26
	.word _Lev0Scr27
	.word _Lev0Scr28
	.word _Lev0Scr29
	.word _Lev0Scr30
	.word _Lev0Scr31
	.word _Lev0Scr32
	.word _Lev0Scr33
	.word _Lev0Scr34
	.word _Lev0Scr35
	.word _Lev0Scr36
	.word _Lev0Scr37
	.word _Lev0Scr38
	.word _Lev0Scr39

_Lev0Scr0:
_Lev0Scr0EntsArr:
	.byte 8
	.word Instance135
	.word Instance137
	.word Instance142
	.word Instance143
	.word Instance141
	.word Instance117
	.word Instance116
	.word Instance115
Instance135:
	.byte $00	; entity instance number (0..n)
	.word logs_32x16	; base entity
	.word $00	; target entity
	.word $10	; map X
	.word $40	; map Y
	.byte $01	; properties count
	.byte $20	; properties data
Instance137:
	.byte $01	; entity instance number (0..n)
	.word door_closed	; base entity
	.word $00	; target entity
	.word $60	; map X
	.word $90	; map Y
	.byte $02	; properties count
	.byte $20, $20	; properties data
Instance142:
	.byte $02	; entity instance number (0..n)
	.word button	; base entity
	.word Instance141	; target entity
	.word $98	; map X
	.word $C0	; map Y
	.byte $00	; properties count
Instance143:
	.byte $03	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $80	; map X
	.word $30	; map Y
	.byte $00	; properties count
Instance141:
	.byte $04	; entity instance number (0..n)
	.word platform_32x10_vert64	; base entity
	.word $00	; target entity
	.word $C0	; map X
	.word $90	; map Y
	.byte $03	; properties count
	.byte $C0, $00, $40	; properties data
Instance117:
	.byte $05	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $18	; map X
	.word $88	; map Y
	.byte $00	; properties count
Instance116:
	.byte $06	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $48	; map X
	.word $58	; map Y
	.byte $00	; properties count
Instance115:
	.byte $07	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $18	; map X
	.word $28	; map Y
	.byte $00	; properties count

_Lev0Scr1:
_Lev0Scr1EntsArr:
	.byte 7
	.word Instance136
	.word Instance139
	.word Instance120
	.word Instance119
	.word Instance140
	.word Instance118
	.word Instance331
Instance136:
	.byte $08
	.word switch
	.word Instance137
	.word $150
	.word $80
	.byte $00
Instance139:
	.byte $09
	.word logs_32x16
	.word $00
	.word $110
	.word $90
	.byte $01
	.byte $20
Instance120:
	.byte $0A
	.word gem
	.word $00
	.word $1D8
	.word $60
	.byte $00
Instance119:
	.byte $0B
	.word gem
	.word $00
	.word $160
	.word $30
	.byte $00
Instance140:
	.byte $0C
	.word gem
	.word $00
	.word $130
	.word $78
	.byte $00
Instance118:
	.byte $0D
	.word gem
	.word $00
	.word $100
	.word $78
	.byte $00
Instance331:
	.byte $0E
	.word checkpoint
	.word $00
	.word $140
	.word $20
	.byte $00

_Lev0Scr2:
_Lev0Scr2EntsArr:
	.byte 5
	.word Instance101
	.word Instance144
	.word Instance121
	.word Instance340
	.word Instance99
Instance101:
	.byte $0F
	.word switch
	.word Instance99
	.word $208
	.word $60
	.byte $00
Instance144:
	.byte $10
	.word enemy_flying96
	.word $00
	.word $238
	.word $30
	.byte $02
	.byte $E0, $00
Instance121:
	.byte $11
	.word gem
	.word $00
	.word $2E0
	.word $60
	.byte $00
Instance340:
	.byte $12
	.word gem
	.word $00
	.word $270
	.word $20
	.byte $00
Instance99:
	.byte $13
	.word platform_32x10_horiz112
	.word $00
	.word $230
	.word $70
	.byte $03
	.byte $70, $70, $20

_Lev0Scr3:
_Lev0Scr3EntsArr:
	.byte 7
	.word Instance123
	.word Instance158
	.word Instance177
	.word Instance332
	.word Instance122
	.word Instance145
	.word Instance159
Instance123:
	.byte $14
	.word gem
	.word $00
	.word $3A8
	.word $A0
	.byte $00
Instance158:
	.byte $15
	.word gem
	.word $00
	.word $3A8
	.word $70
	.byte $00
Instance177:
	.byte $16
	.word portal_in_green
	.word Instance176
	.word $3E8
	.word $40
	.byte $01
	.byte $01
Instance332:
	.byte $17
	.word checkpoint
	.word $00
	.word $3D0
	.word $90
	.byte $00
Instance122:
	.byte $18
	.word gem
	.word $00
	.word $340
	.word $80
	.byte $00
Instance145:
	.byte $19
	.word enemy_flying96
	.word $00
	.word $340
	.word $50
	.byte $02
	.byte $E0, $00
Instance159:
	.byte $1A
	.word gem
	.word $00
	.word $340
	.word $50
	.byte $00

_Lev0Scr4:
_Lev0Scr4EntsArr:
	.byte 7
	.word Instance174
	.word Instance188
	.word Instance193
	.word Instance190
	.word Instance196
	.word Instance194
	.word Instance195
Instance174:
	.byte $1B
	.word door_closed
	.word $00
	.word $420
	.word $20
	.byte $02
	.byte $20, $20
Instance188:
	.byte $1C
	.word switch
	.word Instance174
	.word $4D8
	.word $50
	.byte $00
Instance193:
	.byte $1D
	.word enemy_walking96
	.word $00
	.word $470
	.word $A0
	.byte $03
	.byte $E0, $00, $00
Instance190:
	.byte $1E
	.word heavy_load_lifted
	.word $00
	.word $498
	.word $00
	.byte $03
	.byte $A0, $00, $F0
Instance196:
	.byte $1F
	.word gem
	.word $00
	.word $4D8
	.word $20
	.byte $00
Instance194:
	.byte $20
	.word gem
	.word $00
	.word $458
	.word $20
	.byte $00
Instance195:
	.byte $21
	.word gem
	.word $00
	.word $4A0
	.word $88
	.byte $00

_Lev0Scr5:
_Lev0Scr5EntsArr:
	.byte 6
	.word Instance220
	.word Instance229
	.word Instance230
	.word Instance223
	.word Instance224
	.word Instance225
Instance220:
	.byte $22
	.word platform_32x10_horiz112
	.word $00
	.word $560
	.word $C0
	.byte $03
	.byte $F0, $00, $A0
Instance229:
	.byte $23
	.word gem
	.word $00
	.word $540
	.word $20
	.byte $00
Instance230:
	.byte $24
	.word gem
	.word $00
	.word $5B8
	.word $20
	.byte $00
Instance223:
	.byte $25
	.word enemy_walking112
	.word $00
	.word $500
	.word $40
	.byte $02
	.byte $F0, $00
Instance224:
	.byte $26
	.word enemy_walking112
	.word $00
	.word $580
	.word $40
	.byte $02
	.byte $70, $40
Instance225:
	.byte $27
	.word switch
	.word Instance299
	.word $580
	.word $50
	.byte $00

_Lev0Scr6:
_Lev0Scr6EntsArr:
	.byte 7
	.word Instance234
	.word Instance239
	.word Instance238
	.word Instance236
	.word Instance241
	.word Instance243
	.word Instance237
Instance234:
	.byte $28
	.word portal_out_red
	.word $00
	.word $628
	.word $A0
	.byte $00
Instance239:
	.byte $29
	.word gem
	.word $00
	.word $658
	.word $18
	.byte $00
Instance238:
	.byte $2A
	.word gem
	.word $00
	.word $6D0
	.word $18
	.byte $00
Instance236:
	.byte $2B
	.word platform_32x10_vert64
	.word $00
	.word $6E0
	.word $80
	.byte $03
	.byte $C0, $00, $E0
Instance241:
	.byte $2C
	.word enemy_walking112
	.word $00
	.word $650
	.word $A0
	.byte $03
	.byte $F0, $00, $20
Instance243:
	.byte $2D
	.word gem
	.word $00
	.word $688
	.word $88
	.byte $00
Instance237:
	.byte $2E
	.word switch
	.word Instance245
	.word $620
	.word $50
	.byte $00

_Lev0Scr7:
_Lev0Scr7EntsArr:
	.byte 6
	.word Instance242
	.word Instance244
	.word Instance245
	.word Instance259
	.word Instance249
	.word Instance246
Instance242:
	.byte $2F
	.word gem
	.word $00
	.word $720
	.word $B0
	.byte $00
Instance244:
	.byte $30
	.word enemy_standing
	.word $00
	.word $760
	.word $20
	.byte $03
	.byte $81, $01, $40
Instance245:
	.byte $31
	.word door_closed
	.word $00
	.word $790
	.word $80
	.byte $02
	.byte $20, $20
Instance259:
	.byte $32
	.word gem
	.word $00
	.word $7D8
	.word $18
	.byte $00
Instance249:
	.byte $33
	.word switch
	.word Instance251
	.word $780
	.word $30
	.byte $00
Instance246:
	.byte $34
	.word switch
	.word Instance300
	.word $7C0
	.word $B0
	.byte $00

_Lev0Scr8:
_Lev0Scr8EntsArr:
	.byte 7
	.word Instance250
	.word Instance251
	.word Instance255
	.word Instance256
	.word Instance258
	.word Instance257
	.word Instance252
Instance250:
	.byte $35
	.word portal_in_green
	.word Instance215
	.word $8C8
	.word $20
	.byte $01
	.byte $01
Instance251:
	.byte $36
	.word door_closed
	.word $00
	.word $8A0
	.word $00
	.byte $02
	.byte $20, $20
Instance255:
	.byte $37
	.word enemy_walking96
	.word $00
	.word $810
	.word $A0
	.byte $03
	.byte $E0, $00, $00
Instance256:
	.byte $38
	.word gem
	.word $00
	.word $8D0
	.word $B0
	.byte $00
Instance258:
	.byte $39
	.word gem
	.word $00
	.word $840
	.word $B0
	.byte $00
Instance257:
	.byte $3A
	.word gem
	.word $00
	.word $840
	.word $58
	.byte $00
Instance252:
	.byte $3B
	.word platform_32x10_horiz112
	.word $00
	.word $800
	.word $40
	.byte $03
	.byte $70, $70, $A0

_Lev0Scr9:
_Lev0Scr9EntsArr:
	.byte 6
	.word Instance313
	.word Instance310
	.word Instance314
	.word Instance315
	.word Instance339
	.word Instance346
Instance313:
	.byte $3C
	.word gem
	.word $00
	.word $990
	.word $08
	.byte $00
Instance310:
	.byte $3D
	.word enemy_flying96
	.word $00
	.word $960
	.word $18
	.byte $03
	.byte $60, $D0, $6D
Instance314:
	.byte $3E
	.word platform_32x10_horiz32
	.word $00
	.word $9C0
	.word $50
	.byte $03
	.byte $A0, $00, $10
Instance315:
	.byte $3F
	.word switch
	.word Instance317
	.word $990
	.word $40
	.byte $00
Instance339:
	.byte $40
	.word level_passed
	.word $00
	.word $988
	.word $80
	.byte $00
Instance346:
	.byte $41
	.word gem
	.word $00
	.word $9B8
	.word $90
	.byte $00

_Lev0Scr10:
_Lev0Scr10EntsArr:
	.byte 4
	.word Instance109
	.word Instance129
	.word Instance146
	.word Instance328
Instance109:
	.byte $42
	.word gem
	.word $00
	.word $70
	.word $130
	.byte $00
Instance129:
	.byte $43
	.word enemy_flying96
	.word $00
	.word $28
	.word $190
	.byte $02
	.byte $E0, $00
Instance146:
	.byte $44
	.word gem
	.word $00
	.word $C0
	.word $1A0
	.byte $00
Instance328:
	.byte $45
	.word checkpoint
	.word $00
	.word $D8
	.word $120
	.byte $00

_Lev0Scr11:
_Lev0Scr11EntsArr:
	.byte 3
	.word Instance113
	.word Instance130
	.word Instance110
Instance113:
	.byte $46
	.word gem
	.word $00
	.word $178
	.word $E1
	.byte $00
Instance130:
	.byte $47
	.word enemy_walking96
	.word $00
	.word $100
	.word $120
	.byte $03
	.byte $E0, $00, $00
Instance110:
	.byte $48
	.word gem
	.word $00
	.word $130
	.word $130
	.byte $00

_Lev0Scr12:
_Lev0Scr12EntsArr:
	.byte 4
	.word Instance112
	.word Instance125
	.word Instance160
	.word Instance111
Instance112:
	.byte $49
	.word gem
	.word $00
	.word $2B0
	.word $130
	.byte $00
Instance125:
	.byte $4A
	.word enemy_standing
	.word $00
	.word $290
	.word $120
	.byte $03
	.byte $81, $01, $40
Instance160:
	.byte $4B
	.word gem
	.word $00
	.word $218
	.word $1A0
	.byte $00
Instance111:
	.byte $4C
	.word gem
	.word $00
	.word $260
	.word $100
	.byte $00

_Lev0Scr13:
_Lev0Scr13EntsArr:
	.byte 7
	.word Instance133
	.word Instance157
	.word Instance155
	.word Instance156
	.word Instance154
	.word Instance149
	.word Instance150
Instance133:
	.byte $4D
	.word logs_32x16
	.word $00
	.word $3E0
	.word $130
	.byte $01
	.byte $20
Instance157:
	.byte $4E
	.word gem
	.word $00
	.word $330
	.word $130
	.byte $00
Instance155:
	.byte $4F
	.word gem
	.word $00
	.word $3B8
	.word $118
	.byte $00
Instance156:
	.byte $50
	.word gem
	.word $00
	.word $3E8
	.word $178
	.byte $00
Instance154:
	.byte $51
	.word enemy_flying96
	.word $00
	.word $330
	.word $108
	.byte $02
	.byte $E0, $00
Instance149:
	.byte $52
	.word enemy_walking96
	.word $00
	.word $310
	.word $1A0
	.byte $03
	.byte $60, $60, $20
Instance150:
	.byte $53
	.word switch
	.word Instance153
	.word $340
	.word $1B0
	.byte $00

_Lev0Scr14:
_Lev0Scr14EntsArr:
	.byte 6
	.word Instance131
	.word Instance184
	.word Instance185
	.word Instance186
	.word Instance232
	.word Instance187
Instance131:
	.byte $54
	.word logs_32x16
	.word $00
	.word $400
	.word $100
	.byte $01
	.byte $20
Instance184:
	.byte $55
	.word platform_32x10_horiz112
	.word $00
	.word $430
	.word $190
	.byte $03
	.byte $F0, $00, $20
Instance185:
	.byte $56
	.word button
	.word Instance184
	.word $4A0
	.word $130
	.byte $00
Instance186:
	.byte $57
	.word gem
	.word $00
	.word $448
	.word $128
	.byte $00
Instance232:
	.byte $58
	.word switch
	.word Instance302
	.word $4C0
	.word $F0
	.byte $00
Instance187:
	.byte $59
	.word gem
	.word $00
	.word $4C0
	.word $128
	.byte $00

_Lev0Scr15:
_Lev0Scr15EntsArr:
	.byte 3
	.word Instance226
	.word Instance228
	.word Instance227
Instance226:
	.byte $5A
	.word enemy_flying96
	.word $00
	.word $510
	.word $128
	.byte $02
	.byte $E0, $00
Instance228:
	.byte $5B
	.word gem
	.word $00
	.word $5C8
	.word $160
	.byte $00
Instance227:
	.byte $5C
	.word gem
	.word $00
	.word $5C8
	.word $130
	.byte $00

_Lev0Scr16:
_Lev0Scr16EntsArr:
	.byte 3
	.word Instance260
	.word Instance263
	.word Instance268
Instance260:
	.byte $5D
	.word enemy_flying96
	.word $00
	.word $628
	.word $110
	.byte $02
	.byte $E0, $00
Instance263:
	.byte $5E
	.word gem
	.word $00
	.word $658
	.word $F8
	.byte $00
Instance268:
	.byte $5F
	.word gem
	.word $00
	.word $6C8
	.word $160
	.byte $00

_Lev0Scr17:
_Lev0Scr17EntsArr:
	.byte 6
	.word Instance262
	.word Instance264
	.word Instance267
	.word Instance261
	.word Instance337
	.word Instance345
Instance262:
	.byte $60
	.word enemy_standing
	.word $00
	.word $728
	.word $100
	.byte $03
	.byte $81, $01, $40
Instance264:
	.byte $61
	.word gem
	.word $00
	.word $750
	.word $110
	.byte $00
Instance267:
	.byte $62
	.word gem
	.word $00
	.word $7F0
	.word $110
	.byte $00
Instance261:
	.byte $63
	.word switch
	.word Instance272
	.word $708
	.word $110
	.byte $00
Instance337:
	.byte $64
	.word checkpoint
	.word $00
	.word $748
	.word $150
	.byte $00
Instance345:
	.byte $65
	.word gem
	.word $00
	.word $7C8
	.word $1B0
	.byte $00

_Lev0Scr18:
_Lev0Scr18EntsArr:
	.byte 7
	.word Instance272
	.word Instance273
	.word Instance274
	.word Instance275
	.word Instance298
	.word Instance297
	.word Instance271
Instance272:
	.byte $66
	.word platform_32x10_horiz32
	.word $00
	.word $8A0
	.word $120
	.byte $03
	.byte $A0, $00, $10
Instance273:
	.byte $67
	.word logs_32x16
	.word $00
	.word $8A0
	.word $190
	.byte $01
	.byte $20
Instance274:
	.byte $68
	.word gem
	.word $00
	.word $878
	.word $150
	.byte $00
Instance275:
	.byte $69
	.word gem
	.word $00
	.word $8D8
	.word $150
	.byte $00
Instance298:
	.byte $6A
	.word gem
	.word $00
	.word $878
	.word $1B0
	.byte $00
Instance297:
	.byte $6B
	.word gem
	.word $00
	.word $8D8
	.word $1B0
	.byte $00
Instance271:
	.byte $6C
	.word enemy_flying96
	.word $00
	.word $870
	.word $F8
	.byte $02
	.byte $60, $60

_Lev0Scr19:
_Lev0Scr19EntsArr:
	.byte 7
	.word Instance311
	.word Instance307
	.word Instance306
	.word Instance324
	.word Instance325
	.word Instance323
	.word Instance326
Instance311:
	.byte $6D
	.word gem
	.word $00
	.word $978
	.word $E0
	.byte $00
Instance307:
	.byte $6E
	.word enemy_flying96
	.word $00
	.word $948
	.word $F0
	.byte $02
	.byte $E0, $00
Instance306:
	.byte $6F
	.word platform_32x10_horiz112
	.word $00
	.word $930
	.word $130
	.byte $03
	.byte $70, $70, $A0
Instance324:
	.byte $70
	.word logs_32x16
	.word $00
	.word $9C0
	.word $180
	.byte $01
	.byte $20
Instance325:
	.byte $71
	.word gem
	.word $00
	.word $910
	.word $150
	.byte $00
Instance323:
	.byte $72
	.word logs_32x16
	.word $00
	.word $980
	.word $180
	.byte $01
	.byte $20
Instance326:
	.byte $73
	.word gem
	.word $00
	.word $988
	.word $150
	.byte $00

_Lev0Scr20:
_Lev0Scr20EntsArr:
	.byte 4
	.word Instance106
	.word Instance107
	.word Instance108
	.word Instance128
Instance106:
	.byte $74
	.word gem
	.word $00
	.word $D0
	.word $1F0
	.byte $00
Instance107:
	.byte $75
	.word gem
	.word $00
	.word $40
	.word $220
	.byte $00
Instance108:
	.byte $76
	.word gem
	.word $00
	.word $30
	.word $1C0
	.byte $00
Instance128:
	.byte $77
	.word enemy_flying96
	.word $00
	.word $50
	.word $270
	.byte $02
	.byte $E0, $00

_Lev0Scr21:
_Lev0Scr21EntsArr:
	.byte 3
	.word Instance126
	.word Instance103
	.word Instance105
Instance126:
	.byte $78
	.word enemy_standing
	.word $00
	.word $110
	.word $210
	.byte $03
	.byte $81, $01, $40
Instance103:
	.byte $79
	.word gem
	.word $00
	.word $1B8
	.word $220
	.byte $00
Instance105:
	.byte $7A
	.word gem
	.word $00
	.word $128
	.word $1C0
	.byte $00

_Lev0Scr22:
_Lev0Scr22EntsArr:
	.byte 5
	.word Instance161
	.word Instance163
	.word Instance166
	.word Instance167
	.word Instance165
Instance161:
	.byte $7B
	.word gem
	.word $00
	.word $218
	.word $240
	.byte $00
Instance163:
	.byte $7C
	.word gem
	.word $00
	.word $2B8
	.word $260
	.byte $00
Instance166:
	.byte $7D
	.word enemy_walking96
	.word $00
	.word $218
	.word $1E0
	.byte $03
	.byte $E0, $00, $00
Instance167:
	.byte $7E
	.word gem
	.word $00
	.word $248
	.word $1F0
	.byte $00
Instance165:
	.byte $7F
	.word platform_32x10_vert80
	.word $00
	.word $2B0
	.word $1B0
	.byte $03
	.byte $D0, $28, $E0

_Lev0Scr23:
_Lev0Scr23EntsArr:
	.byte 3
	.word Instance179
	.word Instance169
	.word Instance153
Instance179:
	.byte $80
	.word enemy_standing
	.word $00
	.word $330
	.word $200
	.byte $03
	.byte $81, $01, $40
Instance169:
	.byte $81
	.word gem
	.word $00
	.word $318
	.word $208
	.byte $00
Instance153:
	.byte $82
	.word platform_32x10_horiz32
	.word $00
	.word $390
	.word $1C0
	.byte $03
	.byte $A0, $00, $10

_Lev0Scr24:
_Lev0Scr24EntsArr:
	.byte 6
	.word Instance181
	.word Instance215
	.word Instance182
	.word Instance231
	.word Instance180
	.word Instance338
Instance181:
	.byte $83
	.word enemy_walking96
	.word $00
	.word $408
	.word $240
	.byte $03
	.byte $E0, $00, $00
Instance215:
	.byte $84
	.word portal_out_red
	.word $00
	.word $4E8
	.word $240
	.byte $00
Instance182:
	.byte $85
	.word gem
	.word $00
	.word $4D8
	.word $208
	.byte $00
Instance231:
	.byte $86
	.word gem
	.word $00
	.word $448
	.word $1D8
	.byte $00
Instance180:
	.byte $87
	.word gem
	.word $00
	.word $408
	.word $208
	.byte $00
Instance338:
	.byte $88
	.word checkpoint
	.word $00
	.word $4A0
	.word $240
	.byte $00

_Lev0Scr25:
_Lev0Scr25EntsArr:
	.byte 7
	.word Instance208
	.word Instance209
	.word Instance210
	.word Instance214
	.word Instance213
	.word Instance211
	.word Instance212
Instance208:
	.byte $89
	.word logs_32x16
	.word $00
	.word $580
	.word $260
	.byte $01
	.byte $20
Instance209:
	.byte $8A
	.word heavy_load_lowered
	.word $00
	.word $530
	.word $1C0
	.byte $03
	.byte $20, $20, $F0
Instance210:
	.byte $8B
	.word heavy_load_lifted
	.word $00
	.word $570
	.word $1C0
	.byte $03
	.byte $A0, $00, $F0
Instance214:
	.byte $8C
	.word gem
	.word $00
	.word $5C8
	.word $1E8
	.byte $00
Instance213:
	.byte $8D
	.word gem
	.word $00
	.word $510
	.word $250
	.byte $00
Instance211:
	.byte $8E
	.word portal_in_green
	.word Instance234
	.word $508
	.word $200
	.byte $01
	.byte $01
Instance212:
	.byte $8F
	.word gem
	.word $00
	.word $558
	.word $208
	.byte $00

_Lev0Scr26:
_Lev0Scr26EntsArr:
	.byte 4
	.word Instance233
	.word Instance198
	.word Instance334
	.word Instance200
Instance233:
	.byte $90
	.word gem
	.word $00
	.word $680
	.word $1D0
	.byte $00
Instance198:
	.byte $91
	.word platform_32x10_horiz112
	.word $00
	.word $640
	.word $210
	.byte $03
	.byte $70, $70, $20
Instance334:
	.byte $92
	.word checkpoint
	.word $00
	.word $6D0
	.word $280
	.byte $00
Instance200:
	.byte $93
	.word platform_32x10_vert80
	.word $00
	.word $610
	.word $1C0
	.byte $03
	.byte $D0, $00, $E0

_Lev0Scr27:
_Lev0Scr27EntsArr:
	.byte 4
	.word Instance202
	.word Instance216
	.word Instance341
	.word Instance414
Instance202:
	.byte $94
	.word switch
	.word Instance198
	.word $780
	.word $1D0
	.byte $00
Instance216:
	.byte $95
	.word gem
	.word $00
	.word $728
	.word $260
	.byte $00
Instance341:
	.byte $96
	.word gem
	.word $00
	.word $7A8
	.word $240
	.byte $00
Instance414:
	.byte $97
	.word enemy_walking96
	.word $00
	.word $728
	.word $1F0
	.byte $03
	.byte $E0, $00, $00

_Lev0Scr28:
_Lev0Scr28EntsArr:
	.byte 7
	.word Instance290
	.word Instance292
	.word Instance295
	.word Instance291
	.word Instance293
	.word Instance289
	.word Instance294
Instance290:
	.byte $98
	.word logs_32x16
	.word $00
	.word $840
	.word $1E0
	.byte $01
	.byte $20
Instance292:
	.byte $99
	.word gem
	.word $00
	.word $850
	.word $270
	.byte $00
Instance295:
	.byte $9A
	.word logs_32x16
	.word $00
	.word $8C0
	.word $1E0
	.byte $01
	.byte $20
Instance291:
	.byte $9B
	.word switch
	.word Instance301
	.word $830
	.word $1D0
	.byte $00
Instance293:
	.byte $9C
	.word gem
	.word $00
	.word $828
	.word $218
	.byte $00
Instance289:
	.byte $9D
	.word enemy_walking112
	.word $00
	.word $870
	.word $210
	.byte $02
	.byte $F0, $00
Instance294:
	.byte $9E
	.word gem
	.word $00
	.word $8D8
	.word $218
	.byte $00

_Lev0Scr29:
_Lev0Scr29EntsArr:
	.byte 6
	.word Instance316
	.word Instance317
	.word Instance321
	.word Instance327
	.word Instance318
	.word Instance319
Instance316:
	.byte $9F
	.word switch
	.word Instance314
	.word $9D0
	.word $230
	.byte $00
Instance317:
	.byte $A0
	.word door_closed
	.word $00
	.word $9B0
	.word $200
	.byte $02
	.byte $20, $20
Instance321:
	.byte $A1
	.word gem
	.word $00
	.word $9D0
	.word $218
	.byte $00
Instance327:
	.byte $A2
	.word gem
	.word $00
	.word $978
	.word $1F8
	.byte $00
Instance318:
	.byte $A3
	.word platform_32x10_horiz112
	.word $00
	.word $960
	.word $1E8
	.byte $03
	.byte $70, $70, $20
Instance319:
	.byte $A4
	.word button
	.word Instance318
	.word $910
	.word $200
	.byte $00

_Lev0Scr30:
_Lev0Scr30EntsArr:
	.byte 7
	.word Instance97
	.word Instance91
	.word Instance92
	.word Instance94
	.word Instance93
	.word Instance98
	.word Instance96
Instance97:
	.byte $A5
	.word logs_32x16
	.word $00
	.word $80
	.word $310
	.byte $01
	.byte $20
Instance91:
	.byte $A6
	.word door_closed
	.word $00
	.word $C0
	.word $320
	.byte $02
	.byte $20, $20
Instance92:
	.byte $A7
	.word switch
	.word Instance91
	.word $B0
	.word $300
	.byte $00
Instance94:
	.byte $A8
	.word gem
	.word $00
	.word $18
	.word $2F8
	.byte $00
Instance93:
	.byte $A9
	.word gem
	.word $00
	.word $48
	.word $318
	.byte $00
Instance98:
	.byte $AA
	.word gem
	.word $00
	.word $D8
	.word $318
	.byte $00
Instance96:
	.byte $AB
	.word player_entity
	.word $00
	.word $98
	.word $340
	.byte $00

_Lev0Scr31:
_Lev0Scr31EntsArr:
	.byte 5
	.word Instance127
	.word Instance104
	.word Instance102
	.word Instance176
	.word Instance329
Instance127:
	.byte $AC
	.word gem
	.word $00
	.word $190
	.word $350
	.byte $00
Instance104:
	.byte $AD
	.word gem
	.word $00
	.word $118
	.word $2C0
	.byte $00
Instance102:
	.byte $AE
	.word gem
	.word $00
	.word $1B8
	.word $2A0
	.byte $00
Instance176:
	.byte $AF
	.word portal_out_red
	.word $00
	.word $188
	.word $2F0
	.byte $00
Instance329:
	.byte $B0
	.word checkpoint
	.word $00
	.word $108
	.word $340
	.byte $00

_Lev0Scr32:
_Lev0Scr32EntsArr:
	.byte 2
	.word Instance162
	.word Instance164
Instance162:
	.byte $B1
	.word gem
	.word $00
	.word $218
	.word $2C0
	.byte $00
Instance164:
	.byte $B2
	.word gem
	.word $00
	.word $2B8
	.word $2E0
	.byte $00

_Lev0Scr33:
_Lev0Scr33EntsArr:
	.byte 3
	.word Instance171
	.word Instance170
	.word Instance172
Instance171:
	.byte $B3
	.word gem
	.word $00
	.word $3E8
	.word $2B0
	.byte $00
Instance170:
	.byte $B4
	.word gem
	.word $00
	.word $3A8
	.word $2F0
	.byte $00
Instance172:
	.byte $B5
	.word gem
	.word $00
	.word $348
	.word $2D0
	.byte $00

_Lev0Scr34:
_Lev0Scr34EntsArr:
	.byte 1
	.word Instance173
Instance173:
	.byte $B6
	.word gem
	.word $00
	.word $488
	.word $2E0
	.byte $00

_Lev0Scr35:
_Lev0Scr35EntsArr:
	.byte 2
	.word Instance205
	.word Instance217
Instance205:
	.byte $B7
	.word gem
	.word $00
	.word $538
	.word $2C0
	.byte $00
Instance217:
	.byte $B8
	.word logs_32x16
	.word $00
	.word $580
	.word $2A8
	.byte $01
	.byte $20

_Lev0Scr36:
_Lev0Scr36EntsArr:
	.byte 1
	.word Instance344
Instance344:
	.byte $B9
	.word gem
	.word $00
	.word $6B8
	.word $2D0
	.byte $00

_Lev0Scr37:
_Lev0Scr37EntsArr:
	.byte 4
	.word Instance207
	.word Instance206
	.word Instance335
	.word Instance413
Instance207:
	.byte $BA
	.word gem
	.word $00
	.word $7B8
	.word $2C0
	.byte $00
Instance206:
	.byte $BB
	.word gem
	.word $00
	.word $718
	.word $2E0
	.byte $00
Instance335:
	.byte $BC
	.word checkpoint
	.word $00
	.word $7E0
	.word $340
	.byte $00
Instance413:
	.byte $BD
	.word enemy_walking112
	.word $00
	.word $738
	.word $340
	.byte $03
	.byte $F0, $00, $20

_Lev0Scr38:
_Lev0Scr38EntsArr:
	.byte 6
	.word Instance285
	.word Instance286
	.word Instance287
	.word Instance288
	.word Instance343
	.word Instance342
Instance285:
	.byte $BE
	.word platform_32x10_vert80
	.word $00
	.word $820
	.word $2F8
	.byte $03
	.byte $D0, $00, $E0
Instance286:
	.byte $BF
	.word platform_32x10_vert80
	.word $00
	.word $860
	.word $2D8
	.byte $03
	.byte $50, $50, $E0
Instance287:
	.byte $C0
	.word platform_32x10_vert80
	.word $00
	.word $8A0
	.word $2D8
	.byte $03
	.byte $D0, $00, $E0
Instance288:
	.byte $C1
	.word platform_32x10_vert80
	.word $00
	.word $8E0
	.word $2F0
	.byte $03
	.byte $50, $50, $E0
Instance343:
	.byte $C2
	.word gem
	.word $00
	.word $8C8
	.word $2B0
	.byte $00
Instance342:
	.byte $C3
	.word gem
	.word $00
	.word $848
	.word $2B0
	.byte $00

_Lev0Scr39:
_Lev0Scr39EntsArr:
	.byte 7
	.word Instance302
	.word Instance299
	.word Instance300
	.word Instance301
	.word Instance304
	.word Instance305
	.word Instance303
Instance302:
	.byte $C4
	.word door_closed
	.word $00
	.word $980
	.word $2A0
	.byte $02
	.byte $20, $20
Instance299:
	.byte $C5
	.word door_closed
	.word $00
	.word $990
	.word $2A0
	.byte $02
	.byte $20, $20
Instance300:
	.byte $C6
	.word door_closed
	.word $00
	.word $9A0
	.word $2A0
	.byte $02
	.byte $20, $20
Instance301:
	.byte $C7
	.word door_closed
	.word $00
	.word $9B0
	.word $2A0
	.byte $02
	.byte $20, $20
Instance304:
	.byte $C8
	.word gem
	.word $00
	.word $998
	.word $308
	.byte $00
Instance305:
	.byte $C9
	.word gem
	.word $00
	.word $968
	.word $350
	.byte $00
Instance303:
	.byte $CA
	.word gem
	.word $00
	.word $910
	.word $2B0
	.byte $00

_Lev0_EntInstCnt = 203	; number of entities instances
; *** Lev1 ***

_Lev1_TilesCnt	= 255	; map tiles count
_Lev1_StartScr	= 9	; start screen
_Lev1_WScrCnt	= 1	; number of screens in width
_Lev1_HScrCnt	= 10	; number of screens in height

_Lev1_Layout:	
	.word _Lev1Scr0
	.word _Lev1Scr1
	.word _Lev1Scr2
	.word _Lev1Scr3
	.word _Lev1Scr4
	.word _Lev1Scr5
	.word _Lev1Scr6
	.word _Lev1Scr7
	.word _Lev1Scr8
	.word _Lev1Scr9

_Lev1Scr0:
_Lev1Scr0EntsArr:
	.byte 6
	.word Instance386
	.word Instance349
	.word Instance387
	.word Instance350
	.word Instance388
	.word Instance389
Instance386:
	.byte $00	; entity instance number (0..n)
	.word level_passed	; base entity
	.word $00	; target entity
	.word $C8	; map X
	.word $40	; map Y
	.byte $00	; properties count
Instance349:
	.byte $01	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $28	; map X
	.word $10	; map Y
	.byte $00	; properties count
Instance387:
	.byte $02	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $50	; map X
	.word $28	; map Y
	.byte $00	; properties count
Instance350:
	.byte $03	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $78	; map X
	.word $10	; map Y
	.byte $00	; properties count
Instance388:
	.byte $04	; entity instance number (0..n)
	.word gem	; base entity
	.word $00	; target entity
	.word $A0	; map X
	.word $28	; map Y
	.byte $00	; properties count
Instance389:
	.byte $05	; entity instance number (0..n)
	.word platform_32x10_horiz112	; base entity
	.word $00	; target entity
	.word $50	; map X
	.word $C8	; map Y
	.byte $03	; properties count
	.byte $70, $70, $20	; properties data

_Lev1Scr1:
_Lev1Scr1EntsArr:
	.byte 6
	.word Instance396
	.word Instance399
	.word Instance397
	.word Instance398
	.word Instance401
	.word Instance402
Instance396:
	.byte $06
	.word switch
	.word Instance389
	.word $30
	.word $130
	.byte $00
Instance399:
	.byte $07
	.word enemy_flying96
	.word $00
	.word $40
	.word $100
	.byte $02
	.byte $E0, $00
Instance397:
	.byte $08
	.word platform_32x10_vert80
	.word $00
	.word $C0
	.word $110
	.byte $03
	.byte $C0, $00, $E0
Instance398:
	.byte $09
	.word enemy_flying96
	.word $00
	.word $18
	.word $160
	.byte $02
	.byte $E0, $00
Instance401:
	.byte $0A
	.word gem
	.word $00
	.word $30
	.word $160
	.byte $00
Instance402:
	.byte $0B
	.word gem
	.word $00
	.word $88
	.word $118
	.byte $00

_Lev1Scr2:
_Lev1Scr2EntsArr:
	.byte 5
	.word Instance394
	.word Instance395
	.word Instance400
	.word Instance406
	.word Instance405
Instance394:
	.byte $0C
	.word switch
	.word Instance390
	.word $48
	.word $230
	.byte $00
Instance395:
	.byte $0D
	.word platform_32x10_vert80
	.word Instance392
	.word $B8
	.word $1F0
	.byte $03
	.byte $D0, $00, $60
Instance400:
	.byte $0E
	.word gem
	.word $00
	.word $C0
	.word $1B8
	.byte $00
Instance406:
	.byte $0F
	.word gem
	.word $00
	.word $20
	.word $208
	.byte $00
Instance405:
	.byte $10
	.word gem
	.word $00
	.word $C0
	.word $248
	.byte $00

_Lev1Scr3:
_Lev1Scr3EntsArr:
	.byte 8
	.word Instance384
	.word Instance385
	.word Instance390
	.word Instance393
	.word Instance391
	.word Instance392
	.word Instance403
	.word Instance408
Instance384:
	.byte $11
	.word enemy_walking112
	.word $00
	.word $48
	.word $360
	.byte $03
	.byte $60, $60, $20
Instance385:
	.byte $12
	.word gem
	.word $00
	.word $B0
	.word $370
	.byte $00
Instance390:
	.byte $13
	.word door_closed
	.word $00
	.word $30
	.word $2D0
	.byte $02
	.byte $20, $20
Instance393:
	.byte $14
	.word gem
	.word $00
	.word $18
	.word $2E8
	.byte $00
Instance391:
	.byte $15
	.word enemy_standing
	.word $00
	.word $68
	.word $2F0
	.byte $03
	.byte $81, $01, $40
Instance392:
	.byte $16
	.word switch
	.word Instance395
	.word $18
	.word $300
	.byte $00
Instance403:
	.byte $17
	.word gem
	.word $00
	.word $D0
	.word $2C0
	.byte $00
Instance408:
	.byte $18
	.word gem
	.word $00
	.word $68
	.word $2D0
	.byte $00

_Lev1Scr4:
_Lev1Scr4EntsArr:
	.byte 8
	.word Instance377
	.word Instance379
	.word Instance376
	.word Instance378
	.word Instance380
	.word Instance382
	.word Instance383
	.word Instance381
Instance377:
	.byte $19
	.word platform_32x10_horiz112
	.word $00
	.word $10
	.word $430
	.byte $03
	.byte $F0, $00, $A0
Instance379:
	.byte $1A
	.word platform_32x10_horiz112
	.word $00
	.word $10
	.word $3E0
	.byte $03
	.byte $F0, $00, $A0
Instance376:
	.byte $1B
	.word platform_32x10_horiz112
	.word $00
	.word $60
	.word $458
	.byte $03
	.byte $70, $70, $A0
Instance378:
	.byte $1C
	.word platform_32x10_horiz112
	.word $00
	.word $60
	.word $408
	.byte $03
	.byte $70, $70, $A0
Instance380:
	.byte $1D
	.word gem
	.word $00
	.word $C8
	.word $428
	.byte $00
Instance382:
	.byte $1E
	.word gem
	.word $00
	.word $C8
	.word $3D8
	.byte $00
Instance383:
	.byte $1F
	.word gem
	.word $00
	.word $28
	.word $450
	.byte $00
Instance381:
	.byte $20
	.word gem
	.word $00
	.word $28
	.word $400
	.byte $00

_Lev1Scr5:
_Lev1Scr5EntsArr:
	.byte 6
	.word Instance363
	.word Instance364
	.word Instance372
	.word Instance373
	.word Instance374
	.word Instance375
Instance363:
	.byte $21
	.word gem
	.word $00
	.word $98
	.word $518
	.byte $00
Instance364:
	.byte $22
	.word gem
	.word $00
	.word $20
	.word $4E0
	.byte $00
Instance372:
	.byte $23
	.word gem
	.word $00
	.word $C8
	.word $470
	.byte $00
Instance373:
	.byte $24
	.word checkpoint
	.word $00
	.word $30
	.word $4A0
	.byte $00
Instance374:
	.byte $25
	.word gem
	.word $00
	.word $50
	.word $4B0
	.byte $00
Instance375:
	.byte $26
	.word platform_32x10_horiz112
	.word $00
	.word $10
	.word $480
	.byte $03
	.byte $F0, $00, $A0

_Lev1Scr6:
_Lev1Scr6EntsArr:
	.byte 4
	.word Instance360
	.word Instance359
	.word Instance365
	.word Instance371
Instance360:
	.byte $27
	.word platform_32x10_vert64
	.word $00
	.word $20
	.word $540
	.byte $03
	.byte $C0, $00, $60
Instance359:
	.byte $28
	.word enemy_walking112
	.word $00
	.word $58
	.word $560
	.byte $02
	.byte $F0, $00
Instance365:
	.byte $29
	.word gem
	.word $00
	.word $E0
	.word $570
	.byte $00
Instance371:
	.byte $2A
	.word gem
	.word $00
	.word $98
	.word $5D0
	.byte $00

_Lev1Scr7:
_Lev1Scr7EntsArr:
	.byte 7
	.word Instance358
	.word Instance361
	.word Instance369
	.word Instance370
	.word Instance357
	.word Instance356
	.word Instance409
Instance358:
	.byte $2B
	.word switch
	.word Instance360
	.word $D8
	.word $620
	.byte $00
Instance361:
	.byte $2C
	.word enemy_flying96
	.word $00
	.word $68
	.word $650
	.byte $02
	.byte $E0, $00
Instance369:
	.byte $2D
	.word gem
	.word $00
	.word $60
	.word $690
	.byte $00
Instance370:
	.byte $2E
	.word gem
	.word $00
	.word $88
	.word $638
	.byte $00
Instance357:
	.byte $2F
	.word platform_32x10_vert64
	.word $00
	.word $28
	.word $670
	.byte $03
	.byte $40, $40, $E0
Instance356:
	.byte $30
	.word platform_32x10_vert64
	.word $00
	.word $80
	.word $680
	.byte $03
	.byte $C0, $00, $E0
Instance409:
	.byte $31
	.word gem
	.word $00
	.word $D8
	.word $690
	.byte $00

_Lev1Scr8:
_Lev1Scr8EntsArr:
	.byte 5
	.word Instance355
	.word Instance367
	.word Instance368
	.word Instance347
	.word Instance407
Instance355:
	.byte $32
	.word enemy_flying96
	.word $00
	.word $60
	.word $728
	.byte $02
	.byte $E0, $00
Instance367:
	.byte $33
	.word gem
	.word $00
	.word $C8
	.word $7D0
	.byte $00
Instance368:
	.byte $34
	.word gem
	.word $00
	.word $80
	.word $720
	.byte $00
Instance347:
	.byte $35
	.word platform_32x10_horiz112
	.word $00
	.word $30
	.word $7A0
	.byte $03
	.byte $F0, $00, $A0
Instance407:
	.byte $36
	.word gem
	.word $00
	.word $30
	.word $700
	.byte $00

_Lev1Scr9:
_Lev1Scr9EntsArr:
	.byte 5
	.word Instance348
	.word Instance351
	.word Instance352
	.word Instance353
	.word Instance366
Instance348:
	.byte $37
	.word player_entity
	.word $00
	.word $20
	.word $850
	.byte $00
Instance351:
	.byte $38
	.word logs_32x16
	.word $00
	.word $40
	.word $870
	.byte $01
	.byte $20
Instance352:
	.byte $39
	.word logs_32x16
	.word $00
	.word $60
	.word $870
	.byte $01
	.byte $20
Instance353:
	.byte $3A
	.word logs_32x16
	.word $00
	.word $A0
	.word $870
	.byte $01
	.byte $20
Instance366:
	.byte $3B
	.word gem
	.word $00
	.word $88
	.word $820
	.byte $00

_Lev1_EntInstCnt = 60	; number of entities instances

; *** BASE ENTITIES ***

BaseEntities:
	.word 21		; number of base entities
	.word player_entity
	.word enemy_walking96
	.word enemy_standing
	.word enemy_flying96
	.word enemy_walking112
	.word gem
	.word switch
	.word button
	.word portal_in_green
	.word portal_out_red
	.word checkpoint
	.word level_passed
	.word platform_32x10_horiz112
	.word platform_32x10_vert80
	.word logs_32x16
	.word platform_32x10_vert64
	.word platform_32x10_horiz32
	.word door_opened
	.word door_closed
	.word heavy_load_lifted
	.word heavy_load_lowered

player_entity:
	.byte $00	; uid
	.byte $10	; width
	.byte $20	; height
	.byte $00	; pivot x
	.byte $00	; pivot y
	.byte $00	; properties count

enemy_walking96:
	.byte $02
	.byte $70
	.byte $20
	.byte $00
	.byte $00
	.byte $00

enemy_standing:
	.byte $02
	.byte $10
	.byte $20
	.byte $00
	.byte $00
	.byte $00

enemy_flying96:
	.byte $03
	.byte $70
	.byte $10
	.byte $00
	.byte $00
	.byte $00

enemy_walking112:
	.byte $02
	.byte $80
	.byte $20
	.byte $00
	.byte $00
	.byte $00

gem:
	.byte $01
	.byte $10
	.byte $10
	.byte $00
	.byte $00
	.byte $00

switch:
	.byte $04
	.byte $10
	.byte $10
	.byte $00
	.byte $00
	.byte $00

button:
	.byte $05
	.byte $10
	.byte $10
	.byte $00
	.byte $00
	.byte $00

portal_in_green:
	.byte $0A
	.byte $10
	.byte $20
	.byte $00
	.byte $00
	.byte $00

portal_out_red:
	.byte $0A
	.byte $10
	.byte $20
	.byte $00
	.byte $00
	.byte $00

checkpoint:
	.byte $0B
	.byte $10
	.byte $20
	.byte $00
	.byte $00
	.byte $00

level_passed:
	.byte $0C
	.byte $10
	.byte $20
	.byte $00
	.byte $00
	.byte $00

platform_32x10_horiz112:
	.byte $06
	.byte $90
	.byte $0A
	.byte $00
	.byte $00
	.byte $00

platform_32x10_vert80:
	.byte $06
	.byte $20
	.byte $5A
	.byte $00
	.byte $00
	.byte $00

logs_32x16:
	.byte $07
	.byte $20
	.byte $10
	.byte $00
	.byte $00
	.byte $00

platform_32x10_vert64:
	.byte $06
	.byte $20
	.byte $4A
	.byte $00
	.byte $00
	.byte $00

platform_32x10_horiz32:
	.byte $06
	.byte $20
	.byte $0A
	.byte $00
	.byte $00
	.byte $00

door_opened:
	.byte $08
	.byte $10
	.byte $40
	.byte $00
	.byte $00
	.byte $00

door_closed:
	.byte $08
	.byte $10
	.byte $40
	.byte $00
	.byte $00
	.byte $00

heavy_load_lifted:
	.byte $09
	.byte $20
	.byte $60
	.byte $00
	.byte $00
	.byte $00

heavy_load_lowered:
	.byte $09
	.byte $20
	.byte $60
	.byte $00
	.byte $00
	.byte $00


; *** GLOBAL DATA ***

_chr0:	.incbin "_maps__chr0.bin"		; (7616)


_mpd_CHRs_size:
	.word 7616	; (_chr0)

_mpd_CHRs:
	.word _chr0
	.byte bank(_chr0)

_mpd_Tiles:	.incbin "_maps_Tiles.bin"	; (1024) (4x4) 4 block indices per tile ( left to right, up to down ) of all exported data banks

_mpd_TilesOffs:
	.word 0	; (chr0)
	.word 1024	; data end

_mpd_Attrs:	.incbin "_maps_Attrs.bin"	; (640) attributes array per block ( 2 bytes per attribute; 8 bytes per block ) of all exported data banks

_mpd_BlocksOffs:
	.word 0	; (chr0)
	.word 640	; data end

_mpd_Props:	.incbin "_maps_Props.bin"	; (80) blocks properties array ( 1 byte per block ) of all exported data banks

_mpd_PropsOffs:
	.word 0	; (chr0)
	.word 80	; data end

_mpd_Map1:	.incbin "_maps_Map1.bin"	; compressed (472 / 560) tilemap tiles (4x4)
_mpd_Map0:	.incbin "_maps_Map0.bin"	; compressed (2115 / 2240) tilemap tiles (4x4)

_mpd_MapsArr:
	.word _mpd_Map0
	.byte bank(_mpd_Map0)
	.word _mpd_Map1
	.byte bank(_mpd_Map1)

_mpd_MapsTbl:	.incbin "_maps_MapsTbl.bin"	; (176) lookup table for fast calculation of tile addresses; columns by X coordinate ( 16 bit offset per column of tiles ) of all exported data banks

_mpd_MapsTblOffs:
	.word 0
	.word 160
	.word 176	; data end

_mpd_Plts:	.incbin "_maps_Plts.bin"	; (512) palettes array of all exported data banks ( data offset = chr_id * 512 )

_mpd_MapsCHRBanks:
	.byte 0
	.byte 0

_mpd_StartScrArr:
	.byte _Lev0_StartScr
	.byte _Lev1_StartScr

_mpd_LayoutsDimArr:
	.byte _Lev0_WScrCnt, _Lev0_HScrCnt
	.byte _Lev1_WScrCnt, _Lev1_HScrCnt

_mpd_LayoutsArr:
	.word _Lev0_Layout
	.byte bank(_Lev0_Layout)
	.word _Lev1_Layout
	.byte bank(_Lev1_Layout)

_mpd_BaseEntities:
	.word BaseEntities
	.byte bank(BaseEntities)
