;#######################################################
;
; Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################

_sprites_chr0:	.incbin "_sprites_chr0.bin"	; 4608 bytes

_sprites_SG_arr:	
	.word 4608, _sprites_chr0, bank(_sprites_chr0)


_sprites_palette:
_sprites_palette_slot0:
	.word $16D, $1FF, $1F8, $100, $11C, $83, $139, $1A7, $189, $92, $DB, $51, $A1, $131, $38, $147
_sprites_palette_slot1:
	.word $16D, $28, $78, $13C, $1F8, $1FF, $00, $187, $147, $107, $138, $F8, $B8, $180, $180, $180
_sprites_palette_slot2:
	.word $16D, $04, $85, $107, $54, $94, $D4, $114, $A8, $E8, $128, $168, $FC, $13C, $17C, $1BC
_sprites_palette_end:

_sprites_num_frames:
	.byte $15
_sprites_frames_data:
_heavy_load_32x64_frame:
	.word _heavy_load_32x64
	.byte bank(_heavy_load_32x64)
_player_16x32_0_frame:
	.word _player_16x32_0
	.byte bank(_player_16x32_0)
_checkpoint_16x32_1_frame:
	.word _checkpoint_16x32_1
	.byte bank(_checkpoint_16x32_1)
_enemy_walking_16x32_0_RIGHT_frame:
	.word _enemy_walking_16x32_0_RIGHT
	.byte bank(_enemy_walking_16x32_0_RIGHT)
_enemy_walking_16x32_1_LEFT_frame:
	.word _enemy_walking_16x32_1_LEFT
	.byte bank(_enemy_walking_16x32_1_LEFT)
_door_16x32_0_frame:
	.word _door_16x32_0
	.byte bank(_door_16x32_0)
_portal_16x32_1_frame:
	.word _portal_16x32_1
	.byte bank(_portal_16x32_1)
_logs_32x16_frame:
	.word _logs_32x16
	.byte bank(_logs_32x16)
_platform_32x10_frame:
	.word _platform_32x10
	.byte bank(_platform_32x10)
_enemy_flying_16x16_RIGHT_frame:
	.word _enemy_flying_16x16_RIGHT
	.byte bank(_enemy_flying_16x16_RIGHT)
_enemy_flying_16x16_LEFT_frame:
	.word _enemy_flying_16x16_LEFT
	.byte bank(_enemy_flying_16x16_LEFT)
_player_16x16_frame:
	.word _player_16x16
	.byte bank(_player_16x16)
_collectable_diamond_frame:
	.word _collectable_diamond
	.byte bank(_collectable_diamond)
_switch_off_frame:
	.word _switch_off
	.byte bank(_switch_off)
_switch_on_frame:
	.word _switch_on
	.byte bank(_switch_on)
_button_off_frame:
	.word _button_off
	.byte bank(_button_off)
_button_on_frame:
	.word _button_on
	.byte bank(_button_on)
_HUD_lives_heart_frame:
	.word _HUD_lives_heart
	.byte bank(_HUD_lives_heart)
_HUD_diamond_frame:
	.word _HUD_diamond
	.byte bank(_HUD_diamond)
_HUD_diamonds_cnt_frame:
	.word _HUD_diamonds_cnt
	.byte bank(_HUD_diamonds_cnt)
_pause_32x16_frame:
	.word _pause_32x16
	.byte bank(_pause_32x16)


	; #1: Y pos, #2: X pos, #3: CHR index, #4: CHR desc

_heavy_load_32x64:
	.word _heavy_load_32x64_end - _heavy_load_32x64 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $100, $3180
_heavy_load_32x64_end:

_player_16x32_0:
	.word _player_16x32_0_end - _player_16x32_0 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $110, $1082
_player_16x32_0_end:

_checkpoint_16x32_1:
	.word _checkpoint_16x32_1_end - _checkpoint_16x32_1 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $112, $1081
_checkpoint_16x32_1_end:

_enemy_walking_16x32_0_RIGHT:
	.word _enemy_walking_16x32_0_RIGHT_end - _enemy_walking_16x32_0_RIGHT - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $118, $1080
_enemy_walking_16x32_0_RIGHT_end:

_enemy_walking_16x32_1_LEFT:
	.word _enemy_walking_16x32_1_LEFT_end - _enemy_walking_16x32_1_LEFT - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $11A, $1080
_enemy_walking_16x32_1_LEFT_end:

_door_16x32_0:
	.word _door_16x32_0_end - _door_16x32_0 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $120, $1080
_door_16x32_0_end:

_portal_16x32_1:
	.word _portal_16x32_1_end - _portal_16x32_1 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $122, $1080
_portal_16x32_1_end:

_logs_32x16:
	.word _logs_32x16_end - _logs_32x16 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $128, $180
_logs_32x16_end:

_platform_32x10:
	.word _platform_32x10_end - _platform_32x10 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $12C, $180
_platform_32x10_end:

_enemy_flying_16x16_RIGHT:
	.word _enemy_flying_16x16_RIGHT_end - _enemy_flying_16x16_RIGHT - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $130, $80
_enemy_flying_16x16_RIGHT_end:

_enemy_flying_16x16_LEFT:
	.word _enemy_flying_16x16_LEFT_end - _enemy_flying_16x16_LEFT - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $130, $880
_enemy_flying_16x16_LEFT_end:

_player_16x16:
	.word _player_16x16_end - _player_16x16 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $132, $82
_player_16x16_end:

_collectable_diamond:
	.word _collectable_diamond_end - _collectable_diamond - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $134, $81
_collectable_diamond_end:

_switch_off:
	.word _switch_off_end - _switch_off - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $136, $80
_switch_off_end:

_switch_on:
	.word _switch_on_end - _switch_on - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $138, $80
_switch_on_end:

_button_off:
	.word _button_off_end - _button_off - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $13A, $80
_button_off_end:

_button_on:
	.word _button_on_end - _button_on - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $13C, $80
_button_on_end:

_HUD_lives_heart:
	.word _HUD_lives_heart_end - _HUD_lives_heart - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $13E, $82
_HUD_lives_heart_end:

_HUD_diamond:
	.word _HUD_diamond_end - _HUD_diamond - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $140, $81
_HUD_diamond_end:

_HUD_diamonds_cnt:
	.word _HUD_diamonds_cnt_end - _HUD_diamonds_cnt - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $142, $80
_HUD_diamonds_cnt_end:

_pause_32x16:
	.word _pause_32x16_end - _pause_32x16 - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $00, $00, $144, $181
_pause_32x16_end:

