;#######################################################
;
; Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################

SPRITES_TEST_SPR_VADDR	= 8192
SPRITES_TEST_PALETTE_SLOT	= 0


;chr0:	.incbin "sprites_test_chr0.bin"	; 8192 bytes
sprites_test_CHR_arr:	
	.word 8192, chr0


sprites_test_palette:
	.word $147, $02, $C6, $06, $173, $133, $F3, $1B6, $00, $00, $00, $00, $00, $00, $00, $00
	.word $147, $136, $CB, $15C, $11B, $1B0, $170, $E9, $173, $F0, $58, $68, $61, $F3, $1B6, $00
	.word $147, $1B0, $170, $E9, $F0, $58, $68, $00, $00, $00, $00, $00, $00, $00, $00, $00
	.word $147, $8B, $D4, $82, $41, $16A, $91, $DA, $10, $1B6, $124, $DB, $92, $49, $00, $72
	.word $147, $12B, $E8, $A0, $E9, $A8, $58, $28, $20, $10, $124, $00, $4A, $93, $124, $1BC
	.word $147, $1F8, $178, $F8, $78, $1FF, $68, $00, $00, $00, $00, $00, $00, $00, $00, $00
sprites_test_palette_end:

sprites_test_num_frames:
	.byte $0A
sprites_test_frames_data:
jackie_chan_idle_RIGHT_32x64_frame:
	.word jackie_chan_idle_RIGHT_32x64
	.word jackie_chan_idle_RIGHT_32x64_end - jackie_chan_idle_RIGHT_32x64	; data size
	.byte 0		; CHR bank index (chr0)
dryad_missile_UP_16x64_0_frame:
	.word dryad_missile_UP_16x64_0
	.word dryad_missile_UP_16x64_0_end - dryad_missile_UP_16x64_0
	.byte 0
dryad_missile_UP_16x64_1_ref_frame:
	.word dryad_missile_UP_16x64_1_ref
	.word dryad_missile_UP_16x64_1_ref_end - dryad_missile_UP_16x64_1_ref
	.byte 0
jackie_chan_mini_16x32_0_frame:
	.word jackie_chan_mini_16x32_0
	.word jackie_chan_mini_16x32_0_end - jackie_chan_mini_16x32_0
	.byte 0
jackie_chan_mini_16x32_1_ref_frame:
	.word jackie_chan_mini_16x32_1_ref
	.word jackie_chan_mini_16x32_1_ref_end - jackie_chan_mini_16x32_1_ref
	.byte 0
ripple_fly_RIGHT_32x32_frame:
	.word ripple_fly_RIGHT_32x32
	.word ripple_fly_RIGHT_32x32_end - ripple_fly_RIGHT_32x32
	.byte 0
broomstick_RIGHT_32x16_frame:
	.word broomstick_RIGHT_32x16
	.word broomstick_RIGHT_32x16_end - broomstick_RIGHT_32x16
	.byte 0
dryad_missile_UP_frame:
	.word dryad_missile_UP
	.word dryad_missile_UP_end - dryad_missile_UP
	.byte 0
gigan_idle_LEFT_frame:
	.word gigan_idle_LEFT
	.word gigan_idle_LEFT_end - gigan_idle_LEFT
	.byte 0
tony_idle_RIGHT_frame:
	.word tony_idle_RIGHT
	.word tony_idle_RIGHT_end - tony_idle_RIGHT
	.byte 0


	; #1: Y pos, #2: X pos, #3: CHR index, #4: CHR desc

jackie_chan_idle_RIGHT_32x64:
	.word $FFC0, $FFF0, $100, $3100
jackie_chan_idle_RIGHT_32x64_end:

dryad_missile_UP_16x64_0:
	.word $00, $FFF8, $110, $3005
dryad_missile_UP_16x64_0_end:

dryad_missile_UP_16x64_1_ref:
	.word $00, $FFF8, $112, $3005
dryad_missile_UP_16x64_1_ref_end:

jackie_chan_mini_16x32_0:
	.word $FFE0, $FFF8, $120, $1000
jackie_chan_mini_16x32_0_end:

jackie_chan_mini_16x32_1_ref:
	.word $FFE0, $FFF8, $122, $1000
jackie_chan_mini_16x32_1_ref_end:

ripple_fly_RIGHT_32x32:
	.word $FFF0, $FFF0, $128, $1101
ripple_fly_RIGHT_32x32_end:

broomstick_RIGHT_32x16:
	.word $FFF8, $FFF0, $130, $102
broomstick_RIGHT_32x16_end:

dryad_missile_UP:
	.word $00, $FFF8, $134, $05
	.word $10, $FFF8, $136, $05
dryad_missile_UP_end:

gigan_idle_LEFT:
	.word $FFA0, $FFF6, $138, $03
	.word $FFB0, $FFF2, $13A, $03
	.word $FFB0, $02, $13C, $03
	.word $FFB0, $12, $13E, $03
	.word $FFC0, $FFE4, $140, $03
	.word $FFC0, $FFF4, $142, $03
	.word $FFC0, $04, $144, $03
	.word $FFC0, $14, $146, $03
	.word $FFD0, $FFE4, $148, $03
	.word $FFD0, $FFF4, $14A, $03
	.word $FFD0, $04, $14C, $03
	.word $FFD0, $14, $14E, $03
	.word $FFD0, $26, $150, $03
	.word $FFD0, $36, $152, $03
	.word $FFE0, $FFF6, $154, $03
	.word $FFE0, $06, $156, $03
	.word $FFE0, $16, $158, $03
	.word $FFE0, $26, $15A, $03
	.word $FFE0, $36, $15C, $03
	.word $FFF0, $FFF0, $15E, $03
	.word $FFF0, $02, $160, $03
	.word $FFF0, $12, $162, $03
gigan_idle_LEFT_end:

tony_idle_RIGHT:
	.word $FFA0, $FFF4, $164, $804
	.word $FFB0, $05, $166, $804
	.word $FFB0, $FFF5, $168, $804
	.word $FFB0, $FFE5, $16A, $804
	.word $FFC0, $05, $16C, $804
	.word $FFC0, $FFF5, $16E, $804
	.word $FFC0, $FFE5, $170, $804
	.word $FFD0, $FFFD, $172, $804
	.word $FFD0, $FFED, $174, $804
	.word $FFE0, $FFFF, $176, $804
	.word $FFE0, $FFEC, $178, $804
	.word $FFF0, $02, $17A, $804
	.word $FFF0, $FFF2, $17C, $804
	.word $FFF0, $FFE2, $17E, $804
tony_idle_RIGHT_end:

