;############################################################
;
; Generated by MAPeD-PCE (x64) Copyright 2017-2023 0x8BitDev
;
;############################################################

; *** LAYOUTS DATA ***

; *** Lev0 ***

_Lev0_TilesCnt	= 246	; map tiles count
_Lev0_StartScr	= 3	; start screen
_Lev0_WScrCnt	= 4	; number of screens in width
_Lev0_HScrCnt	= 5	; number of screens in height

_Lev0_Layout:	
	.word _Lev0Scr0
	.word _Lev0Scr1
	.word _Lev0Scr2
	.word _Lev0Scr3
	.word _Lev0Scr4
	.word _Lev0Scr5
	.word _Lev0Scr6
	.word _Lev0Scr7
	.word _Lev0Scr8
	.word _Lev0Scr9
	.word _Lev0Scr10
	.word _Lev0Scr11
	.word _Lev0Scr12
	.word _Lev0Scr13
	.word _Lev0Scr14
	.word _Lev0Scr15
	.word _Lev0Scr16
	.word _Lev0Scr17
	.word _Lev0Scr18
	.word _Lev0Scr19

_Lev0Scr0:

_Lev0Scr1:

_Lev0Scr2:

_Lev0Scr3:

_Lev0Scr4:

_Lev0Scr5:

_Lev0Scr6:

_Lev0Scr7:

_Lev0Scr8:

_Lev0Scr9:

_Lev0Scr10:

_Lev0Scr11:

_Lev0Scr12:

_Lev0Scr13:

_Lev0Scr14:

_Lev0Scr15:

_Lev0Scr16:

_Lev0Scr17:

_Lev0Scr18:

_Lev0Scr19:

; *** Lev1 ***

_Lev1_TilesCnt	= 174	; map tiles count
_Lev1_StartScr	= 36	; start screen
_Lev1_WScrCnt	= 6	; number of screens in width
_Lev1_HScrCnt	= 7	; number of screens in height

_Lev1_Layout:	
	.word _Lev1Scr0
	.word _Lev1Scr1
	.word _Lev1Scr2
	.word _Lev1Scr3
	.word _Lev1Scr4
	.word _Lev1Scr5
	.word _Lev1Scr6
	.word _Lev1Scr7
	.word _Lev1Scr8
	.word _Lev1Scr9
	.word _Lev1Scr10
	.word _Lev1Scr11
	.word _Lev1Scr12
	.word _Lev1Scr13
	.word _Lev1Scr14
	.word _Lev1Scr15
	.word _Lev1Scr16
	.word _Lev1Scr17
	.word _Lev1Scr18
	.word _Lev1Scr19
	.word _Lev1Scr20
	.word _Lev1Scr21
	.word _Lev1Scr22
	.word _Lev1Scr23
	.word _Lev1Scr24
	.word _Lev1Scr25
	.word _Lev1Scr26
	.word _Lev1Scr27
	.word _Lev1Scr28
	.word _Lev1Scr29
	.word _Lev1Scr30
	.word _Lev1Scr31
	.word _Lev1Scr32
	.word _Lev1Scr33
	.word _Lev1Scr34
	.word _Lev1Scr35
	.word _Lev1Scr36
	.word _Lev1Scr37
	.word _Lev1Scr38
	.word _Lev1Scr39
	.word _Lev1Scr40
	.word _Lev1Scr41

_Lev1Scr0:

_Lev1Scr1:

_Lev1Scr2:

_Lev1Scr3:

_Lev1Scr4:

_Lev1Scr5:

_Lev1Scr6:

_Lev1Scr7:

_Lev1Scr8:

_Lev1Scr9:

_Lev1Scr10:

_Lev1Scr11:

_Lev1Scr12:

_Lev1Scr13:

_Lev1Scr14:

_Lev1Scr15:

_Lev1Scr16:

_Lev1Scr17:

_Lev1Scr18:

_Lev1Scr19:

_Lev1Scr20:

_Lev1Scr21:

_Lev1Scr22:

_Lev1Scr23:

_Lev1Scr24:

_Lev1Scr25:

_Lev1Scr26:

_Lev1Scr27:

_Lev1Scr28:

_Lev1Scr29:

_Lev1Scr30:

_Lev1Scr31:

_Lev1Scr32:

_Lev1Scr33:

_Lev1Scr34:

_Lev1Scr35:

_Lev1Scr36:

_Lev1Scr37:

_Lev1Scr38:

_Lev1Scr39:

_Lev1Scr40:

_Lev1Scr41:


; *** GLOBAL DATA ***

_chr0:	.incbin "_tilemap__chr0.bin"		; (17376)
_chr1:	.incbin "_tilemap__chr1.bin"		; (13248)


_mpd_CHRs_size:
	.word 17376	; (_chr0)
	.word 13248	; (_chr1)

_mpd_CHRs:
	.word _chr0
	.byte bank(_chr0)
	.word _chr1
	.byte bank(_chr1)

_mpd_Attrs:	.incbin "_tilemap_Attrs.bin"	; (3360) attributes array per block ( 2 bytes per attribute; 8 bytes per block ) of all exported data banks

_mpd_BlocksOffs:
	.word 0	; (chr0)
	.word 1968	; (chr1)
	.word 3360	; data end

_mpd_Props:	.incbin "_tilemap_Props.bin"	; (1680) blocks properties array ( 4 bytes per block ) of all exported data banks

_mpd_PropsOffs:
	.word 0	; (chr0)
	.word 984	; (chr1)
	.word 1680	; data end

_mpd_Maps:	.incbin "_tilemap_Maps.bin"	; (13888) game levels blocks (2x2) array of all exported data banks

_mpd_MapsOffs:
	.word 0
	.word 4480
	.word 13888	; data end

_mpd_MapsTbl:	.incbin "_tilemap_MapsTbl.bin"	; (320) lookup table for fast calculation of tile addresses; columns by X coordinate ( 16 bit offset per column of tiles ) of all exported data banks

_mpd_MapsTblOffs:
	.word 0
	.word 128
	.word 320	; data end

_mpd_Plts:	.incbin "_tilemap_Plts.bin"	; (1024) palettes array of all exported data banks ( data offset = chr_id * 512 )

_mpd_MapsCHRBanks:
	.byte 0
	.byte 1

_mpd_StartScrArr:
	.byte _Lev0_StartScr
	.byte _Lev1_StartScr

_mpd_MapsDimArr:
	.byte _Lev0_WScrCnt, _Lev0_HScrCnt
	.byte _Lev1_WScrCnt, _Lev1_HScrCnt

_mpd_MapsArr:
	.word _Lev0_Layout
	.byte bank(_Lev0_Layout)
	.word _Lev1_Layout
	.byte bank(_Lev1_Layout)

