;#######################################################
;
; Generated by SPReD-SMS Copyright 2017-2022 0x8BitDev
;
;#######################################################

.define	DOG_GFX_SPR_MODE_8X16	1
.define	DOG_GFX_SPR_CHR_BPP	4
.define	DOG_GFX_SPR_CHRS_OFFSET	0	; first CHR index in a CHR bank


;dog_gfx_chr0:	.incbin "dog_gfx_chr0.bin"	; 384 bytes
;dog_gfx_chr1:	.incbin "dog_gfx_chr1.bin"	; 384 bytes
;dog_gfx_chr2:	.incbin "dog_gfx_chr2.bin"	; 384 bytes
;dog_gfx_chr3:	.incbin "dog_gfx_chr3.bin"	; 384 bytes
;dog_gfx_chr4:	.incbin "dog_gfx_chr4.bin"	; 384 bytes
;dog_gfx_chr5:	.incbin "dog_gfx_chr5.bin"	; 384 bytes
;dog_gfx_chr6:	.incbin "dog_gfx_chr6.bin"	; 384 bytes
;dog_gfx_chr7:	.incbin "dog_gfx_chr7.bin"	; 384 bytes

;dog_gfx_CHR_arr:	
;	.word 384, dog_gfx_chr0
;	.word 384, dog_gfx_chr1
;	.word 384, dog_gfx_chr2
;	.word 384, dog_gfx_chr3
;	.word 384, dog_gfx_chr4
;	.word 384, dog_gfx_chr5
;	.word 384, dog_gfx_chr6
;	.word 384, dog_gfx_chr7


dog_gfx_palette:
	.byte $39, $0B, $07, $00, $3E, $38, $34, $10, $22, $25, $29, $2D, $33, $36, $3A, $3E


dog_gfx_num_frames:
	.byte $08
dog_gfx_frames_data:
dog01_IDLE01_RIGHT_frame:
	.word dog01_IDLE01_RIGHT
dog01_IDLE02_RIGHT_frame:
	.word dog01_IDLE02_RIGHT
dog01_RUN01_RIGHT_frame:
	.word dog01_RUN01_RIGHT
dog01_JUMP_RIGHT_frame:
	.word dog01_JUMP_RIGHT
dog01_IDLE01_LEFT_frame:
	.word dog01_IDLE01_LEFT
dog01_IDLE02_LEFT_frame:
	.word dog01_IDLE02_LEFT
dog01_RUN01_LEFT_frame:
	.word dog01_RUN01_LEFT
dog01_JUMP_LEFT_frame:
	.word dog01_JUMP_LEFT


	; #1: Y pos, #2: X pos, #3: CHR index

dog01_IDLE01_RIGHT:
	.byte dog01_IDLE01_RIGHT_end - dog01_IDLE01_RIGHT - 2	; data size
	.byte 0		; GFX bank index (chr0)

	.byte $E1, $F4, $00
	.byte $E1, $FC, $02
	.byte $E1, $04, $04
	.byte $F1, $F4, $06
	.byte $F1, $04, $08
	.byte $F1, $FC, $0A
dog01_IDLE01_RIGHT_end:

dog01_IDLE02_RIGHT:
	.byte dog01_IDLE02_RIGHT_end - dog01_IDLE02_RIGHT - 2	; data size
	.byte 1		; GFX bank index (chr1)

	.byte $E0, $FC, $00
	.byte $E0, $04, $02
	.byte $F0, $F4, $04
	.byte $F0, $FC, $06
	.byte $F0, $04, $08
	.byte $E0, $F4, $0A
dog01_IDLE02_RIGHT_end:

dog01_RUN01_RIGHT:
	.byte dog01_RUN01_RIGHT_end - dog01_RUN01_RIGHT - 2	; data size
	.byte 2		; GFX bank index (chr2)

	.byte $E0, $FC, $00
	.byte $E0, $04, $02
	.byte $F0, $F4, $04
	.byte $F0, $FC, $06
	.byte $F0, $04, $08
	.byte $E0, $F4, $0A
dog01_RUN01_RIGHT_end:

dog01_JUMP_RIGHT:
	.byte dog01_JUMP_RIGHT_end - dog01_JUMP_RIGHT - 2	; data size
	.byte 3		; GFX bank index (chr3)

	.byte $DE, $FC, $00
	.byte $DE, $04, $02
	.byte $DE, $F4, $04
	.byte $EE, $F4, $06
	.byte $EE, $FC, $08
	.byte $EE, $04, $0A
dog01_JUMP_RIGHT_end:

dog01_IDLE01_LEFT:
	.byte dog01_IDLE01_LEFT_end - dog01_IDLE01_LEFT - 2	; data size
	.byte 4		; GFX bank index (chr4)

	.byte $E1, $04, $00
	.byte $E1, $FC, $02
	.byte $E1, $F4, $04
	.byte $F1, $04, $06
	.byte $F1, $F4, $08
	.byte $F1, $FC, $0A
dog01_IDLE01_LEFT_end:

dog01_IDLE02_LEFT:
	.byte dog01_IDLE02_LEFT_end - dog01_IDLE02_LEFT - 2	; data size
	.byte 5		; GFX bank index (chr5)

	.byte $E0, $FC, $00
	.byte $E0, $F4, $02
	.byte $F0, $04, $04
	.byte $F0, $FC, $06
	.byte $F0, $F4, $08
	.byte $E0, $04, $0A
dog01_IDLE02_LEFT_end:

dog01_RUN01_LEFT:
	.byte dog01_RUN01_LEFT_end - dog01_RUN01_LEFT - 2	; data size
	.byte 6		; GFX bank index (chr6)

	.byte $E0, $FC, $00
	.byte $E0, $F4, $02
	.byte $F0, $04, $04
	.byte $F0, $FC, $06
	.byte $F0, $F4, $08
	.byte $E0, $04, $0A
dog01_RUN01_LEFT_end:

dog01_JUMP_LEFT:
	.byte dog01_JUMP_LEFT_end - dog01_JUMP_LEFT - 2	; data size
	.byte 7		; GFX bank index (chr7)

	.byte $DE, $FC, $00
	.byte $DE, $F4, $02
	.byte $DE, $04, $04
	.byte $EE, $04, $06
	.byte $EE, $FC, $08
	.byte $EE, $F4, $0A
dog01_JUMP_LEFT_end:

