;#######################################################
;
; Generated by SPReD-SMS Copyright 2017-2022 0x8BitDev
;
;#######################################################

.define	MARCO_GFX_SPR_MODE_8X16	0
.define	MARCO_GFX_SPR_CHR_BPP	4
.define	MARCO_GFX_SPR_CHRS_OFFSET	0	; first CHR index in a CHR bank


;marco_gfx_chr0:	.incbin "marco_gfx_chr0.bin"	; 512 bytes
;marco_gfx_chr1:	.incbin "marco_gfx_chr1.bin"	; 512 bytes
;marco_gfx_chr2:	.incbin "marco_gfx_chr2.bin"	; 512 bytes
;marco_gfx_chr3:	.incbin "marco_gfx_chr3.bin"	; 576 bytes
;marco_gfx_chr4:	.incbin "marco_gfx_chr4.bin"	; 544 bytes
;marco_gfx_chr5:	.incbin "marco_gfx_chr5.bin"	; 384 bytes
;marco_gfx_chr6:	.incbin "marco_gfx_chr6.bin"	; 384 bytes
;marco_gfx_chr7:	.incbin "marco_gfx_chr7.bin"	; 384 bytes
;marco_gfx_chr8:	.incbin "marco_gfx_chr8.bin"	; 384 bytes
;marco_gfx_chr9:	.incbin "marco_gfx_chr9.bin"	; 544 bytes
;marco_gfx_chr10:	.incbin "marco_gfx_chr10.bin"	; 544 bytes
;marco_gfx_chr11:	.incbin "marco_gfx_chr11.bin"	; 576 bytes
;marco_gfx_chr12:	.incbin "marco_gfx_chr12.bin"	; 512 bytes
;marco_gfx_chr13:	.incbin "marco_gfx_chr13.bin"	; 576 bytes
;marco_gfx_chr14:	.incbin "marco_gfx_chr14.bin"	; 512 bytes
;marco_gfx_chr15:	.incbin "marco_gfx_chr15.bin"	; 672 bytes
;marco_gfx_chr16:	.incbin "marco_gfx_chr16.bin"	; 736 bytes
;marco_gfx_chr17:	.incbin "marco_gfx_chr17.bin"	; 576 bytes
;marco_gfx_chr18:	.incbin "marco_gfx_chr18.bin"	; 576 bytes
;marco_gfx_chr19:	.incbin "marco_gfx_chr19.bin"	; 512 bytes
;marco_gfx_chr20:	.incbin "marco_gfx_chr20.bin"	; 544 bytes
;marco_gfx_chr21:	.incbin "marco_gfx_chr21.bin"	; 544 bytes
;marco_gfx_chr22:	.incbin "marco_gfx_chr22.bin"	; 512 bytes
;marco_gfx_chr23:	.incbin "marco_gfx_chr23.bin"	; 512 bytes
;marco_gfx_chr24:	.incbin "marco_gfx_chr24.bin"	; 512 bytes
;marco_gfx_chr25:	.incbin "marco_gfx_chr25.bin"	; 512 bytes
;marco_gfx_chr26:	.incbin "marco_gfx_chr26.bin"	; 512 bytes
;marco_gfx_chr27:	.incbin "marco_gfx_chr27.bin"	; 512 bytes
;marco_gfx_chr28:	.incbin "marco_gfx_chr28.bin"	; 576 bytes
;marco_gfx_chr29:	.incbin "marco_gfx_chr29.bin"	; 544 bytes
;marco_gfx_chr30:	.incbin "marco_gfx_chr30.bin"	; 384 bytes
;marco_gfx_chr31:	.incbin "marco_gfx_chr31.bin"	; 384 bytes
;marco_gfx_chr32:	.incbin "marco_gfx_chr32.bin"	; 384 bytes
;marco_gfx_chr33:	.incbin "marco_gfx_chr33.bin"	; 384 bytes
;marco_gfx_chr34:	.incbin "marco_gfx_chr34.bin"	; 384 bytes
;marco_gfx_chr35:	.incbin "marco_gfx_chr35.bin"	; 384 bytes
;marco_gfx_chr36:	.incbin "marco_gfx_chr36.bin"	; 384 bytes
;marco_gfx_chr37:	.incbin "marco_gfx_chr37.bin"	; 384 bytes
;marco_gfx_chr38:	.incbin "marco_gfx_chr38.bin"	; 512 bytes
;marco_gfx_chr39:	.incbin "marco_gfx_chr39.bin"	; 544 bytes
;marco_gfx_chr40:	.incbin "marco_gfx_chr40.bin"	; 544 bytes
;marco_gfx_chr41:	.incbin "marco_gfx_chr41.bin"	; 576 bytes
;marco_gfx_chr42:	.incbin "marco_gfx_chr42.bin"	; 544 bytes
;marco_gfx_chr43:	.incbin "marco_gfx_chr43.bin"	; 512 bytes
;marco_gfx_chr44:	.incbin "marco_gfx_chr44.bin"	; 544 bytes
;marco_gfx_chr45:	.incbin "marco_gfx_chr45.bin"	; 576 bytes
;marco_gfx_chr46:	.incbin "marco_gfx_chr46.bin"	; 512 bytes
;marco_gfx_chr47:	.incbin "marco_gfx_chr47.bin"	; 672 bytes
;marco_gfx_chr48:	.incbin "marco_gfx_chr48.bin"	; 736 bytes
;marco_gfx_chr49:	.incbin "marco_gfx_chr49.bin"	; 576 bytes
;marco_gfx_chr50:	.incbin "marco_gfx_chr50.bin"	; 576 bytes

;marco_gfx_CHR_arr:	
;	.word 512, marco_gfx_chr0
;	.word 512, marco_gfx_chr1
;	.word 512, marco_gfx_chr2
;	.word 576, marco_gfx_chr3
;	.word 544, marco_gfx_chr4
;	.word 384, marco_gfx_chr5
;	.word 384, marco_gfx_chr6
;	.word 384, marco_gfx_chr7
;	.word 384, marco_gfx_chr8
;	.word 544, marco_gfx_chr9
;	.word 544, marco_gfx_chr10
;	.word 576, marco_gfx_chr11
;	.word 512, marco_gfx_chr12
;	.word 576, marco_gfx_chr13
;	.word 512, marco_gfx_chr14
;	.word 672, marco_gfx_chr15
;	.word 736, marco_gfx_chr16
;	.word 576, marco_gfx_chr17
;	.word 576, marco_gfx_chr18
;	.word 512, marco_gfx_chr19
;	.word 544, marco_gfx_chr20
;	.word 544, marco_gfx_chr21
;	.word 512, marco_gfx_chr22
;	.word 512, marco_gfx_chr23
;	.word 512, marco_gfx_chr24
;	.word 512, marco_gfx_chr25
;	.word 512, marco_gfx_chr26
;	.word 512, marco_gfx_chr27
;	.word 576, marco_gfx_chr28
;	.word 544, marco_gfx_chr29
;	.word 384, marco_gfx_chr30
;	.word 384, marco_gfx_chr31
;	.word 384, marco_gfx_chr32
;	.word 384, marco_gfx_chr33
;	.word 384, marco_gfx_chr34
;	.word 384, marco_gfx_chr35
;	.word 384, marco_gfx_chr36
;	.word 384, marco_gfx_chr37
;	.word 512, marco_gfx_chr38
;	.word 544, marco_gfx_chr39
;	.word 544, marco_gfx_chr40
;	.word 576, marco_gfx_chr41
;	.word 544, marco_gfx_chr42
;	.word 512, marco_gfx_chr43
;	.word 544, marco_gfx_chr44
;	.word 576, marco_gfx_chr45
;	.word 512, marco_gfx_chr46
;	.word 672, marco_gfx_chr47
;	.word 736, marco_gfx_chr48
;	.word 576, marco_gfx_chr49
;	.word 576, marco_gfx_chr50


marco_gfx_palette:
	.byte $39, $00, $3F, $1A, $1F, $15, $2F, $00, $0B, $1B, $06, $01, $06, $01, $3A, $3E


marco_gfx_num_frames:
	.byte $3A
marco_gfx_frames_data:
marco_idle01_RIGHT_frame:
	.word marco_idle01_RIGHT
marco_idle02_RIGHT_frame:
	.word marco_idle02_RIGHT
marco_idle03_RIGHT_frame:
	.word marco_idle03_RIGHT
marco_idle04_RIGHT_frame:
	.word marco_idle04_RIGHT
marco_idle05_RIGHT_frame:
	.word marco_idle05_RIGHT
marco_idle06_RIGHT_frame:
	.word marco_idle06_RIGHT
marco_duck01_RIGHT_frame:
	.word marco_duck01_RIGHT
marco_duck02_RIGHT_frame:
	.word marco_duck02_RIGHT
marco_duck03_RIGHT_frame:
	.word marco_duck03_RIGHT
marco_duck04_RIGHT_frame:
	.word marco_duck04_RIGHT
marco_duck05_RIGHT_frame:
	.word marco_duck05_RIGHT
marco_duck06_RIGHT_frame:
	.word marco_duck06_RIGHT
marco_duck07_RIGHT_frame:
	.word marco_duck07_RIGHT
marco_duck08_RIGHT_frame:
	.word marco_duck08_RIGHT
marco_duck09_RIGHT_frame:
	.word marco_duck09_RIGHT
marco_duck10_RIGHT_frame:
	.word marco_duck10_RIGHT
marco_run01_RIGHT_frame:
	.word marco_run01_RIGHT
marco_run02_RIGHT_frame:
	.word marco_run02_RIGHT
marco_run03_RIGHT_frame:
	.word marco_run03_RIGHT
marco_run04_RIGHT_frame:
	.word marco_run04_RIGHT
marco_run05_RIGHT_frame:
	.word marco_run05_RIGHT
marco_run06_RIGHT_frame:
	.word marco_run06_RIGHT
marco_run07_RIGHT_frame:
	.word marco_run07_RIGHT
marco_run08_RIGHT_frame:
	.word marco_run08_RIGHT
marco_run09_RIGHT_frame:
	.word marco_run09_RIGHT
marco_shoot01_RIGHT_frame:
	.word marco_shoot01_RIGHT
marco_shoot02_RIGHT_frame:
	.word marco_shoot02_RIGHT
marco_shoot03_RIGHT_frame:
	.word marco_shoot03_RIGHT
marco_shoot04_RIGHT_frame:
	.word marco_shoot04_RIGHT
marco_idle01_LEFT_frame:
	.word marco_idle01_LEFT
marco_idle02_LEFT_frame:
	.word marco_idle02_LEFT
marco_idle03_LEFT_frame:
	.word marco_idle03_LEFT
marco_idle04_LEFT_frame:
	.word marco_idle04_LEFT
marco_idle05_LEFT_frame:
	.word marco_idle05_LEFT
marco_idle06_LEFT_frame:
	.word marco_idle06_LEFT
marco_duck01_LEFT_frame:
	.word marco_duck01_LEFT
marco_duck02_LEFT_frame:
	.word marco_duck02_LEFT
marco_duck03_LEFT_frame:
	.word marco_duck03_LEFT
marco_duck04_LEFT_frame:
	.word marco_duck04_LEFT
marco_duck05_LEFT_frame:
	.word marco_duck05_LEFT
marco_duck06_LEFT_frame:
	.word marco_duck06_LEFT
marco_duck07_LEFT_frame:
	.word marco_duck07_LEFT
marco_duck08_LEFT_frame:
	.word marco_duck08_LEFT
marco_duck09_LEFT_frame:
	.word marco_duck09_LEFT
marco_duck10_LEFT_frame:
	.word marco_duck10_LEFT
marco_run01_LEFT_frame:
	.word marco_run01_LEFT
marco_run02_LEFT_frame:
	.word marco_run02_LEFT
marco_run03_LEFT_frame:
	.word marco_run03_LEFT
marco_run04_LEFT_frame:
	.word marco_run04_LEFT
marco_run05_LEFT_frame:
	.word marco_run05_LEFT
marco_run06_LEFT_frame:
	.word marco_run06_LEFT
marco_run07_LEFT_frame:
	.word marco_run07_LEFT
marco_run08_LEFT_frame:
	.word marco_run08_LEFT
marco_run09_LEFT_frame:
	.word marco_run09_LEFT
marco_shoot01_LEFT_frame:
	.word marco_shoot01_LEFT
marco_shoot02_LEFT_frame:
	.word marco_shoot02_LEFT
marco_shoot03_LEFT_frame:
	.word marco_shoot03_LEFT
marco_shoot04_LEFT_frame:
	.word marco_shoot04_LEFT


	; #1: Y pos, #2: X pos, #3: CHR index

marco_idle01_RIGHT:
	.byte marco_idle01_RIGHT_end - marco_idle01_RIGHT - 2	; data size
	.byte 0		; GFX bank index (chr0)

	.byte $D9, $FD, $00
	.byte $D9, $05, $01
	.byte $E1, $F6, $02
	.byte $E1, $FE, $03
	.byte $E1, $06, $04
	.byte $E9, $F5, $05
	.byte $E9, $FD, $06
	.byte $E9, $05, $07
	.byte $E9, $0D, $08
	.byte $F1, $F7, $09
	.byte $F1, $FF, $0A
	.byte $F1, $07, $0B
	.byte $F1, $0F, $0C
	.byte $F9, $F5, $0D
	.byte $F9, $FD, $0E
	.byte $F9, $05, $0F
marco_idle01_RIGHT_end:

marco_idle02_RIGHT:
	.byte marco_idle02_RIGHT_end - marco_idle02_RIGHT - 2	; data size
	.byte 1		; GFX bank index (chr1)

	.byte $D9, $FD, $00
	.byte $D9, $05, $01
	.byte $E1, $F6, $02
	.byte $E1, $FE, $03
	.byte $E1, $06, $04
	.byte $E9, $F5, $05
	.byte $E9, $FD, $06
	.byte $E9, $05, $07
	.byte $E9, $0D, $08
	.byte $F1, $F7, $09
	.byte $F1, $FF, $0A
	.byte $F1, $07, $0B
	.byte $F1, $0F, $0C
	.byte $F9, $F5, $0D
	.byte $F9, $FD, $0E
	.byte $F9, $05, $0F
marco_idle02_RIGHT_end:

marco_idle03_RIGHT:
	.byte marco_idle03_RIGHT_end - marco_idle03_RIGHT - 2	; data size
	.byte 2		; GFX bank index (chr2)

	.byte $D9, $FD, $00
	.byte $D9, $05, $01
	.byte $E1, $F6, $02
	.byte $E1, $FE, $03
	.byte $E1, $06, $04
	.byte $E9, $F5, $05
	.byte $E9, $FD, $06
	.byte $E9, $05, $07
	.byte $E9, $0D, $08
	.byte $F1, $F7, $09
	.byte $F1, $FF, $0A
	.byte $F1, $07, $0B
	.byte $F1, $0F, $0C
	.byte $F9, $F5, $0D
	.byte $F9, $FD, $0E
	.byte $F9, $05, $0F
marco_idle03_RIGHT_end:

marco_idle04_RIGHT:
	.byte marco_idle04_RIGHT_end - marco_idle04_RIGHT - 2	; data size
	.byte 2		; GFX bank index (chr2)

	.byte $D9, $FD, $00
	.byte $D9, $05, $01
	.byte $E1, $F6, $02
	.byte $E1, $FE, $03
	.byte $E1, $06, $04
	.byte $E9, $F5, $05
	.byte $E9, $FD, $06
	.byte $E9, $05, $07
	.byte $E9, $0D, $08
	.byte $F1, $F7, $09
	.byte $F1, $FF, $0A
	.byte $F1, $07, $0B
	.byte $F1, $0F, $0C
	.byte $F9, $F5, $0D
	.byte $F9, $FD, $0E
	.byte $F9, $05, $0F
marco_idle04_RIGHT_end:

marco_idle05_RIGHT:
	.byte marco_idle05_RIGHT_end - marco_idle05_RIGHT - 2	; data size
	.byte 1		; GFX bank index (chr1)

	.byte $D9, $FD, $00
	.byte $D9, $05, $01
	.byte $E1, $F6, $02
	.byte $E1, $FE, $03
	.byte $E1, $06, $04
	.byte $E9, $F5, $05
	.byte $E9, $FD, $06
	.byte $E9, $05, $07
	.byte $E9, $0D, $08
	.byte $F1, $F7, $09
	.byte $F1, $FF, $0A
	.byte $F1, $07, $0B
	.byte $F1, $0F, $0C
	.byte $F9, $F5, $0D
	.byte $F9, $FD, $0E
	.byte $F9, $05, $0F
marco_idle05_RIGHT_end:

marco_idle06_RIGHT:
	.byte marco_idle06_RIGHT_end - marco_idle06_RIGHT - 2	; data size
	.byte 0		; GFX bank index (chr0)

	.byte $D9, $FD, $00
	.byte $D9, $05, $01
	.byte $E1, $F6, $02
	.byte $E1, $FE, $03
	.byte $E1, $06, $04
	.byte $E9, $F5, $05
	.byte $E9, $FD, $06
	.byte $E9, $05, $07
	.byte $E9, $0D, $08
	.byte $F1, $F7, $09
	.byte $F1, $FF, $0A
	.byte $F1, $07, $0B
	.byte $F1, $0F, $0C
	.byte $F9, $F5, $0D
	.byte $F9, $FD, $0E
	.byte $F9, $05, $0F
marco_idle06_RIGHT_end:

marco_duck01_RIGHT:
	.byte marco_duck01_RIGHT_end - marco_duck01_RIGHT - 2	; data size
	.byte 3		; GFX bank index (chr3)

	.byte $D7, $FA, $00
	.byte $D7, $02, $01
	.byte $DF, $F5, $02
	.byte $DF, $FD, $03
	.byte $DF, $05, $04
	.byte $E7, $F4, $05
	.byte $E7, $FC, $06
	.byte $E7, $04, $07
	.byte $EF, $F7, $08
	.byte $EF, $FF, $09
	.byte $EF, $07, $0A
	.byte $EF, $0F, $0B
	.byte $F7, $F5, $0C
	.byte $F7, $FD, $0D
	.byte $F7, $05, $0E
	.byte $FF, $F5, $0F
	.byte $FF, $FD, $10
	.byte $FF, $05, $11
marco_duck01_RIGHT_end:

marco_duck02_RIGHT:
	.byte marco_duck02_RIGHT_end - marco_duck02_RIGHT - 2	; data size
	.byte 4		; GFX bank index (chr4)

	.byte $DA, $F5, $00
	.byte $DA, $FE, $01
	.byte $DA, $06, $02
	.byte $E2, $F6, $03
	.byte $E2, $FE, $04
	.byte $E2, $06, $05
	.byte $EA, $F5, $06
	.byte $EA, $FD, $07
	.byte $EA, $05, $08
	.byte $EA, $0D, $09
	.byte $F2, $F7, $0A
	.byte $F2, $FF, $0B
	.byte $F2, $07, $0C
	.byte $F2, $0F, $0D
	.byte $FA, $F5, $0E
	.byte $FA, $FD, $0F
	.byte $FA, $05, $10
marco_duck02_RIGHT_end:

marco_duck03_RIGHT:
	.byte marco_duck03_RIGHT_end - marco_duck03_RIGHT - 2	; data size
	.byte 5		; GFX bank index (chr5)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck03_RIGHT_end:

marco_duck04_RIGHT:
	.byte marco_duck04_RIGHT_end - marco_duck04_RIGHT - 2	; data size
	.byte 6		; GFX bank index (chr6)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck04_RIGHT_end:

marco_duck05_RIGHT:
	.byte marco_duck05_RIGHT_end - marco_duck05_RIGHT - 2	; data size
	.byte 7		; GFX bank index (chr7)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck05_RIGHT_end:

marco_duck06_RIGHT:
	.byte marco_duck06_RIGHT_end - marco_duck06_RIGHT - 2	; data size
	.byte 8		; GFX bank index (chr8)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck06_RIGHT_end:

marco_duck07_RIGHT:
	.byte marco_duck07_RIGHT_end - marco_duck07_RIGHT - 2	; data size
	.byte 8		; GFX bank index (chr8)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck07_RIGHT_end:

marco_duck08_RIGHT:
	.byte marco_duck08_RIGHT_end - marco_duck08_RIGHT - 2	; data size
	.byte 7		; GFX bank index (chr7)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck08_RIGHT_end:

marco_duck09_RIGHT:
	.byte marco_duck09_RIGHT_end - marco_duck09_RIGHT - 2	; data size
	.byte 6		; GFX bank index (chr6)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck09_RIGHT_end:

marco_duck10_RIGHT:
	.byte marco_duck10_RIGHT_end - marco_duck10_RIGHT - 2	; data size
	.byte 5		; GFX bank index (chr5)

	.byte $E8, $F1, $00
	.byte $E8, $F9, $01
	.byte $E8, $01, $02
	.byte $E8, $09, $03
	.byte $F0, $F0, $04
	.byte $F0, $F8, $05
	.byte $F0, $00, $06
	.byte $F0, $08, $07
	.byte $F8, $F2, $08
	.byte $F8, $FA, $09
	.byte $F8, $02, $0A
	.byte $F8, $0A, $0B
marco_duck10_RIGHT_end:

marco_run01_RIGHT:
	.byte marco_run01_RIGHT_end - marco_run01_RIGHT - 2	; data size
	.byte 19		; GFX bank index (chr19)

	.byte $D8, $FE, $00
	.byte $D8, $06, $01
	.byte $E0, $F6, $02
	.byte $E0, $FE, $03
	.byte $E0, $06, $04
	.byte $E8, $F5, $05
	.byte $E8, $FD, $06
	.byte $E8, $05, $07
	.byte $E8, $0D, $08
	.byte $F0, $F9, $09
	.byte $F0, $01, $0A
	.byte $F0, $09, $0B
	.byte $F0, $11, $0C
	.byte $F8, $F8, $0D
	.byte $F8, $00, $0E
	.byte $F8, $08, $0F
marco_run01_RIGHT_end:

marco_run02_RIGHT:
	.byte marco_run02_RIGHT_end - marco_run02_RIGHT - 2	; data size
	.byte 9		; GFX bank index (chr9)

	.byte $D6, $FE, $00
	.byte $D6, $06, $01
	.byte $DE, $F6, $02
	.byte $DE, $FE, $03
	.byte $DE, $06, $04
	.byte $E6, $F5, $05
	.byte $E6, $FD, $06
	.byte $E6, $05, $07
	.byte $E6, $0D, $08
	.byte $EE, $F8, $09
	.byte $EE, $00, $0A
	.byte $EE, $08, $0B
	.byte $EE, $10, $0C
	.byte $F6, $F9, $0D
	.byte $F6, $01, $0E
	.byte $FE, $FC, $0F
	.byte $FE, $04, $10
marco_run02_RIGHT_end:

marco_run03_RIGHT:
	.byte marco_run03_RIGHT_end - marco_run03_RIGHT - 2	; data size
	.byte 10		; GFX bank index (chr10)

	.byte $D5, $FE, $00
	.byte $D5, $06, $01
	.byte $DD, $F6, $02
	.byte $DD, $FE, $03
	.byte $DD, $06, $04
	.byte $E5, $F5, $05
	.byte $E5, $FD, $06
	.byte $E5, $05, $07
	.byte $E5, $0D, $08
	.byte $ED, $FA, $09
	.byte $ED, $02, $0A
	.byte $ED, $0A, $0B
	.byte $ED, $12, $0C
	.byte $F5, $F6, $0D
	.byte $F5, $FE, $0E
	.byte $F5, $06, $0F
	.byte $FD, $FA, $10
marco_run03_RIGHT_end:

marco_run04_RIGHT:
	.byte marco_run04_RIGHT_end - marco_run04_RIGHT - 2	; data size
	.byte 11		; GFX bank index (chr11)

	.byte $D5, $FD, $00
	.byte $D5, $05, $01
	.byte $DD, $F5, $02
	.byte $DD, $FD, $03
	.byte $DD, $05, $04
	.byte $E5, $F4, $05
	.byte $E5, $FC, $06
	.byte $E5, $04, $07
	.byte $E5, $0C, $08
	.byte $ED, $F6, $09
	.byte $ED, $FE, $0A
	.byte $ED, $06, $0B
	.byte $ED, $0E, $0C
	.byte $F5, $F2, $0D
	.byte $F5, $FA, $0E
	.byte $F5, $04, $0F
	.byte $F5, $0C, $10
	.byte $FD, $F6, $11
marco_run04_RIGHT_end:

marco_run05_RIGHT:
	.byte marco_run05_RIGHT_end - marco_run05_RIGHT - 2	; data size
	.byte 20		; GFX bank index (chr20)

	.byte $D8, $F7, $00
	.byte $D8, $FF, $01
	.byte $D8, $07, $02
	.byte $E0, $F5, $03
	.byte $E0, $FD, $04
	.byte $E0, $05, $05
	.byte $E8, $F4, $06
	.byte $E8, $FC, $07
	.byte $E8, $04, $08
	.byte $E8, $0C, $09
	.byte $F0, $F6, $0A
	.byte $F0, $FE, $0B
	.byte $F0, $06, $0C
	.byte $F0, $0E, $0D
	.byte $F8, $F4, $0E
	.byte $F8, $FC, $0F
	.byte $F8, $04, $10
marco_run05_RIGHT_end:

marco_run06_RIGHT:
	.byte marco_run06_RIGHT_end - marco_run06_RIGHT - 2	; data size
	.byte 12		; GFX bank index (chr12)

	.byte $D7, $FD, $00
	.byte $D7, $05, $01
	.byte $DF, $F5, $02
	.byte $DF, $FD, $03
	.byte $DF, $05, $04
	.byte $E7, $F4, $05
	.byte $E7, $FC, $06
	.byte $E7, $04, $07
	.byte $E7, $0C, $08
	.byte $EF, $F6, $09
	.byte $EF, $FE, $0A
	.byte $EF, $06, $0B
	.byte $EF, $0E, $0C
	.byte $F7, $F8, $0D
	.byte $F7, $00, $0E
	.byte $FF, $FD, $0F
marco_run06_RIGHT_end:

marco_run07_RIGHT:
	.byte marco_run07_RIGHT_end - marco_run07_RIGHT - 2	; data size
	.byte 21		; GFX bank index (chr21)

	.byte $D7, $F7, $00
	.byte $D7, $FF, $01
	.byte $D7, $07, $02
	.byte $DF, $F6, $03
	.byte $DF, $FE, $04
	.byte $DF, $06, $05
	.byte $E7, $F5, $06
	.byte $E7, $FD, $07
	.byte $E7, $05, $08
	.byte $E7, $0D, $09
	.byte $EF, $F7, $0A
	.byte $EF, $FF, $0B
	.byte $EF, $07, $0C
	.byte $EF, $0F, $0D
	.byte $F7, $F5, $0E
	.byte $F7, $FD, $0F
	.byte $F7, $05, $10
marco_run07_RIGHT_end:

marco_run08_RIGHT:
	.byte marco_run08_RIGHT_end - marco_run08_RIGHT - 2	; data size
	.byte 13		; GFX bank index (chr13)

	.byte $D5, $FE, $00
	.byte $D5, $06, $01
	.byte $DD, $F6, $02
	.byte $DD, $FE, $03
	.byte $DD, $06, $04
	.byte $E5, $F5, $05
	.byte $E5, $FD, $06
	.byte $E5, $05, $07
	.byte $E5, $0D, $08
	.byte $ED, $F2, $09
	.byte $ED, $FA, $0A
	.byte $ED, $02, $0B
	.byte $ED, $0A, $0C
	.byte $ED, $12, $0D
	.byte $F5, $F1, $0E
	.byte $F5, $F9, $0F
	.byte $F5, $03, $10
	.byte $F5, $0B, $11
marco_run08_RIGHT_end:

marco_run09_RIGHT:
	.byte marco_run09_RIGHT_end - marco_run09_RIGHT - 2	; data size
	.byte 14		; GFX bank index (chr14)

	.byte $D7, $FF, $00
	.byte $D7, $07, $01
	.byte $DF, $F6, $02
	.byte $DF, $FE, $03
	.byte $DF, $06, $04
	.byte $E7, $F5, $05
	.byte $E7, $FD, $06
	.byte $E7, $05, $07
	.byte $E7, $0D, $08
	.byte $EF, $FA, $09
	.byte $EF, $02, $0A
	.byte $EF, $0A, $0B
	.byte $EF, $12, $0C
	.byte $F7, $F8, $0D
	.byte $F7, $00, $0E
	.byte $FF, $FB, $0F
marco_run09_RIGHT_end:

marco_shoot01_RIGHT:
	.byte marco_shoot01_RIGHT_end - marco_shoot01_RIGHT - 2	; data size
	.byte 15		; GFX bank index (chr15)

	.byte $DA, $F8, $00
	.byte $DA, $00, $01
	.byte $DA, $08, $02
	.byte $DA, $1E, $03
	.byte $E2, $F5, $04
	.byte $E2, $FD, $05
	.byte $E2, $05, $06
	.byte $E2, $0D, $07
	.byte $E2, $15, $08
	.byte $E2, $1D, $09
	.byte $E2, $25, $0A
	.byte $EA, $F5, $0B
	.byte $EA, $FD, $0C
	.byte $EA, $05, $0D
	.byte $EA, $0D, $0E
	.byte $F2, $F7, $0F
	.byte $F2, $FF, $10
	.byte $F2, $07, $11
	.byte $FA, $F5, $12
	.byte $FA, $FD, $13
	.byte $FA, $05, $14
marco_shoot01_RIGHT_end:

marco_shoot02_RIGHT:
	.byte marco_shoot02_RIGHT_end - marco_shoot02_RIGHT - 2	; data size
	.byte 16		; GFX bank index (chr16)

	.byte $DA, $F8, $00
	.byte $DA, $00, $01
	.byte $DA, $08, $02
	.byte $DA, $10, $03
	.byte $DA, $1E, $04
	.byte $DA, $26, $05
	.byte $E2, $F5, $06
	.byte $E2, $FD, $07
	.byte $E2, $05, $08
	.byte $E2, $0D, $09
	.byte $E2, $15, $0A
	.byte $E2, $1D, $0B
	.byte $E2, $25, $0C
	.byte $EA, $F5, $0D
	.byte $EA, $FD, $0E
	.byte $EA, $05, $0F
	.byte $EA, $0D, $10
	.byte $F2, $F7, $11
	.byte $F2, $FF, $12
	.byte $F2, $07, $13
	.byte $FA, $F5, $14
	.byte $FA, $FD, $15
	.byte $FA, $05, $16
marco_shoot02_RIGHT_end:

marco_shoot03_RIGHT:
	.byte marco_shoot03_RIGHT_end - marco_shoot03_RIGHT - 2	; data size
	.byte 17		; GFX bank index (chr17)

	.byte $D8, $FF, $00
	.byte $D8, $07, $01
	.byte $D8, $0F, $02
	.byte $E0, $F5, $03
	.byte $E0, $FD, $04
	.byte $E0, $05, $05
	.byte $E0, $0D, $06
	.byte $E0, $15, $07
	.byte $E8, $F4, $08
	.byte $E8, $FC, $09
	.byte $E8, $04, $0A
	.byte $E8, $0C, $0B
	.byte $F0, $F7, $0C
	.byte $F0, $FF, $0D
	.byte $F0, $07, $0E
	.byte $F8, $F5, $0F
	.byte $F8, $FD, $10
	.byte $F8, $05, $11
marco_shoot03_RIGHT_end:

marco_shoot04_RIGHT:
	.byte marco_shoot04_RIGHT_end - marco_shoot04_RIGHT - 2	; data size
	.byte 18		; GFX bank index (chr18)

	.byte $D8, $FF, $00
	.byte $D8, $07, $01
	.byte $D8, $14, $02
	.byte $E0, $F5, $03
	.byte $E0, $FD, $04
	.byte $E0, $05, $05
	.byte $E0, $0D, $06
	.byte $E0, $15, $07
	.byte $E8, $F4, $08
	.byte $E8, $FC, $09
	.byte $E8, $04, $0A
	.byte $E8, $0C, $0B
	.byte $F0, $F7, $0C
	.byte $F0, $FF, $0D
	.byte $F0, $07, $0E
	.byte $F8, $F5, $0F
	.byte $F8, $FD, $10
	.byte $F8, $05, $11
marco_shoot04_RIGHT_end:

marco_idle01_LEFT:
	.byte marco_idle01_LEFT_end - marco_idle01_LEFT - 2	; data size
	.byte 22		; GFX bank index (chr22)

	.byte $D9, $FB, $00
	.byte $D9, $F3, $01
	.byte $E1, $02, $02
	.byte $E1, $FA, $03
	.byte $E1, $F2, $04
	.byte $E9, $03, $05
	.byte $E9, $FB, $06
	.byte $E9, $F3, $07
	.byte $E9, $EB, $08
	.byte $F1, $01, $09
	.byte $F1, $F9, $0A
	.byte $F1, $F1, $0B
	.byte $F1, $E9, $0C
	.byte $F9, $03, $0D
	.byte $F9, $FB, $0E
	.byte $F9, $F3, $0F
marco_idle01_LEFT_end:

marco_idle02_LEFT:
	.byte marco_idle02_LEFT_end - marco_idle02_LEFT - 2	; data size
	.byte 23		; GFX bank index (chr23)

	.byte $D9, $FB, $00
	.byte $D9, $F3, $01
	.byte $E1, $02, $02
	.byte $E1, $FA, $03
	.byte $E1, $F2, $04
	.byte $E9, $03, $05
	.byte $E9, $FB, $06
	.byte $E9, $F3, $07
	.byte $E9, $EB, $08
	.byte $F1, $01, $09
	.byte $F1, $F9, $0A
	.byte $F1, $F1, $0B
	.byte $F1, $E9, $0C
	.byte $F9, $03, $0D
	.byte $F9, $FB, $0E
	.byte $F9, $F3, $0F
marco_idle02_LEFT_end:

marco_idle03_LEFT:
	.byte marco_idle03_LEFT_end - marco_idle03_LEFT - 2	; data size
	.byte 24		; GFX bank index (chr24)

	.byte $D9, $FB, $00
	.byte $D9, $F3, $01
	.byte $E1, $02, $02
	.byte $E1, $FA, $03
	.byte $E1, $F2, $04
	.byte $E9, $03, $05
	.byte $E9, $FB, $06
	.byte $E9, $F3, $07
	.byte $E9, $EB, $08
	.byte $F1, $01, $09
	.byte $F1, $F9, $0A
	.byte $F1, $F1, $0B
	.byte $F1, $E9, $0C
	.byte $F9, $03, $0D
	.byte $F9, $FB, $0E
	.byte $F9, $F3, $0F
marco_idle03_LEFT_end:

marco_idle04_LEFT:
	.byte marco_idle04_LEFT_end - marco_idle04_LEFT - 2	; data size
	.byte 25		; GFX bank index (chr25)

	.byte $D9, $FB, $00
	.byte $D9, $F3, $01
	.byte $E1, $02, $02
	.byte $E1, $FA, $03
	.byte $E1, $F2, $04
	.byte $E9, $03, $05
	.byte $E9, $FB, $06
	.byte $E9, $F3, $07
	.byte $E9, $EB, $08
	.byte $F1, $01, $09
	.byte $F1, $F9, $0A
	.byte $F1, $F1, $0B
	.byte $F1, $E9, $0C
	.byte $F9, $03, $0D
	.byte $F9, $FB, $0E
	.byte $F9, $F3, $0F
marco_idle04_LEFT_end:

marco_idle05_LEFT:
	.byte marco_idle05_LEFT_end - marco_idle05_LEFT - 2	; data size
	.byte 26		; GFX bank index (chr26)

	.byte $D9, $FB, $00
	.byte $D9, $F3, $01
	.byte $E1, $02, $02
	.byte $E1, $FA, $03
	.byte $E1, $F2, $04
	.byte $E9, $03, $05
	.byte $E9, $FB, $06
	.byte $E9, $F3, $07
	.byte $E9, $EB, $08
	.byte $F1, $01, $09
	.byte $F1, $F9, $0A
	.byte $F1, $F1, $0B
	.byte $F1, $E9, $0C
	.byte $F9, $03, $0D
	.byte $F9, $FB, $0E
	.byte $F9, $F3, $0F
marco_idle05_LEFT_end:

marco_idle06_LEFT:
	.byte marco_idle06_LEFT_end - marco_idle06_LEFT - 2	; data size
	.byte 27		; GFX bank index (chr27)

	.byte $D9, $FB, $00
	.byte $D9, $F3, $01
	.byte $E1, $02, $02
	.byte $E1, $FA, $03
	.byte $E1, $F2, $04
	.byte $E9, $03, $05
	.byte $E9, $FB, $06
	.byte $E9, $F3, $07
	.byte $E9, $EB, $08
	.byte $F1, $01, $09
	.byte $F1, $F9, $0A
	.byte $F1, $F1, $0B
	.byte $F1, $E9, $0C
	.byte $F9, $03, $0D
	.byte $F9, $FB, $0E
	.byte $F9, $F3, $0F
marco_idle06_LEFT_end:

marco_duck01_LEFT:
	.byte marco_duck01_LEFT_end - marco_duck01_LEFT - 2	; data size
	.byte 28		; GFX bank index (chr28)

	.byte $D7, $FE, $00
	.byte $D7, $F6, $01
	.byte $DF, $03, $02
	.byte $DF, $FB, $03
	.byte $DF, $F3, $04
	.byte $E7, $04, $05
	.byte $E7, $FC, $06
	.byte $E7, $F4, $07
	.byte $EF, $01, $08
	.byte $EF, $F9, $09
	.byte $EF, $F1, $0A
	.byte $EF, $E9, $0B
	.byte $F7, $03, $0C
	.byte $F7, $FB, $0D
	.byte $F7, $F3, $0E
	.byte $FF, $03, $0F
	.byte $FF, $FB, $10
	.byte $FF, $F3, $11
marco_duck01_LEFT_end:

marco_duck02_LEFT:
	.byte marco_duck02_LEFT_end - marco_duck02_LEFT - 2	; data size
	.byte 29		; GFX bank index (chr29)

	.byte $DA, $03, $00
	.byte $DA, $FA, $01
	.byte $DA, $F2, $02
	.byte $E2, $02, $03
	.byte $E2, $FA, $04
	.byte $E2, $F2, $05
	.byte $EA, $03, $06
	.byte $EA, $FB, $07
	.byte $EA, $F3, $08
	.byte $EA, $EB, $09
	.byte $F2, $01, $0A
	.byte $F2, $F9, $0B
	.byte $F2, $F1, $0C
	.byte $F2, $E9, $0D
	.byte $FA, $03, $0E
	.byte $FA, $FB, $0F
	.byte $FA, $F3, $10
marco_duck02_LEFT_end:

marco_duck03_LEFT:
	.byte marco_duck03_LEFT_end - marco_duck03_LEFT - 2	; data size
	.byte 30		; GFX bank index (chr30)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck03_LEFT_end:

marco_duck04_LEFT:
	.byte marco_duck04_LEFT_end - marco_duck04_LEFT - 2	; data size
	.byte 31		; GFX bank index (chr31)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck04_LEFT_end:

marco_duck05_LEFT:
	.byte marco_duck05_LEFT_end - marco_duck05_LEFT - 2	; data size
	.byte 32		; GFX bank index (chr32)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck05_LEFT_end:

marco_duck06_LEFT:
	.byte marco_duck06_LEFT_end - marco_duck06_LEFT - 2	; data size
	.byte 33		; GFX bank index (chr33)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck06_LEFT_end:

marco_duck07_LEFT:
	.byte marco_duck07_LEFT_end - marco_duck07_LEFT - 2	; data size
	.byte 34		; GFX bank index (chr34)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck07_LEFT_end:

marco_duck08_LEFT:
	.byte marco_duck08_LEFT_end - marco_duck08_LEFT - 2	; data size
	.byte 35		; GFX bank index (chr35)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck08_LEFT_end:

marco_duck09_LEFT:
	.byte marco_duck09_LEFT_end - marco_duck09_LEFT - 2	; data size
	.byte 36		; GFX bank index (chr36)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck09_LEFT_end:

marco_duck10_LEFT:
	.byte marco_duck10_LEFT_end - marco_duck10_LEFT - 2	; data size
	.byte 37		; GFX bank index (chr37)

	.byte $E8, $07, $00
	.byte $E8, $FF, $01
	.byte $E8, $F7, $02
	.byte $E8, $EF, $03
	.byte $F0, $08, $04
	.byte $F0, $00, $05
	.byte $F0, $F8, $06
	.byte $F0, $F0, $07
	.byte $F8, $06, $08
	.byte $F8, $FE, $09
	.byte $F8, $F6, $0A
	.byte $F8, $EE, $0B
marco_duck10_LEFT_end:

marco_run01_LEFT:
	.byte marco_run01_LEFT_end - marco_run01_LEFT - 2	; data size
	.byte 38		; GFX bank index (chr38)

	.byte $D8, $FA, $00
	.byte $D8, $F2, $01
	.byte $E0, $02, $02
	.byte $E0, $FA, $03
	.byte $E0, $F2, $04
	.byte $E8, $03, $05
	.byte $E8, $FB, $06
	.byte $E8, $F3, $07
	.byte $E8, $EB, $08
	.byte $F0, $FF, $09
	.byte $F0, $F7, $0A
	.byte $F0, $EF, $0B
	.byte $F0, $E7, $0C
	.byte $F8, $00, $0D
	.byte $F8, $F8, $0E
	.byte $F8, $F0, $0F
marco_run01_LEFT_end:

marco_run02_LEFT:
	.byte marco_run02_LEFT_end - marco_run02_LEFT - 2	; data size
	.byte 39		; GFX bank index (chr39)

	.byte $D6, $FA, $00
	.byte $D6, $F2, $01
	.byte $DE, $02, $02
	.byte $DE, $FA, $03
	.byte $DE, $F2, $04
	.byte $E6, $03, $05
	.byte $E6, $FB, $06
	.byte $E6, $F3, $07
	.byte $E6, $EB, $08
	.byte $EE, $00, $09
	.byte $EE, $F8, $0A
	.byte $EE, $F0, $0B
	.byte $EE, $E8, $0C
	.byte $F6, $FF, $0D
	.byte $F6, $F7, $0E
	.byte $FE, $FC, $0F
	.byte $FE, $F4, $10
marco_run02_LEFT_end:

marco_run03_LEFT:
	.byte marco_run03_LEFT_end - marco_run03_LEFT - 2	; data size
	.byte 40		; GFX bank index (chr40)

	.byte $D5, $FA, $00
	.byte $D5, $F2, $01
	.byte $DD, $02, $02
	.byte $DD, $FA, $03
	.byte $DD, $F2, $04
	.byte $E5, $03, $05
	.byte $E5, $FB, $06
	.byte $E5, $F3, $07
	.byte $E5, $EB, $08
	.byte $ED, $FE, $09
	.byte $ED, $F6, $0A
	.byte $ED, $EE, $0B
	.byte $ED, $E6, $0C
	.byte $F5, $02, $0D
	.byte $F5, $FA, $0E
	.byte $F5, $F2, $0F
	.byte $FD, $FE, $10
marco_run03_LEFT_end:

marco_run04_LEFT:
	.byte marco_run04_LEFT_end - marco_run04_LEFT - 2	; data size
	.byte 41		; GFX bank index (chr41)

	.byte $D5, $FB, $00
	.byte $D5, $F3, $01
	.byte $DD, $03, $02
	.byte $DD, $FB, $03
	.byte $DD, $F3, $04
	.byte $E5, $04, $05
	.byte $E5, $FC, $06
	.byte $E5, $F4, $07
	.byte $E5, $EC, $08
	.byte $ED, $02, $09
	.byte $ED, $FA, $0A
	.byte $ED, $F2, $0B
	.byte $ED, $EA, $0C
	.byte $F5, $06, $0D
	.byte $F5, $FE, $0E
	.byte $F5, $F4, $0F
	.byte $F5, $EC, $10
	.byte $FD, $02, $11
marco_run04_LEFT_end:

marco_run05_LEFT:
	.byte marco_run05_LEFT_end - marco_run05_LEFT - 2	; data size
	.byte 42		; GFX bank index (chr42)

	.byte $D8, $01, $00
	.byte $D8, $F9, $01
	.byte $D8, $F1, $02
	.byte $E0, $03, $03
	.byte $E0, $FB, $04
	.byte $E0, $F3, $05
	.byte $E8, $04, $06
	.byte $E8, $FC, $07
	.byte $E8, $F4, $08
	.byte $E8, $EC, $09
	.byte $F0, $02, $0A
	.byte $F0, $FA, $0B
	.byte $F0, $F2, $0C
	.byte $F0, $EA, $0D
	.byte $F8, $04, $0E
	.byte $F8, $FC, $0F
	.byte $F8, $F4, $10
marco_run05_LEFT_end:

marco_run06_LEFT:
	.byte marco_run06_LEFT_end - marco_run06_LEFT - 2	; data size
	.byte 43		; GFX bank index (chr43)

	.byte $D7, $FB, $00
	.byte $D7, $F3, $01
	.byte $DF, $03, $02
	.byte $DF, $FB, $03
	.byte $DF, $F3, $04
	.byte $E7, $04, $05
	.byte $E7, $FC, $06
	.byte $E7, $F4, $07
	.byte $E7, $EC, $08
	.byte $EF, $02, $09
	.byte $EF, $FA, $0A
	.byte $EF, $F2, $0B
	.byte $EF, $EA, $0C
	.byte $F7, $00, $0D
	.byte $F7, $F8, $0E
	.byte $FF, $FB, $0F
marco_run06_LEFT_end:

marco_run07_LEFT:
	.byte marco_run07_LEFT_end - marco_run07_LEFT - 2	; data size
	.byte 44		; GFX bank index (chr44)

	.byte $D7, $01, $00
	.byte $D7, $F9, $01
	.byte $D7, $F1, $02
	.byte $DF, $02, $03
	.byte $DF, $FA, $04
	.byte $DF, $F2, $05
	.byte $E7, $03, $06
	.byte $E7, $FB, $07
	.byte $E7, $F3, $08
	.byte $E7, $EB, $09
	.byte $EF, $01, $0A
	.byte $EF, $F9, $0B
	.byte $EF, $F1, $0C
	.byte $EF, $E9, $0D
	.byte $F7, $03, $0E
	.byte $F7, $FB, $0F
	.byte $F7, $F3, $10
marco_run07_LEFT_end:

marco_run08_LEFT:
	.byte marco_run08_LEFT_end - marco_run08_LEFT - 2	; data size
	.byte 45		; GFX bank index (chr45)

	.byte $D5, $FA, $00
	.byte $D5, $F2, $01
	.byte $DD, $02, $02
	.byte $DD, $FA, $03
	.byte $DD, $F2, $04
	.byte $E5, $03, $05
	.byte $E5, $FB, $06
	.byte $E5, $F3, $07
	.byte $E5, $EB, $08
	.byte $ED, $06, $09
	.byte $ED, $FE, $0A
	.byte $ED, $F6, $0B
	.byte $ED, $EE, $0C
	.byte $ED, $E6, $0D
	.byte $F5, $07, $0E
	.byte $F5, $FF, $0F
	.byte $F5, $F5, $10
	.byte $F5, $ED, $11
marco_run08_LEFT_end:

marco_run09_LEFT:
	.byte marco_run09_LEFT_end - marco_run09_LEFT - 2	; data size
	.byte 46		; GFX bank index (chr46)

	.byte $D7, $F9, $00
	.byte $D7, $F1, $01
	.byte $DF, $02, $02
	.byte $DF, $FA, $03
	.byte $DF, $F2, $04
	.byte $E7, $03, $05
	.byte $E7, $FB, $06
	.byte $E7, $F3, $07
	.byte $E7, $EB, $08
	.byte $EF, $FE, $09
	.byte $EF, $F6, $0A
	.byte $EF, $EE, $0B
	.byte $EF, $E6, $0C
	.byte $F7, $00, $0D
	.byte $F7, $F8, $0E
	.byte $FF, $FD, $0F
marco_run09_LEFT_end:

marco_shoot01_LEFT:
	.byte marco_shoot01_LEFT_end - marco_shoot01_LEFT - 2	; data size
	.byte 47		; GFX bank index (chr47)

	.byte $DA, $00, $00
	.byte $DA, $F8, $01
	.byte $DA, $F0, $02
	.byte $DA, $DA, $03
	.byte $E2, $03, $04
	.byte $E2, $FB, $05
	.byte $E2, $F3, $06
	.byte $E2, $EB, $07
	.byte $E2, $E3, $08
	.byte $E2, $DB, $09
	.byte $E2, $D3, $0A
	.byte $EA, $03, $0B
	.byte $EA, $FB, $0C
	.byte $EA, $F3, $0D
	.byte $EA, $EB, $0E
	.byte $F2, $01, $0F
	.byte $F2, $F9, $10
	.byte $F2, $F1, $11
	.byte $FA, $03, $12
	.byte $FA, $FB, $13
	.byte $FA, $F3, $14
marco_shoot01_LEFT_end:

marco_shoot02_LEFT:
	.byte marco_shoot02_LEFT_end - marco_shoot02_LEFT - 2	; data size
	.byte 48		; GFX bank index (chr48)

	.byte $DA, $00, $00
	.byte $DA, $F8, $01
	.byte $DA, $F0, $02
	.byte $DA, $E8, $03
	.byte $DA, $DA, $04
	.byte $DA, $D2, $05
	.byte $E2, $03, $06
	.byte $E2, $FB, $07
	.byte $E2, $F3, $08
	.byte $E2, $EB, $09
	.byte $E2, $E3, $0A
	.byte $E2, $DB, $0B
	.byte $E2, $D3, $0C
	.byte $EA, $03, $0D
	.byte $EA, $FB, $0E
	.byte $EA, $F3, $0F
	.byte $EA, $EB, $10
	.byte $F2, $01, $11
	.byte $F2, $F9, $12
	.byte $F2, $F1, $13
	.byte $FA, $03, $14
	.byte $FA, $FB, $15
	.byte $FA, $F3, $16
marco_shoot02_LEFT_end:

marco_shoot03_LEFT:
	.byte marco_shoot03_LEFT_end - marco_shoot03_LEFT - 2	; data size
	.byte 49		; GFX bank index (chr49)

	.byte $D8, $F9, $00
	.byte $D8, $F1, $01
	.byte $D8, $E9, $02
	.byte $E0, $03, $03
	.byte $E0, $FB, $04
	.byte $E0, $F3, $05
	.byte $E0, $EB, $06
	.byte $E0, $E3, $07
	.byte $E8, $04, $08
	.byte $E8, $FC, $09
	.byte $E8, $F4, $0A
	.byte $E8, $EC, $0B
	.byte $F0, $01, $0C
	.byte $F0, $F9, $0D
	.byte $F0, $F1, $0E
	.byte $F8, $03, $0F
	.byte $F8, $FB, $10
	.byte $F8, $F3, $11
marco_shoot03_LEFT_end:

marco_shoot04_LEFT:
	.byte marco_shoot04_LEFT_end - marco_shoot04_LEFT - 2	; data size
	.byte 50		; GFX bank index (chr50)

	.byte $D8, $F9, $00
	.byte $D8, $F1, $01
	.byte $D8, $E4, $02
	.byte $E0, $03, $03
	.byte $E0, $FB, $04
	.byte $E0, $F3, $05
	.byte $E0, $EB, $06
	.byte $E0, $E3, $07
	.byte $E8, $04, $08
	.byte $E8, $FC, $09
	.byte $E8, $F4, $0A
	.byte $E8, $EC, $0B
	.byte $F0, $01, $0C
	.byte $F0, $F9, $0D
	.byte $F0, $F1, $0E
	.byte $F8, $03, $0F
	.byte $F8, $FB, $10
	.byte $F8, $F3, $11
marco_shoot04_LEFT_end:

