;#######################################################
;
; Generated by SPReD-NES Copyright 2017-2022 0x8BitDev
;
;#######################################################

DOG_GFX_SPR_MODE_8X16 = 1

;dog_gfx_chr0:	.incbin "dog_gfx_chr0.bin"	; 512 of 1024 bytes


dog_gfx_palette:
	.byte $21, $38, $16, $0D, $21, $14, $24, $34, $21, $38, $11, $1D, $21, $1A, $2A, $3A


dog_gfx_num_frames:
	.byte $08
dog_gfx_frames_data:
dog01_IDLE01_RIGHT_frame:
	.word dog01_IDLE01_RIGHT
	.byte dog01_IDLE01_RIGHT_end - dog01_IDLE01_RIGHT	; data size
	.byte 0		; GFX bank index (chr0)
dog01_IDLE02_RIGHT_frame:
	.word dog01_IDLE02_RIGHT
	.byte dog01_IDLE02_RIGHT_end - dog01_IDLE02_RIGHT
	.byte 0
dog01_RUN01_RIGHT_frame:
	.word dog01_RUN01_RIGHT
	.byte dog01_RUN01_RIGHT_end - dog01_RUN01_RIGHT
	.byte 0
dog01_JUMP_RIGHT_frame:
	.word dog01_JUMP_RIGHT
	.byte dog01_JUMP_RIGHT_end - dog01_JUMP_RIGHT
	.byte 0
dog01_IDLE01_LEFT_frame:
	.word dog01_IDLE01_LEFT
	.byte dog01_IDLE01_LEFT_end - dog01_IDLE01_LEFT
	.byte 0
dog01_IDLE02_LEFT_frame:
	.word dog01_IDLE02_LEFT
	.byte dog01_IDLE02_LEFT_end - dog01_IDLE02_LEFT
	.byte 0
dog01_RUN01_LEFT_frame:
	.word dog01_RUN01_LEFT
	.byte dog01_RUN01_LEFT_end - dog01_RUN01_LEFT
	.byte 0
dog01_JUMP_LEFT_frame:
	.word dog01_JUMP_LEFT
	.byte dog01_JUMP_LEFT_end - dog01_JUMP_LEFT
	.byte 0


	; #1: Y pos, #2: CHR index, #3: Attributes, #4: X pos

dog01_IDLE01_RIGHT:
	.byte $E1, $00, $00, $F4
	.byte $E1, $02, $00, $FC
	.byte $E1, $04, $00, $04
	.byte $F1, $06, $02, $F4
	.byte $F1, $0A, $02, $04
	.byte $F1, $08, $02, $FC
dog01_IDLE01_RIGHT_end:

dog01_IDLE02_RIGHT:
	.byte $E0, $02, $00, $FC
	.byte $E0, $04, $00, $04
	.byte $F0, $0C, $02, $F4
	.byte $F0, $0E, $02, $FC
	.byte $F0, $10, $02, $04
	.byte $E0, $12, $00, $F4
dog01_IDLE02_RIGHT_end:

dog01_RUN01_RIGHT:
	.byte $E0, $02, $00, $FC
	.byte $E0, $04, $00, $04
	.byte $F0, $1A, $02, $F4
	.byte $F0, $1C, $02, $FC
	.byte $F0, $1E, $00, $04
	.byte $E0, $00, $00, $F4
dog01_RUN01_RIGHT_end:

dog01_JUMP_RIGHT:
	.byte $DE, $02, $00, $FC
	.byte $DE, $04, $00, $04
	.byte $DE, $12, $00, $F4
	.byte $EE, $14, $02, $F4
	.byte $EE, $16, $02, $FC
	.byte $EE, $18, $02, $04
dog01_JUMP_RIGHT_end:

dog01_IDLE01_LEFT:
	.byte $E1, $00, $40, $04
	.byte $E1, $02, $40, $FC
	.byte $E1, $04, $40, $F4
	.byte $F1, $06, $42, $04
	.byte $F1, $0A, $42, $F4
	.byte $F1, $08, $42, $FC
dog01_IDLE01_LEFT_end:

dog01_IDLE02_LEFT:
	.byte $E0, $02, $40, $FC
	.byte $E0, $04, $40, $F4
	.byte $F0, $0C, $42, $04
	.byte $F0, $0E, $42, $FC
	.byte $F0, $10, $42, $F4
	.byte $E0, $12, $40, $04
dog01_IDLE02_LEFT_end:

dog01_RUN01_LEFT:
	.byte $E0, $02, $40, $FC
	.byte $E0, $04, $40, $F4
	.byte $F0, $1A, $42, $04
	.byte $F0, $1C, $42, $FC
	.byte $F0, $1E, $40, $F4
	.byte $E0, $00, $40, $04
dog01_RUN01_LEFT_end:

dog01_JUMP_LEFT:
	.byte $DE, $02, $40, $FC
	.byte $DE, $04, $40, $F4
	.byte $DE, $12, $40, $04
	.byte $EE, $14, $42, $04
	.byte $EE, $16, $42, $FC
	.byte $EE, $18, $42, $F4
dog01_JUMP_LEFT_end:

