//#######################################################
//
// Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
//
//#######################################################

#incasm( "data/set2.asm" )

#define SET2_SPR_VADDR	12288
#define SET2_PALETTE_SLOT	1


typedef struct
{
	const unsigned short*	sprite_data;
	unsigned char		bank;
	unsigned short		size;
	unsigned char		SG_ind;
} spd_ANM_FRAME;


extern unsigned short*	set2_SG_arr;
const unsigned short	set2_palette_size	= 16;	// words

extern unsigned short*	set2_palette;
const unsigned short	set2_frames_cnt	= 6;
extern spd_ANM_FRAME	set2_frames_data[];

const unsigned char	SPR_MARTHA_PUNCH01	= 0;
const unsigned char	SPR_MARTHA_PUNCH02	= 1;
const unsigned char	SPR_MARTHA_PUNCH03	= 2;
const unsigned char	SPR_MARTHA_PUNCH04	= 3;
const unsigned char	SPR_MARTHA_PUNCH05	= 4;
const unsigned char	SPR_MARTHA_PUNCH06_REF04	= 5;

extern spd_ANM_FRAME*	martha_punch01_frame;
extern spd_ANM_FRAME*	martha_punch02_frame;
extern spd_ANM_FRAME*	martha_punch03_frame;
extern spd_ANM_FRAME*	martha_punch04_frame;
extern spd_ANM_FRAME*	martha_punch05_frame;
extern spd_ANM_FRAME*	martha_punch06_ref04_frame;

