//#######################################################
//
// Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
//
//#######################################################

#incasm( "data/set2.asm" )

#define SET2_SPR_VADDR	12288
#define SET2_PALETTE_SLOT	17


#ifndef	DEF_TYPE_SPD_SPRITE
#define	DEF_TYPE_SPD_SPRITE
typedef struct
{
	const unsigned short*	attrs;
	unsigned char		bank;
	unsigned short		size;
	unsigned char		SG_ind;
} spd_SPRITE;
#endif	//DEF_TYPE_SPD_SPRITE


extern unsigned short*	set2_SG_arr;
const unsigned char	set2_SG_cnt	= 5;	// graphics banks count
const unsigned short	set2_palette_size	= 1;	// active palettes

extern unsigned short*	set2_palette;
const unsigned short	set2_frames_cnt	= 6;
extern spd_SPRITE	set2_frames_data[];

const unsigned char	SPR_MARTHA_PUNCH01	= 0;
const unsigned char	SPR_MARTHA_PUNCH02	= 1;
const unsigned char	SPR_MARTHA_PUNCH03	= 2;
const unsigned char	SPR_MARTHA_PUNCH04	= 3;
const unsigned char	SPR_MARTHA_PUNCH05	= 4;
const unsigned char	SPR_MARTHA_PUNCH06_REF04	= 5;

extern spd_SPRITE*	martha_punch01_frame;
extern spd_SPRITE*	martha_punch02_frame;
extern spd_SPRITE*	martha_punch03_frame;
extern spd_SPRITE*	martha_punch04_frame;
extern spd_SPRITE*	martha_punch05_frame;
extern spd_SPRITE*	martha_punch06_ref04_frame;

