//#######################################################
//
// Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
//
//#######################################################

#incasm( "data/set3.asm" )

#define SET3_SPR_VADDR	16384
#define SET3_PALETTE_SLOT	2


typedef struct
{
	const unsigned short*	sprite_data;
	unsigned char		bank;
	unsigned short		size;
	unsigned char		SG_ind;
} spd_ANM_FRAME;


extern unsigned short*	set3_SG_arr;
const unsigned short	set3_palette_size	= 16;	// words

extern unsigned short*	set3_palette;
const unsigned short	set3_frames_cnt	= 12;
extern spd_ANM_FRAME	set3_frames_data[];

const unsigned char	SPR_MPWR_IDLE01_LEFT	= 0;
const unsigned char	SPR_MPWR_WALK01_LEFT	= 1;
const unsigned char	SPR_MPWR_WALK02_LEFT	= 2;
const unsigned char	SPR_MPWR_WALK03_LEFT	= 3;
const unsigned char	SPR_MPWR_WALK04_LEFT	= 4;
const unsigned char	SPR_MPWR_WALK05_LEFT	= 5;
const unsigned char	SPR_MPWR_WALK06_LEFT	= 6;
const unsigned char	SPR_MPWR_KICK01_LEFT	= 7;
const unsigned char	SPR_MPWR_KICK02_LEFT	= 8;
const unsigned char	SPR_MPWR_KICK03_LEFT	= 9;
const unsigned char	SPR_MPWR_KICK04_REF02_LEFT	= 10;
const unsigned char	SPR_MPWR_KICK05_REF01_LEFT	= 11;

extern spd_ANM_FRAME*	mpwr_idle01_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_walk01_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_walk02_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_walk03_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_walk04_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_walk05_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_walk06_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_kick01_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_kick02_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_kick03_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_kick04_ref02_LEFT_frame;
extern spd_ANM_FRAME*	mpwr_kick05_ref01_LEFT_frame;

