;#######################################################
;
; Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################

ANM_TEST_SPR_VADDR	= 8192
ANM_TEST_PALETTE_SLOT	= 0


;chr0:	.incbin "anm_test_chr0.bin"	; 11904 bytes

;anm_test_CHR_arr:	
;	.word 11904, chr0


anm_test_palette:
	.word $147, $1FD, $16C, $1FE, $1B8, $130, $98, $17B, $132, $F0, $A8, $60, $1FF, $1B6, $DB, $00
anm_test_palette_end:

anm_test_num_frames:
	.byte $07
anm_test_frames_data:
martha_punch01_frame:
	.word martha_punch01
	.word martha_punch01_end - martha_punch01	; data size
	.byte 0		; CHR bank index (chr0)
martha_punch02_frame:
	.word martha_punch02
	.word martha_punch02_end - martha_punch02
	.byte 0
martha_punch03_frame:
	.word martha_punch03
	.word martha_punch03_end - martha_punch03
	.byte 0
martha_punch04_frame:
	.word martha_punch04
	.word martha_punch04_end - martha_punch04
	.byte 0
martha_punch05_frame:
	.word martha_punch05
	.word martha_punch05_end - martha_punch05
	.byte 0
martha_punch06_ref04_frame:
	.word martha_punch06_ref04
	.word martha_punch06_ref04_end - martha_punch06_ref04
	.byte 0
martha_punch07_ref03_frame:
	.word martha_punch07_ref03
	.word martha_punch07_ref03_end - martha_punch07_ref03
	.byte 0


	; #1: Y pos, #2: X pos, #3: CHR index, #4: CHR desc

martha_punch01:
	.word $FFA0, $FFF8, $100, $80
	.word $FFA0, $08, $102, $80
	.word $FFB0, $FFE8, $104, $80
	.word $FFB0, $FFF8, $106, $80
	.word $FFB0, $08, $108, $80
	.word $FFC0, $FFE8, $10A, $80
	.word $FFC0, $FFF8, $10C, $80
	.word $FFC0, $08, $10E, $80
	.word $FFD0, $FFE8, $110, $80
	.word $FFD0, $FFF8, $112, $80
	.word $FFD0, $08, $114, $80
	.word $FFE0, $FFE8, $116, $80
	.word $FFE0, $FFF8, $118, $80
	.word $FFE0, $08, $11A, $80
	.word $FFF0, $FFE8, $11C, $80
	.word $FFF0, $FFF8, $11E, $80
	.word $FFF0, $08, $120, $80
martha_punch01_end:

martha_punch02:
	.word $FFA0, $FFE8, $122, $80
	.word $FFA0, $FFF8, $124, $80
	.word $FFB0, $FFE8, $126, $80
	.word $FFB0, $FFF8, $128, $80
	.word $FFB0, $08, $12A, $80
	.word $FFC0, $FFE8, $12C, $80
	.word $FFC0, $FFF8, $12E, $80
	.word $FFC0, $08, $130, $80
	.word $FFD0, $FFE8, $132, $80
	.word $FFD0, $FFF8, $134, $80
	.word $FFD0, $08, $136, $80
	.word $FFE0, $FFE8, $138, $80
	.word $FFE0, $FFF8, $13A, $80
	.word $FFE0, $08, $13C, $80
	.word $FFF0, $FFE8, $13E, $80
martha_punch02_end:

martha_punch03:
	.word $FFA0, $FFF8, $140, $80
	.word $FFA0, $08, $142, $80
	.word $FFB0, $FFE8, $144, $80
	.word $FFB0, $FFF8, $146, $80
	.word $FFB0, $08, $148, $80
	.word $FFC0, $FFE8, $14A, $80
	.word $FFC0, $FFF8, $14C, $80
	.word $FFC0, $08, $14E, $80
	.word $FFC0, $18, $150, $80
	.word $FFD0, $FFE8, $152, $80
	.word $FFD0, $FFF8, $154, $80
	.word $FFD0, $08, $156, $80
	.word $FFD0, $18, $158, $80
	.word $FFE0, $FFE8, $15A, $80
	.word $FFE0, $FFF8, $15C, $80
	.word $FFE0, $08, $15E, $80
	.word $FFF0, $FFE8, $160, $80
	.word $FFF0, $FFF8, $162, $80
	.word $FFF0, $08, $164, $80
martha_punch03_end:

martha_punch04:
	.word $FFA0, $08, $166, $80
	.word $FFA0, $18, $168, $80
	.word $FFB0, $FFE8, $16A, $80
	.word $FFB0, $FFF8, $16C, $80
	.word $FFB0, $08, $16E, $80
	.word $FFB0, $18, $170, $80
	.word $FFB0, $28, $172, $80
	.word $FFC0, $FFF8, $174, $80
	.word $FFC0, $08, $176, $80
	.word $FFC0, $18, $178, $80
	.word $FFC0, $28, $17A, $80
	.word $FFD0, $FFE8, $17C, $80
	.word $FFD0, $FFF8, $17E, $80
	.word $FFD0, $08, $180, $80
	.word $FFD0, $18, $182, $80
	.word $FFE0, $FFE8, $184, $80
	.word $FFE0, $FFF8, $186, $80
	.word $FFE0, $08, $188, $80
	.word $FFF0, $FFE8, $18A, $80
	.word $FFF0, $FFF8, $18C, $80
	.word $FFF0, $08, $18E, $80
martha_punch04_end:

martha_punch05:
	.word $FF80, $08, $190, $80
	.word $FF90, $08, $192, $80
	.word $FF90, $18, $194, $80
	.word $FFA0, $FFF8, $196, $80
	.word $FFA0, $08, $198, $80
	.word $FFA0, $18, $19A, $80
	.word $FFB0, $FFE8, $19C, $80
	.word $FFB0, $FFF8, $19E, $80
	.word $FFB0, $08, $1A0, $80
	.word $FFC0, $FFE8, $1A2, $80
	.word $FFC0, $FFF8, $1A4, $80
	.word $FFC0, $08, $1A6, $80
	.word $FFD0, $FFE8, $1A8, $80
	.word $FFD0, $FFF8, $1AA, $80
	.word $FFD0, $08, $1AC, $80
	.word $FFE0, $FFE8, $1AE, $80
	.word $FFE0, $FFF8, $1B0, $80
	.word $FFE0, $08, $1B2, $80
	.word $FFF0, $FFE8, $1B4, $80
	.word $FFF0, $FFF8, $1B6, $80
	.word $FFF0, $08, $1B8, $80
martha_punch05_end:

martha_punch06_ref04:
	.word $FFA0, $08, $166, $80
	.word $FFA0, $18, $168, $80
	.word $FFB0, $FFE8, $16A, $80
	.word $FFB0, $FFF8, $16C, $80
	.word $FFB0, $08, $16E, $80
	.word $FFB0, $18, $170, $80
	.word $FFB0, $28, $172, $80
	.word $FFC0, $FFF8, $174, $80
	.word $FFC0, $08, $176, $80
	.word $FFC0, $18, $178, $80
	.word $FFC0, $28, $17A, $80
	.word $FFD0, $FFE8, $17C, $80
	.word $FFD0, $FFF8, $17E, $80
	.word $FFD0, $08, $180, $80
	.word $FFD0, $18, $182, $80
	.word $FFE0, $FFE8, $184, $80
	.word $FFE0, $FFF8, $186, $80
	.word $FFE0, $08, $188, $80
	.word $FFF0, $FFE8, $18A, $80
	.word $FFF0, $FFF8, $18C, $80
	.word $FFF0, $08, $18E, $80
martha_punch06_ref04_end:

martha_punch07_ref03:
	.word $FFA0, $FFF8, $140, $80
	.word $FFA0, $08, $142, $80
	.word $FFB0, $FFE8, $144, $80
	.word $FFB0, $FFF8, $146, $80
	.word $FFB0, $08, $148, $80
	.word $FFC0, $FFE8, $14A, $80
	.word $FFC0, $FFF8, $14C, $80
	.word $FFC0, $08, $14E, $80
	.word $FFC0, $18, $150, $80
	.word $FFD0, $FFE8, $152, $80
	.word $FFD0, $FFF8, $154, $80
	.word $FFD0, $08, $156, $80
	.word $FFD0, $18, $158, $80
	.word $FFE0, $FFE8, $15A, $80
	.word $FFE0, $FFF8, $15C, $80
	.word $FFE0, $08, $15E, $80
	.word $FFF0, $FFE8, $160, $80
	.word $FFF0, $FFF8, $162, $80
	.word $FFF0, $08, $164, $80
martha_punch07_ref03_end:

