;#######################################################
;
; Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################

_set1_chr0:	.incbin "data/_set1_chr0.bin"	; 2944 bytes
_set1_chr1:	.incbin "data/_set1_chr1.bin"	; 2304 bytes
_set1_chr2:	.incbin "data/_set1_chr2.bin"	; 2432 bytes
_set1_chr3:	.incbin "data/_set1_chr3.bin"	; 2944 bytes
_set1_chr4:	.incbin "data/_set1_chr4.bin"	; 2560 bytes
_set1_chr5:	.incbin "data/_set1_chr5.bin"	; 2304 bytes
_set1_chr6:	.incbin "data/_set1_chr6.bin"	; 2560 bytes
_set1_chr7:	.incbin "data/_set1_chr7.bin"	; 3200 bytes
_set1_chr8:	.incbin "data/_set1_chr8.bin"	; 2176 bytes
_set1_chr9:	.incbin "data/_set1_chr9.bin"	; 3200 bytes

_set1_SG_arr:	
	.word 2944, _set1_chr0, bank(_set1_chr0)
	.word 2304, _set1_chr1, bank(_set1_chr1)
	.word 2432, _set1_chr2, bank(_set1_chr2)
	.word 2944, _set1_chr3, bank(_set1_chr3)
	.word 2560, _set1_chr4, bank(_set1_chr4)
	.word 2304, _set1_chr5, bank(_set1_chr5)
	.word 2560, _set1_chr6, bank(_set1_chr6)
	.word 3200, _set1_chr7, bank(_set1_chr7)
	.word 2176, _set1_chr8, bank(_set1_chr8)
	.word 3200, _set1_chr9, bank(_set1_chr9)


_set1_palette:
_set1_palette_slot0:
	.word $147, $C2, $81, $14B, $19D, $1B0, $170, $E9, $173, $F0, $1B5, $B0, $58, $133, $F2, $1B6
_set1_palette_end:

_set1_num_frames:
	.byte $0C
_set1_frames_data:
_mpwr_idle01_RIGHT_frame:
	.word _mpwr_idle01_RIGHT
	.byte bank(_mpwr_idle01_RIGHT)
	.word _mpwr_idle01_RIGHT_end - _mpwr_idle01_RIGHT	; data size
	.byte 6		; GFX bank index (chr6)
_mpwr_walk01_RIGHT_frame:
	.word _mpwr_walk01_RIGHT
	.byte bank(_mpwr_walk01_RIGHT)
	.word _mpwr_walk01_RIGHT_end - _mpwr_walk01_RIGHT
	.byte 0
_mpwr_walk02_RIGHT_frame:
	.word _mpwr_walk02_RIGHT
	.byte bank(_mpwr_walk02_RIGHT)
	.word _mpwr_walk02_RIGHT_end - _mpwr_walk02_RIGHT
	.byte 1
_mpwr_walk03_RIGHT_frame:
	.word _mpwr_walk03_RIGHT
	.byte bank(_mpwr_walk03_RIGHT)
	.word _mpwr_walk03_RIGHT_end - _mpwr_walk03_RIGHT
	.byte 2
_mpwr_walk04_RIGHT_frame:
	.word _mpwr_walk04_RIGHT
	.byte bank(_mpwr_walk04_RIGHT)
	.word _mpwr_walk04_RIGHT_end - _mpwr_walk04_RIGHT
	.byte 3
_mpwr_walk05_RIGHT_frame:
	.word _mpwr_walk05_RIGHT
	.byte bank(_mpwr_walk05_RIGHT)
	.word _mpwr_walk05_RIGHT_end - _mpwr_walk05_RIGHT
	.byte 4
_mpwr_walk06_RIGHT_frame:
	.word _mpwr_walk06_RIGHT
	.byte bank(_mpwr_walk06_RIGHT)
	.word _mpwr_walk06_RIGHT_end - _mpwr_walk06_RIGHT
	.byte 5
_mpwr_kick01_RIGHT_frame:
	.word _mpwr_kick01_RIGHT
	.byte bank(_mpwr_kick01_RIGHT)
	.word _mpwr_kick01_RIGHT_end - _mpwr_kick01_RIGHT
	.byte 7
_mpwr_kick02_RIGHT_frame:
	.word _mpwr_kick02_RIGHT
	.byte bank(_mpwr_kick02_RIGHT)
	.word _mpwr_kick02_RIGHT_end - _mpwr_kick02_RIGHT
	.byte 8
_mpwr_kick03_RIGHT_frame:
	.word _mpwr_kick03_RIGHT
	.byte bank(_mpwr_kick03_RIGHT)
	.word _mpwr_kick03_RIGHT_end - _mpwr_kick03_RIGHT
	.byte 9
_mpwr_kick04_ref02_RIGHT_frame:
	.word _mpwr_kick04_ref02_RIGHT
	.byte bank(_mpwr_kick04_ref02_RIGHT)
	.word _mpwr_kick04_ref02_RIGHT_end - _mpwr_kick04_ref02_RIGHT
	.byte 8
_mpwr_kick05_ref01_RIGHT_frame:
	.word _mpwr_kick05_ref01_RIGHT
	.byte bank(_mpwr_kick05_ref01_RIGHT)
	.word _mpwr_kick05_ref01_RIGHT_end - _mpwr_kick05_ref01_RIGHT
	.byte 7


	; #1: Y pos, #2: X pos, #3: CHR index, #4: CHR desc

_mpwr_idle01_RIGHT:
	.word $FFCE, $FFFB, $100, $1980
	.word $FF9E, $FFFB, $108, $980
	.word $FFAE, $FFFF, $10C, $980
	.word $FFBE, $FFFC, $110, $980
	.word $FFEE, $FFFB, $114, $980
	.word $FFEE, $FFDB, $118, $980
	.word $FF9E, $FFEB, $11C, $880
	.word $FFAE, $FFEF, $11E, $880
	.word $FFBE, $FFEC, $120, $880
	.word $FFCE, $FFEB, $122, $880
	.word $FFDE, $FFEB, $124, $880
	.word $FFFE, $FFE4, $126, $880
_mpwr_idle01_RIGHT_end:

_mpwr_walk01_RIGHT:
	.word $FF97, $FFF3, $100, $980
	.word $FFA7, $08, $104, $980
	.word $FFA7, $FFE8, $108, $980
	.word $FFB7, $07, $10C, $980
	.word $FFB7, $FFE7, $110, $980
	.word $FFC7, $FFED, $114, $980
	.word $FFD7, $FFF1, $118, $980
	.word $FFE7, $FFD9, $11C, $980
	.word $FFF7, $FFF5, $120, $980
	.word $FF97, $FFE3, $124, $880
	.word $FFA7, $FFD8, $126, $880
	.word $FFD7, $FFE1, $128, $880
	.word $FFE7, $FFFF, $12A, $880
	.word $FFF7, $FFDC, $12C, $880
_mpwr_walk01_RIGHT_end:

_mpwr_walk02_RIGHT:
	.word $FF96, $FFF2, $100, $1980
	.word $FFB6, $FFEF, $108, $980
	.word $FFC6, $FFE9, $10C, $980
	.word $FFD6, $FFEC, $110, $980
	.word $FFE6, $FFEA, $114, $980
	.word $FFF6, $FFEE, $118, $980
	.word $FFA6, $12, $11C, $880
	.word $FFD6, $FFDC, $11E, $880
	.word $FFE6, $FFDA, $120, $880
	.word $FFF6, $FFDE, $122, $880
_mpwr_walk02_RIGHT_end:

_mpwr_walk03_RIGHT:
	.word $FFC3, $FFFA, $100, $1980
	.word $FF93, $FFF2, $108, $980
	.word $FFA3, $00, $10C, $980
	.word $FFB3, $FFF2, $110, $980
	.word $FFE3, $FFF6, $114, $980
	.word $FFF3, $FFD7, $118, $980
	.word $FFA3, $FFF0, $11C, $880
	.word $FFB3, $FFE2, $11E, $880
	.word $FFC3, $FFEA, $120, $880
	.word $FFD3, $FFEA, $122, $880
	.word $FFE3, $FFE6, $124, $880
_mpwr_walk03_RIGHT_end:

_mpwr_walk04_RIGHT:
	.word $FF97, $FFF2, $100, $1980
	.word $FFD7, $FFD9, $108, $1980
	.word $FFE7, $FFFD, $110, $1980
	.word $FFB7, $FFFC, $118, $980
	.word $FFC7, $FFF6, $11C, $980
	.word $FFD7, $FFF9, $120, $980
	.word $FFA7, $12, $124, $880
	.word $FFA7, $FFE2, $126, $880
	.word $FFB7, $FFEC, $128, $880
	.word $FFC7, $FFE6, $12A, $880
	.word $FFF7, $FFD7, $12C, $880
_mpwr_walk04_RIGHT_end:

_mpwr_walk05_RIGHT:
	.word $FFBA, $FFF2, $100, $1980
	.word $FF9A, $FFF2, $108, $980
	.word $FFAA, $FFFE, $10C, $980
	.word $FFDA, $FFF3, $110, $980
	.word $FFEA, $FFF1, $114, $980
	.word $FFFA, $FFF2, $118, $980
	.word $FFAA, $FFEE, $11C, $880
	.word $FFBA, $FFE2, $11E, $880
	.word $FFCA, $FFE2, $120, $880
	.word $FFDA, $FFE3, $122, $880
	.word $FFEA, $FFE1, $124, $880
	.word $FFFA, $FFDA, $126, $880
_mpwr_walk05_RIGHT_end:

_mpwr_walk06_RIGHT:
	.word $FF98, $FFF2, $100, $1980
	.word $FFC8, $FFF2, $108, $1980
	.word $FFB8, $FFF0, $110, $980
	.word $FFE8, $FFEE, $114, $980
	.word $FFF8, $FFE0, $118, $980
	.word $FFA8, $12, $11C, $880
	.word $FFA8, $FFE2, $11E, $880
	.word $FFB8, $FFE0, $120, $880
	.word $FFC8, $FFE2, $122, $880
_mpwr_walk06_RIGHT_end:

_mpwr_kick01_RIGHT:
	.word $FFE8, $FFFB, $100, $1980
	.word $FF98, $05, $108, $980
	.word $FF98, $FFE5, $10C, $980
	.word $FFA8, $08, $110, $980
	.word $FFA8, $FFE8, $114, $980
	.word $FFB8, $FFF6, $118, $980
	.word $FFC8, $FFFC, $11C, $980
	.word $FFD8, $FFFF, $120, $980
	.word $FFD8, $FFDF, $124, $980
	.word $FFE8, $FFDB, $128, $980
	.word $FFB8, $17, $12C, $880
	.word $FFC8, $FFEC, $12E, $880
	.word $FFF8, $FFE1, $130, $880
_mpwr_kick01_RIGHT_end:

_mpwr_kick02_RIGHT:
	.word $FFD3, $00, $100, $1980
	.word $FF93, $FFED, $108, $980
	.word $FFA3, $FFFE, $10C, $980
	.word $FFB3, $FFF7, $110, $980
	.word $FFC3, $FFFD, $114, $980
	.word $FFF3, $FFFB, $118, $980
	.word $FFA3, $FFEE, $11C, $880
	.word $FFD3, $FFF0, $11E, $880
	.word $FFE3, $FFF0, $120, $880
_mpwr_kick02_RIGHT_end:

_mpwr_kick03_RIGHT:
	.word $FFAA, $14, $100, $1980
	.word $FFAA, $FFF4, $108, $1980
	.word $FFCA, $03, $110, $1980
	.word $FF9A, $08, $118, $980
	.word $FFCA, $FFE3, $11C, $980
	.word $FFEA, $FFFE, $120, $980
	.word $FFFA, $FFFB, $124, $980
	.word $FF9A, $33, $128, $880
	.word $FF9A, $FFF8, $12A, $880
	.word $FFAA, $34, $12C, $880
	.word $FFAA, $FFE4, $12E, $880
	.word $FFBA, $FFE4, $130, $880
_mpwr_kick03_RIGHT_end:

_mpwr_kick04_ref02_RIGHT:
	.word $FFD3, $00, $100, $1980
	.word $FF93, $FFED, $108, $980
	.word $FFA3, $FFFE, $10C, $980
	.word $FFB3, $FFF7, $110, $980
	.word $FFC3, $FFFD, $114, $980
	.word $FFF3, $FFFB, $118, $980
	.word $FFA3, $FFEE, $11C, $880
	.word $FFD3, $FFF0, $11E, $880
	.word $FFE3, $FFF0, $120, $880
_mpwr_kick04_ref02_RIGHT_end:

_mpwr_kick05_ref01_RIGHT:
	.word $FFE8, $FFFB, $100, $1980
	.word $FF98, $05, $108, $980
	.word $FF98, $FFE5, $10C, $980
	.word $FFA8, $08, $110, $980
	.word $FFA8, $FFE8, $114, $980
	.word $FFB8, $FFF6, $118, $980
	.word $FFC8, $FFFC, $11C, $980
	.word $FFD8, $FFFF, $120, $980
	.word $FFD8, $FFDF, $124, $980
	.word $FFE8, $FFDB, $128, $980
	.word $FFB8, $17, $12C, $880
	.word $FFC8, $FFEC, $12E, $880
	.word $FFF8, $FFE1, $130, $880
_mpwr_kick05_ref01_RIGHT_end:

