;#######################################################
;
; Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################

_set3_chr0:	.incbin "data/_set3_chr0.bin"	; 2944 bytes
_set3_chr1:	.incbin "data/_set3_chr1.bin"	; 2304 bytes
_set3_chr2:	.incbin "data/_set3_chr2.bin"	; 2432 bytes
_set3_chr3:	.incbin "data/_set3_chr3.bin"	; 2944 bytes
_set3_chr4:	.incbin "data/_set3_chr4.bin"	; 2560 bytes
_set3_chr5:	.incbin "data/_set3_chr5.bin"	; 2304 bytes
_set3_chr6:	.incbin "data/_set3_chr6.bin"	; 2560 bytes
_set3_chr7:	.incbin "data/_set3_chr7.bin"	; 3200 bytes
_set3_chr8:	.incbin "data/_set3_chr8.bin"	; 2176 bytes
_set3_chr9:	.incbin "data/_set3_chr9.bin"	; 3200 bytes

_set3_SG_arr:	
	.word 2944, _set3_chr0, bank(_set3_chr0)
	.word 2304, _set3_chr1, bank(_set3_chr1)
	.word 2432, _set3_chr2, bank(_set3_chr2)
	.word 2944, _set3_chr3, bank(_set3_chr3)
	.word 2560, _set3_chr4, bank(_set3_chr4)
	.word 2304, _set3_chr5, bank(_set3_chr5)
	.word 2560, _set3_chr6, bank(_set3_chr6)
	.word 3200, _set3_chr7, bank(_set3_chr7)
	.word 2176, _set3_chr8, bank(_set3_chr8)
	.word 3200, _set3_chr9, bank(_set3_chr9)


_set3_palette:
_set3_palette_slot0:
	.word $147, $87, $44, $107, $14D, $1B0, $170, $E9, $173, $F0, $1B5, $B0, $58, $133, $F2, $1B6
_set3_palette_end:

_set3_num_frames:
	.byte $0C
_set3_frames_data:
_mpwr_idle01_LEFT_frame:
	.word _mpwr_idle01_LEFT
	.byte bank(_mpwr_idle01_LEFT)
_mpwr_walk01_LEFT_frame:
	.word _mpwr_walk01_LEFT
	.byte bank(_mpwr_walk01_LEFT)
_mpwr_walk02_LEFT_frame:
	.word _mpwr_walk02_LEFT
	.byte bank(_mpwr_walk02_LEFT)
_mpwr_walk03_LEFT_frame:
	.word _mpwr_walk03_LEFT
	.byte bank(_mpwr_walk03_LEFT)
_mpwr_walk04_LEFT_frame:
	.word _mpwr_walk04_LEFT
	.byte bank(_mpwr_walk04_LEFT)
_mpwr_walk05_LEFT_frame:
	.word _mpwr_walk05_LEFT
	.byte bank(_mpwr_walk05_LEFT)
_mpwr_walk06_LEFT_frame:
	.word _mpwr_walk06_LEFT
	.byte bank(_mpwr_walk06_LEFT)
_mpwr_kick01_LEFT_frame:
	.word _mpwr_kick01_LEFT
	.byte bank(_mpwr_kick01_LEFT)
_mpwr_kick02_LEFT_frame:
	.word _mpwr_kick02_LEFT
	.byte bank(_mpwr_kick02_LEFT)
_mpwr_kick03_LEFT_frame:
	.word _mpwr_kick03_LEFT
	.byte bank(_mpwr_kick03_LEFT)
_mpwr_kick04_ref02_LEFT_frame:
	.word _mpwr_kick04_ref02_LEFT
	.byte bank(_mpwr_kick04_ref02_LEFT)
_mpwr_kick05_ref01_LEFT_frame:
	.word _mpwr_kick05_ref01_LEFT
	.byte bank(_mpwr_kick05_ref01_LEFT)


	; #1: Y pos, #2: X pos, #3: CHR index, #4: CHR desc

_mpwr_idle01_LEFT:
	.word _mpwr_idle01_LEFT_end - _mpwr_idle01_LEFT - 3	; data size
	.byte 6		; GFX bank index (chr6)

	.word $FFCE, $FFE5, $200, $1182
	.word $FF9E, $FFE5, $208, $182
	.word $FFAE, $FFE1, $20C, $182
	.word $FFBE, $FFE4, $210, $182
	.word $FFEE, $FFE5, $214, $182
	.word $FFEE, $05, $218, $182
	.word $FF9E, $05, $21C, $82
	.word $FFAE, $01, $21E, $82
	.word $FFBE, $04, $220, $82
	.word $FFCE, $05, $222, $82
	.word $FFDE, $05, $224, $82
	.word $FFFE, $0C, $226, $82
_mpwr_idle01_LEFT_end:

_mpwr_walk01_LEFT:
	.word _mpwr_walk01_LEFT_end - _mpwr_walk01_LEFT - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $FF97, $FFED, $200, $182
	.word $FFA7, $FFD8, $204, $182
	.word $FFA7, $FFF8, $208, $182
	.word $FFB7, $FFD9, $20C, $182
	.word $FFB7, $FFF9, $210, $182
	.word $FFC7, $FFF3, $214, $182
	.word $FFD7, $FFEF, $218, $182
	.word $FFE7, $07, $21C, $182
	.word $FFF7, $FFEB, $220, $182
	.word $FF97, $0D, $224, $82
	.word $FFA7, $18, $226, $82
	.word $FFD7, $0F, $228, $82
	.word $FFE7, $FFF1, $22A, $82
	.word $FFF7, $14, $22C, $82
_mpwr_walk01_LEFT_end:

_mpwr_walk02_LEFT:
	.word _mpwr_walk02_LEFT_end - _mpwr_walk02_LEFT - 3	; data size
	.byte 1		; GFX bank index (chr1)

	.word $FF96, $FFEE, $200, $1182
	.word $FFB6, $FFF1, $208, $182
	.word $FFC6, $FFF7, $20C, $182
	.word $FFD6, $FFF4, $210, $182
	.word $FFE6, $FFF6, $214, $182
	.word $FFF6, $FFF2, $218, $182
	.word $FFA6, $FFDE, $21C, $82
	.word $FFD6, $14, $21E, $82
	.word $FFE6, $16, $220, $82
	.word $FFF6, $12, $222, $82
_mpwr_walk02_LEFT_end:

_mpwr_walk03_LEFT:
	.word _mpwr_walk03_LEFT_end - _mpwr_walk03_LEFT - 3	; data size
	.byte 2		; GFX bank index (chr2)

	.word $FFC3, $FFE6, $200, $1182
	.word $FF93, $FFEE, $208, $182
	.word $FFA3, $FFE0, $20C, $182
	.word $FFB3, $FFEE, $210, $182
	.word $FFE3, $FFEA, $214, $182
	.word $FFF3, $09, $218, $182
	.word $FFA3, $00, $21C, $82
	.word $FFB3, $0E, $21E, $82
	.word $FFC3, $06, $220, $82
	.word $FFD3, $06, $222, $82
	.word $FFE3, $0A, $224, $82
_mpwr_walk03_LEFT_end:

_mpwr_walk04_LEFT:
	.word _mpwr_walk04_LEFT_end - _mpwr_walk04_LEFT - 3	; data size
	.byte 3		; GFX bank index (chr3)

	.word $FF97, $FFEE, $200, $1182
	.word $FFD7, $07, $208, $1182
	.word $FFE7, $FFE3, $210, $1182
	.word $FFB7, $FFE4, $218, $182
	.word $FFC7, $FFEA, $21C, $182
	.word $FFD7, $FFE7, $220, $182
	.word $FFA7, $FFDE, $224, $82
	.word $FFA7, $0E, $226, $82
	.word $FFB7, $04, $228, $82
	.word $FFC7, $0A, $22A, $82
	.word $FFF7, $19, $22C, $82
_mpwr_walk04_LEFT_end:

_mpwr_walk05_LEFT:
	.word _mpwr_walk05_LEFT_end - _mpwr_walk05_LEFT - 3	; data size
	.byte 4		; GFX bank index (chr4)

	.word $FFBA, $FFEE, $200, $1182
	.word $FF9A, $FFEE, $208, $182
	.word $FFAA, $FFE2, $20C, $182
	.word $FFDA, $FFED, $210, $182
	.word $FFEA, $FFEF, $214, $182
	.word $FFFA, $FFEE, $218, $182
	.word $FFAA, $02, $21C, $82
	.word $FFBA, $0E, $21E, $82
	.word $FFCA, $0E, $220, $82
	.word $FFDA, $0D, $222, $82
	.word $FFEA, $0F, $224, $82
	.word $FFFA, $16, $226, $82
_mpwr_walk05_LEFT_end:

_mpwr_walk06_LEFT:
	.word _mpwr_walk06_LEFT_end - _mpwr_walk06_LEFT - 3	; data size
	.byte 5		; GFX bank index (chr5)

	.word $FF98, $FFEE, $200, $1182
	.word $FFC8, $FFEE, $208, $1182
	.word $FFB8, $FFF0, $210, $182
	.word $FFE8, $FFF2, $214, $182
	.word $FFF8, $00, $218, $182
	.word $FFA8, $FFDE, $21C, $82
	.word $FFA8, $0E, $21E, $82
	.word $FFB8, $10, $220, $82
	.word $FFC8, $0E, $222, $82
_mpwr_walk06_LEFT_end:

_mpwr_kick01_LEFT:
	.word _mpwr_kick01_LEFT_end - _mpwr_kick01_LEFT - 3	; data size
	.byte 7		; GFX bank index (chr7)

	.word $FFE8, $FFE5, $200, $1182
	.word $FF98, $FFDB, $208, $182
	.word $FF98, $FFFB, $20C, $182
	.word $FFA8, $FFD8, $210, $182
	.word $FFA8, $FFF8, $214, $182
	.word $FFB8, $FFEA, $218, $182
	.word $FFC8, $FFE4, $21C, $182
	.word $FFD8, $FFE1, $220, $182
	.word $FFD8, $01, $224, $182
	.word $FFE8, $05, $228, $182
	.word $FFB8, $FFD9, $22C, $82
	.word $FFC8, $04, $22E, $82
	.word $FFF8, $0F, $230, $82
_mpwr_kick01_LEFT_end:

_mpwr_kick02_LEFT:
	.word _mpwr_kick02_LEFT_end - _mpwr_kick02_LEFT - 3	; data size
	.byte 8		; GFX bank index (chr8)

	.word $FFD3, $FFE0, $200, $1182
	.word $FF93, $FFF3, $208, $182
	.word $FFA3, $FFE2, $20C, $182
	.word $FFB3, $FFE9, $210, $182
	.word $FFC3, $FFE3, $214, $182
	.word $FFF3, $FFE5, $218, $182
	.word $FFA3, $02, $21C, $82
	.word $FFD3, $00, $21E, $82
	.word $FFE3, $00, $220, $82
_mpwr_kick02_LEFT_end:

_mpwr_kick03_LEFT:
	.word _mpwr_kick03_LEFT_end - _mpwr_kick03_LEFT - 3	; data size
	.byte 9		; GFX bank index (chr9)

	.word $FFAA, $FFCC, $200, $1182
	.word $FFAA, $FFEC, $208, $1182
	.word $FFCA, $FFDD, $210, $1182
	.word $FF9A, $FFD8, $218, $182
	.word $FFCA, $FFFD, $21C, $182
	.word $FFEA, $FFE2, $220, $182
	.word $FFFA, $FFE5, $224, $182
	.word $FF9A, $FFBD, $228, $82
	.word $FF9A, $FFF8, $22A, $82
	.word $FFAA, $FFBC, $22C, $82
	.word $FFAA, $0C, $22E, $82
	.word $FFBA, $0C, $230, $82
_mpwr_kick03_LEFT_end:

_mpwr_kick04_ref02_LEFT:
	.word _mpwr_kick04_ref02_LEFT_end - _mpwr_kick04_ref02_LEFT - 3	; data size
	.byte 8		; GFX bank index (chr8)

	.word $FFD3, $FFE0, $200, $1182
	.word $FF93, $FFF3, $208, $182
	.word $FFA3, $FFE2, $20C, $182
	.word $FFB3, $FFE9, $210, $182
	.word $FFC3, $FFE3, $214, $182
	.word $FFF3, $FFE5, $218, $182
	.word $FFA3, $02, $21C, $82
	.word $FFD3, $00, $21E, $82
	.word $FFE3, $00, $220, $82
_mpwr_kick04_ref02_LEFT_end:

_mpwr_kick05_ref01_LEFT:
	.word _mpwr_kick05_ref01_LEFT_end - _mpwr_kick05_ref01_LEFT - 3	; data size
	.byte 7		; GFX bank index (chr7)

	.word $FFE8, $FFE5, $200, $1182
	.word $FF98, $FFDB, $208, $182
	.word $FF98, $FFFB, $20C, $182
	.word $FFA8, $FFD8, $210, $182
	.word $FFA8, $FFF8, $214, $182
	.word $FFB8, $FFEA, $218, $182
	.word $FFC8, $FFE4, $21C, $182
	.word $FFD8, $FFE1, $220, $182
	.word $FFD8, $01, $224, $182
	.word $FFE8, $05, $228, $182
	.word $FFB8, $FFD9, $22C, $82
	.word $FFC8, $04, $22E, $82
	.word $FFF8, $0F, $230, $82
_mpwr_kick05_ref01_LEFT_end:

