;#######################################################
;
; Generated by MAPeD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################


; *** GLOBAL DATA ***

_chr0:	.incbin "_tilemap__chr0.bin"		; (28512)
_chr1:	.incbin "_tilemap__chr1.bin"		; (28704)
_chr2:	.incbin "_tilemap__chr2.bin"		; (28704)
_chr3:	.incbin "_tilemap__chr3.bin"		; (28704)


_mpd_CHRs_size:
	.word 28512	; (_chr0)
	.word 28704	; (_chr1)
	.word 28704	; (_chr2)
	.word 28704	; (_chr3)

_mpd_Props:	.incbin "_tilemap_Props.bin"	; (3600) block properties array of all exported data banks ( 4 bytes per block )

_mpd_PropsOffs:
	.word 0	; (chr0)
	.word 900	; (chr1)
	.word 1800	; (chr2)
	.word 2700	; (chr3)
	.word 3600	; data end

_mpd_Tiles:	.incbin "_tilemap_Tiles.bin"	; (896) 4x4 tiles array of all exported data banks ( 4 bytes per tile )

_mpd_TilesOffs:
	.word 0	; (chr0)
	.word 224	; (chr1)
	.word 448	; (chr2)
	.word 672	; (chr3)

_mpd_BlocksOffs:
	.word 0	; (chr0)
	.word 1800	; (chr1)
	.word 3600	; (chr2)
	.word 5400	; (chr3)

_mpd_VDCScr:	.incbin "_tilemap_VDCScr.bin"	; (7168) VDC-ready data array for each screen (1792 bytes per screen)
_mpd_TilesScr:	.incbin "_tilemap_TilesScr.bin"	; (224) 4x4 tiles array for each screen ( 56 bytes per screen \ 1 byte per tile )
_mpd_Plts:	.incbin "_tilemap_Plts.bin"	; (2048) palettes array of all exported data banks ( data offset = chr_id * 512 )
