//############################################################
//
// Generated by MAPeD-PCE (x64) Copyright 2017-2023 0x8BitDev
//
//############################################################


#incasm( "tilemap.asm" )

// export options:
//	- tiles 4x4/(columns)
//	- properties per CHR
//	- mode: static screens
//	- layout: adjacent screen indices (no marks)
//	- no entities


/* exported data flags: */

#define FLAG_TILES2X2                 0
#define FLAG_TILES4X4                 1
#define FLAG_RLE                      0
#define FLAG_DIR_COLUMNS              1
#define FLAG_DIR_ROWS                 0
#define FLAG_MODE_MULTIDIR_SCROLL     0
#define FLAG_MODE_BIDIR_SCROLL        0
#define FLAG_MODE_BIDIR_STAT_SCR      0
#define FLAG_MODE_STAT_SCR            1
#define FLAG_ENTITIES                 0
#define FLAG_ENTITY_SCR_COORDS        0
#define FLAG_ENTITY_MAP_COORS         0
#define FLAG_ENTITY_SORTING_OFF       0
#define FLAG_ENTITY_SORTING_LT_RT     0
#define FLAG_ENTITY_SORTING_BTM_TP    0
#define FLAG_LAYOUT_ADJ_SCR           0
#define FLAG_LAYOUT_ADJ_SCR_INDS      1
#define FLAG_LAYOUT_MATRIX            0
#define FLAG_MARKS                    0
#define FLAG_PROP_ID_PER_BLOCK        0
#define FLAG_PROP_ID_PER_CHR          1

#define MAPS_CNT	4

#define BAT_INDEX	0
#define CHRS_OFFSET	32	// first CHR index from the beginning of VRAM

#define SCR_BLOCKS2x2_WIDTH	16	// number of screen blocks (2x2) in width
#define SCR_BLOCKS2x2_HEIGHT	14	// number of screen blocks (2x2) in height

#define ScrTilesWidth	8	// number of screen tiles (4x4) in width
#define ScrTilesHeight	7	// number of screen tiles (4x4) in height

#define ScrPixelsWidth	256	// screen width in pixels
#define ScrPixelsHeight	224	// screen height in pixels

#define ScrGfxDataSize	1792	// static screen data size in bytes


/* screen data */

typedef struct
{
#if	FLAG_MODE_BIDIR_SCROLL + FLAG_MODE_STAT_SCR
	u8	chr_id;
#endif
#if	FLAG_MARKS
	//bits: 7-4 - bit mask of user defined adjacent screens ( Down(7)-Right(6)-Up(5)-Left(4) ); 3-0 - screen property
	u8	marks;
#endif
#if	FLAG_MODE_STAT_SCR
	u16	VDC_data_offset;
#endif
#if	FLAG_MODE_BIDIR_SCROLL + FLAG_MODE_STAT_SCR
	u8	scr_ind;
#endif
#if	FLAG_LAYOUT_ADJ_SCR
	// adjacent screen pointers
	u16	adj_scr[4];
#endif
#if	FLAG_LAYOUT_ADJ_SCR_INDS
	u8	adj_scr[4];
#endif
#if	FLAG_ENTITIES
	u8	ents_cnt;
#endif
} mpd_SCREEN;

extern u16*	chr0;
extern u16*	chr1;
extern u16*	chr2;
extern u16*	chr3;

extern u16	mpd_CHRs[];
extern u16*	mpd_CHRs_size;
extern u8*	mpd_Props;
extern u16*	mpd_PropsOffs;
extern u8*	mpd_Tiles;
extern u16*	mpd_TilesOffs;
extern u16*	mpd_BlocksOffs;
extern u16*	mpd_VDCScr;	// VDC-ready data array for each screen
extern u8*	mpd_TilesScr;
extern u16*	mpd_Plts;


extern mpd_SCREEN** mpd_LayoutsArr[];
extern mpd_SCREEN** mpd_LayoutsScrArr[];

#define	ENT_MAX_PROPS_CNT	0
#define	MAX_TILE_PROPS_SIZE	900	// largest array of tile properties
