;#######################################################
;
; Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################

;_chin_pink_chr0:	.incbin "data/_chin_pink_chr0.bin"	; 1920 bytes
;_chin_pink_chr1:	.incbin "data/_chin_pink_chr1.bin"	; 1664 bytes
;_chin_pink_chr2:	.incbin "data/_chin_pink_chr2.bin"	; 1536 bytes
;_chin_pink_chr3:	.incbin "data/_chin_pink_chr3.bin"	; 1536 bytes
;_chin_pink_chr4:	.incbin "data/_chin_pink_chr4.bin"	; 1536 bytes

;_chin_pink_SG_arr:	
;	.word 1920, _chin_pink_chr0, bank(_chin_pink_chr0)
;	.word 1664, _chin_pink_chr1, bank(_chin_pink_chr1)
;	.word 1536, _chin_pink_chr2, bank(_chin_pink_chr2)
;	.word 1536, _chin_pink_chr3, bank(_chin_pink_chr3)
;	.word 1536, _chin_pink_chr4, bank(_chin_pink_chr4)


_chin_pink_palette:
_chin_pink_palette_slot0:
	.word $1C0, $1B, $24, $B6, $FE, $12E, $DB, $E0, $98, $EA, $1B5, $133, $A0, $1B6, $92, $00
_chin_pink_palette_end:

_chin_pink_num_frames:
	.byte $0A
_chin_pink_frames_data:
_chin_pink_idle01_RIGHT_frame:
	.word _chin_pink_idle01_RIGHT
	.byte bank(_chin_pink_idle01_RIGHT)
	.word _chin_pink_idle01_RIGHT_end - _chin_pink_idle01_RIGHT	; data size
	.byte 0		; GFX bank index (chr0)
_chin_pink_walk01_RIGHT_frame:
	.word _chin_pink_walk01_RIGHT
	.byte bank(_chin_pink_walk01_RIGHT)
	.word _chin_pink_walk01_RIGHT_end - _chin_pink_walk01_RIGHT
	.byte 1
_chin_pink_walk02_RIGHT_frame:
	.word _chin_pink_walk02_RIGHT
	.byte bank(_chin_pink_walk02_RIGHT)
	.word _chin_pink_walk02_RIGHT_end - _chin_pink_walk02_RIGHT
	.byte 2
_chin_pink_walk03_RIGHT_frame:
	.word _chin_pink_walk03_RIGHT
	.byte bank(_chin_pink_walk03_RIGHT)
	.word _chin_pink_walk03_RIGHT_end - _chin_pink_walk03_RIGHT
	.byte 3
_chin_pink_walk04_RIGHT_frame:
	.word _chin_pink_walk04_RIGHT
	.byte bank(_chin_pink_walk04_RIGHT)
	.word _chin_pink_walk04_RIGHT_end - _chin_pink_walk04_RIGHT
	.byte 4
_chin_pink_idle01_LEFT_frame:
	.word _chin_pink_idle01_LEFT
	.byte bank(_chin_pink_idle01_LEFT)
	.word _chin_pink_idle01_LEFT_end - _chin_pink_idle01_LEFT
	.byte 0
_chin_pink_walk01_LEFT_frame:
	.word _chin_pink_walk01_LEFT
	.byte bank(_chin_pink_walk01_LEFT)
	.word _chin_pink_walk01_LEFT_end - _chin_pink_walk01_LEFT
	.byte 1
_chin_pink_walk02_LEFT_frame:
	.word _chin_pink_walk02_LEFT
	.byte bank(_chin_pink_walk02_LEFT)
	.word _chin_pink_walk02_LEFT_end - _chin_pink_walk02_LEFT
	.byte 2
_chin_pink_walk03_LEFT_frame:
	.word _chin_pink_walk03_LEFT
	.byte bank(_chin_pink_walk03_LEFT)
	.word _chin_pink_walk03_LEFT_end - _chin_pink_walk03_LEFT
	.byte 3
_chin_pink_walk04_LEFT_frame:
	.word _chin_pink_walk04_LEFT
	.byte bank(_chin_pink_walk04_LEFT)
	.word _chin_pink_walk04_LEFT_end - _chin_pink_walk04_LEFT
	.byte 4


	; #1: Y pos, #2: X pos, #3: CHR index, #4: CHR desc

_chin_pink_idle01_RIGHT:
	.word $FFB0, $FFE9, $100, $81
	.word $FFB0, $FFF9, $102, $81
	.word $FFB0, $09, $104, $81
	.word $FFC0, $FFE9, $106, $81
	.word $FFC0, $FFF9, $108, $81
	.word $FFC0, $09, $10A, $81
	.word $FFD0, $FFE9, $10C, $81
	.word $FFD0, $FFF9, $10E, $81
	.word $FFD0, $09, $110, $81
	.word $FFE0, $FFE9, $112, $81
	.word $FFE0, $FFF9, $114, $81
	.word $FFE0, $09, $116, $81
	.word $FFF0, $FFE9, $118, $81
	.word $FFF0, $FFF9, $11A, $81
	.word $FFF0, $09, $11C, $81
_chin_pink_idle01_RIGHT_end:

_chin_pink_walk01_RIGHT:
	.word $FFB0, $FFEC, $100, $81
	.word $FFB0, $FFFC, $102, $81
	.word $FFC0, $FFEC, $104, $81
	.word $FFC0, $FFFC, $106, $81
	.word $FFC0, $0C, $108, $81
	.word $FFD0, $FFEC, $10A, $81
	.word $FFD0, $FFFC, $10C, $81
	.word $FFD0, $0C, $10E, $81
	.word $FFE0, $FFEC, $110, $81
	.word $FFE0, $FFFC, $112, $81
	.word $FFF0, $FFEC, $114, $81
	.word $FFF0, $FFFC, $116, $81
	.word $FFF0, $0C, $118, $81
_chin_pink_walk01_RIGHT_end:

_chin_pink_walk02_RIGHT:
	.word $FFB0, $FFEC, $100, $81
	.word $FFB0, $FFFC, $102, $81
	.word $FFC0, $FFEC, $104, $81
	.word $FFC0, $FFFC, $106, $81
	.word $FFC0, $0C, $108, $81
	.word $FFD0, $FFEC, $10A, $81
	.word $FFD0, $FFFC, $10C, $81
	.word $FFD0, $0C, $10E, $81
	.word $FFE0, $FFEC, $110, $81
	.word $FFE0, $FFFC, $112, $81
	.word $FFF0, $FFEC, $114, $81
	.word $FFF0, $FFFC, $116, $81
_chin_pink_walk02_RIGHT_end:

_chin_pink_walk03_RIGHT:
	.word $FFB0, $FFEC, $100, $81
	.word $FFB0, $FFFC, $102, $81
	.word $FFC0, $FFEC, $104, $81
	.word $FFC0, $FFFC, $106, $81
	.word $FFC0, $0C, $108, $81
	.word $FFD0, $FFEC, $10A, $81
	.word $FFD0, $FFFC, $10C, $81
	.word $FFD0, $0C, $10E, $81
	.word $FFE0, $FFEC, $110, $81
	.word $FFE0, $FFFC, $112, $81
	.word $FFF0, $FFEC, $114, $81
	.word $FFF0, $FFFC, $116, $81
_chin_pink_walk03_RIGHT_end:

_chin_pink_walk04_RIGHT:
	.word $FFB0, $FFEC, $100, $81
	.word $FFB0, $FFFC, $102, $81
	.word $FFC0, $FFEC, $104, $81
	.word $FFC0, $FFFC, $106, $81
	.word $FFC0, $0C, $108, $81
	.word $FFD0, $FFEC, $10A, $81
	.word $FFD0, $FFFC, $10C, $81
	.word $FFD0, $0C, $10E, $81
	.word $FFE0, $FFEC, $110, $81
	.word $FFE0, $FFFC, $112, $81
	.word $FFF0, $FFEC, $114, $81
	.word $FFF0, $FFFC, $116, $81
_chin_pink_walk04_RIGHT_end:

_chin_pink_idle01_LEFT:
	.word $FFB0, $07, $100, $881
	.word $FFB0, $FFF7, $102, $881
	.word $FFB0, $FFE7, $104, $881
	.word $FFC0, $07, $106, $881
	.word $FFC0, $FFF7, $108, $881
	.word $FFC0, $FFE7, $10A, $881
	.word $FFD0, $07, $10C, $881
	.word $FFD0, $FFF7, $10E, $881
	.word $FFD0, $FFE7, $110, $881
	.word $FFE0, $07, $112, $881
	.word $FFE0, $FFF7, $114, $881
	.word $FFE0, $FFE7, $116, $881
	.word $FFF0, $07, $118, $881
	.word $FFF0, $FFF7, $11A, $881
	.word $FFF0, $FFE7, $11C, $881
_chin_pink_idle01_LEFT_end:

_chin_pink_walk01_LEFT:
	.word $FFB0, $04, $100, $881
	.word $FFB0, $FFF4, $102, $881
	.word $FFC0, $04, $104, $881
	.word $FFC0, $FFF4, $106, $881
	.word $FFC0, $FFE4, $108, $881
	.word $FFD0, $04, $10A, $881
	.word $FFD0, $FFF4, $10C, $881
	.word $FFD0, $FFE4, $10E, $881
	.word $FFE0, $04, $110, $881
	.word $FFE0, $FFF4, $112, $881
	.word $FFF0, $04, $114, $881
	.word $FFF0, $FFF4, $116, $881
	.word $FFF0, $FFE4, $118, $881
_chin_pink_walk01_LEFT_end:

_chin_pink_walk02_LEFT:
	.word $FFB0, $04, $100, $881
	.word $FFB0, $FFF4, $102, $881
	.word $FFC0, $04, $104, $881
	.word $FFC0, $FFF4, $106, $881
	.word $FFC0, $FFE4, $108, $881
	.word $FFD0, $04, $10A, $881
	.word $FFD0, $FFF4, $10C, $881
	.word $FFD0, $FFE4, $10E, $881
	.word $FFE0, $04, $110, $881
	.word $FFE0, $FFF4, $112, $881
	.word $FFF0, $04, $114, $881
	.word $FFF0, $FFF4, $116, $881
_chin_pink_walk02_LEFT_end:

_chin_pink_walk03_LEFT:
	.word $FFB0, $04, $100, $881
	.word $FFB0, $FFF4, $102, $881
	.word $FFC0, $04, $104, $881
	.word $FFC0, $FFF4, $106, $881
	.word $FFC0, $FFE4, $108, $881
	.word $FFD0, $04, $10A, $881
	.word $FFD0, $FFF4, $10C, $881
	.word $FFD0, $FFE4, $10E, $881
	.word $FFE0, $04, $110, $881
	.word $FFE0, $FFF4, $112, $881
	.word $FFF0, $04, $114, $881
	.word $FFF0, $FFF4, $116, $881
_chin_pink_walk03_LEFT_end:

_chin_pink_walk04_LEFT:
	.word $FFB0, $04, $100, $881
	.word $FFB0, $FFF4, $102, $881
	.word $FFC0, $04, $104, $881
	.word $FFC0, $FFF4, $106, $881
	.word $FFC0, $FFE4, $108, $881
	.word $FFD0, $04, $10A, $881
	.word $FFD0, $FFF4, $10C, $881
	.word $FFD0, $FFE4, $10E, $881
	.word $FFE0, $04, $110, $881
	.word $FFE0, $FFF4, $112, $881
	.word $FFF0, $04, $114, $881
	.word $FFF0, $FFF4, $116, $881
_chin_pink_walk04_LEFT_end:

