;#######################################################
;
; Generated by SPReD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################

_player_gfx_chr0:	.incbin "_player_gfx_chr0.bin"	; 2944 bytes
_player_gfx_chr1:	.incbin "_player_gfx_chr1.bin"	; 2304 bytes
_player_gfx_chr2:	.incbin "_player_gfx_chr2.bin"	; 2432 bytes
_player_gfx_chr3:	.incbin "_player_gfx_chr3.bin"	; 2944 bytes
_player_gfx_chr4:	.incbin "_player_gfx_chr4.bin"	; 2560 bytes
_player_gfx_chr5:	.incbin "_player_gfx_chr5.bin"	; 2304 bytes
_player_gfx_chr6:	.incbin "_player_gfx_chr6.bin"	; 2560 bytes
_player_gfx_chr7:	.incbin "_player_gfx_chr7.bin"	; 3200 bytes
_player_gfx_chr8:	.incbin "_player_gfx_chr8.bin"	; 2176 bytes
_player_gfx_chr9:	.incbin "_player_gfx_chr9.bin"	; 3200 bytes

_player_gfx_SG_arr:	
	.word 2944, _player_gfx_chr0, bank(_player_gfx_chr0)
	.word 2304, _player_gfx_chr1, bank(_player_gfx_chr1)
	.word 2432, _player_gfx_chr2, bank(_player_gfx_chr2)
	.word 2944, _player_gfx_chr3, bank(_player_gfx_chr3)
	.word 2560, _player_gfx_chr4, bank(_player_gfx_chr4)
	.word 2304, _player_gfx_chr5, bank(_player_gfx_chr5)
	.word 2560, _player_gfx_chr6, bank(_player_gfx_chr6)
	.word 3200, _player_gfx_chr7, bank(_player_gfx_chr7)
	.word 2176, _player_gfx_chr8, bank(_player_gfx_chr8)
	.word 3200, _player_gfx_chr9, bank(_player_gfx_chr9)


_player_gfx_palette:
_player_gfx_palette_slot0:
	.word $147, $C2, $81, $14B, $19D, $1B0, $170, $E9, $173, $F0, $1B5, $B0, $58, $133, $F2, $1B6
_player_gfx_palette_end:

_player_gfx_num_frames:
	.byte $18
_player_gfx_frames_data:
_mpwr_idle01_RIGHT_frame:
	.word _mpwr_idle01_RIGHT
	.byte bank(_mpwr_idle01_RIGHT)
_mpwr_walk01_RIGHT_frame:
	.word _mpwr_walk01_RIGHT
	.byte bank(_mpwr_walk01_RIGHT)
_mpwr_walk02_RIGHT_frame:
	.word _mpwr_walk02_RIGHT
	.byte bank(_mpwr_walk02_RIGHT)
_mpwr_walk03_RIGHT_frame:
	.word _mpwr_walk03_RIGHT
	.byte bank(_mpwr_walk03_RIGHT)
_mpwr_walk04_RIGHT_frame:
	.word _mpwr_walk04_RIGHT
	.byte bank(_mpwr_walk04_RIGHT)
_mpwr_walk05_RIGHT_frame:
	.word _mpwr_walk05_RIGHT
	.byte bank(_mpwr_walk05_RIGHT)
_mpwr_walk06_RIGHT_frame:
	.word _mpwr_walk06_RIGHT
	.byte bank(_mpwr_walk06_RIGHT)
_mpwr_kick01_RIGHT_frame:
	.word _mpwr_kick01_RIGHT
	.byte bank(_mpwr_kick01_RIGHT)
_mpwr_kick02_RIGHT_frame:
	.word _mpwr_kick02_RIGHT
	.byte bank(_mpwr_kick02_RIGHT)
_mpwr_kick03_RIGHT_frame:
	.word _mpwr_kick03_RIGHT
	.byte bank(_mpwr_kick03_RIGHT)
_mpwr_kick04_ref02_RIGHT_frame:
	.word _mpwr_kick04_ref02_RIGHT
	.byte bank(_mpwr_kick04_ref02_RIGHT)
_mpwr_kick05_ref01_RIGHT_frame:
	.word _mpwr_kick05_ref01_RIGHT
	.byte bank(_mpwr_kick05_ref01_RIGHT)
_mpwr_idle01_LEFT_frame:
	.word _mpwr_idle01_LEFT
	.byte bank(_mpwr_idle01_LEFT)
_mpwr_walk01_LEFT_frame:
	.word _mpwr_walk01_LEFT
	.byte bank(_mpwr_walk01_LEFT)
_mpwr_walk02_LEFT_frame:
	.word _mpwr_walk02_LEFT
	.byte bank(_mpwr_walk02_LEFT)
_mpwr_walk03_LEFT_frame:
	.word _mpwr_walk03_LEFT
	.byte bank(_mpwr_walk03_LEFT)
_mpwr_walk04_LEFT_frame:
	.word _mpwr_walk04_LEFT
	.byte bank(_mpwr_walk04_LEFT)
_mpwr_walk05_LEFT_frame:
	.word _mpwr_walk05_LEFT
	.byte bank(_mpwr_walk05_LEFT)
_mpwr_walk06_LEFT_frame:
	.word _mpwr_walk06_LEFT
	.byte bank(_mpwr_walk06_LEFT)
_mpwr_kick01_LEFT_frame:
	.word _mpwr_kick01_LEFT
	.byte bank(_mpwr_kick01_LEFT)
_mpwr_kick02_LEFT_frame:
	.word _mpwr_kick02_LEFT
	.byte bank(_mpwr_kick02_LEFT)
_mpwr_kick03_LEFT_frame:
	.word _mpwr_kick03_LEFT
	.byte bank(_mpwr_kick03_LEFT)
_mpwr_kick04_ref02_LEFT_frame:
	.word _mpwr_kick04_ref02_LEFT
	.byte bank(_mpwr_kick04_ref02_LEFT)
_mpwr_kick05_ref01_LEFT_frame:
	.word _mpwr_kick05_ref01_LEFT
	.byte bank(_mpwr_kick05_ref01_LEFT)


	; #1: Y pos, #2: X pos, #3: CHR index, #4: CHR desc

_mpwr_idle01_RIGHT:
	.word _mpwr_idle01_RIGHT_end - _mpwr_idle01_RIGHT - 3	; data size
	.byte 6		; GFX bank index (chr6)

	.word $FFCE, $FFFB, $100, $1980
	.word $FF9E, $FFFB, $108, $980
	.word $FFAE, $FFFF, $10C, $980
	.word $FFBE, $FFFC, $110, $980
	.word $FFEE, $FFFB, $114, $980
	.word $FFEE, $FFDB, $118, $980
	.word $FF9E, $FFEB, $11C, $880
	.word $FFAE, $FFEF, $11E, $880
	.word $FFBE, $FFEC, $120, $880
	.word $FFCE, $FFEB, $122, $880
	.word $FFDE, $FFEB, $124, $880
	.word $FFFE, $FFE4, $126, $880
_mpwr_idle01_RIGHT_end:

_mpwr_walk01_RIGHT:
	.word _mpwr_walk01_RIGHT_end - _mpwr_walk01_RIGHT - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $FF97, $FFF3, $100, $980
	.word $FFA7, $08, $104, $980
	.word $FFA7, $FFE8, $108, $980
	.word $FFB7, $07, $10C, $980
	.word $FFB7, $FFE7, $110, $980
	.word $FFC7, $FFED, $114, $980
	.word $FFD7, $FFF1, $118, $980
	.word $FFE7, $FFD9, $11C, $980
	.word $FFF7, $FFF5, $120, $980
	.word $FF97, $FFE3, $124, $880
	.word $FFA7, $FFD8, $126, $880
	.word $FFD7, $FFE1, $128, $880
	.word $FFE7, $FFFF, $12A, $880
	.word $FFF7, $FFDC, $12C, $880
_mpwr_walk01_RIGHT_end:

_mpwr_walk02_RIGHT:
	.word _mpwr_walk02_RIGHT_end - _mpwr_walk02_RIGHT - 3	; data size
	.byte 1		; GFX bank index (chr1)

	.word $FF96, $FFF2, $100, $1980
	.word $FFB6, $FFEF, $108, $980
	.word $FFC6, $FFE9, $10C, $980
	.word $FFD6, $FFEC, $110, $980
	.word $FFE6, $FFEA, $114, $980
	.word $FFF6, $FFEE, $118, $980
	.word $FFA6, $12, $11C, $880
	.word $FFD6, $FFDC, $11E, $880
	.word $FFE6, $FFDA, $120, $880
	.word $FFF6, $FFDE, $122, $880
_mpwr_walk02_RIGHT_end:

_mpwr_walk03_RIGHT:
	.word _mpwr_walk03_RIGHT_end - _mpwr_walk03_RIGHT - 3	; data size
	.byte 2		; GFX bank index (chr2)

	.word $FFC3, $FFFA, $100, $1980
	.word $FF93, $FFF2, $108, $980
	.word $FFA3, $00, $10C, $980
	.word $FFB3, $FFF2, $110, $980
	.word $FFE3, $FFF6, $114, $980
	.word $FFF3, $FFD7, $118, $980
	.word $FFA3, $FFF0, $11C, $880
	.word $FFB3, $FFE2, $11E, $880
	.word $FFC3, $FFEA, $120, $880
	.word $FFD3, $FFEA, $122, $880
	.word $FFE3, $FFE6, $124, $880
_mpwr_walk03_RIGHT_end:

_mpwr_walk04_RIGHT:
	.word _mpwr_walk04_RIGHT_end - _mpwr_walk04_RIGHT - 3	; data size
	.byte 3		; GFX bank index (chr3)

	.word $FF97, $FFF2, $100, $1980
	.word $FFD7, $FFD9, $108, $1980
	.word $FFE7, $FFFD, $110, $1980
	.word $FFB7, $FFFC, $118, $980
	.word $FFC7, $FFF6, $11C, $980
	.word $FFD7, $FFF9, $120, $980
	.word $FFA7, $12, $124, $880
	.word $FFA7, $FFE2, $126, $880
	.word $FFB7, $FFEC, $128, $880
	.word $FFC7, $FFE6, $12A, $880
	.word $FFF7, $FFD7, $12C, $880
_mpwr_walk04_RIGHT_end:

_mpwr_walk05_RIGHT:
	.word _mpwr_walk05_RIGHT_end - _mpwr_walk05_RIGHT - 3	; data size
	.byte 4		; GFX bank index (chr4)

	.word $FFBA, $FFF2, $100, $1980
	.word $FF9A, $FFF2, $108, $980
	.word $FFAA, $FFFE, $10C, $980
	.word $FFDA, $FFF3, $110, $980
	.word $FFEA, $FFF1, $114, $980
	.word $FFFA, $FFF2, $118, $980
	.word $FFAA, $FFEE, $11C, $880
	.word $FFBA, $FFE2, $11E, $880
	.word $FFCA, $FFE2, $120, $880
	.word $FFDA, $FFE3, $122, $880
	.word $FFEA, $FFE1, $124, $880
	.word $FFFA, $FFDA, $126, $880
_mpwr_walk05_RIGHT_end:

_mpwr_walk06_RIGHT:
	.word _mpwr_walk06_RIGHT_end - _mpwr_walk06_RIGHT - 3	; data size
	.byte 5		; GFX bank index (chr5)

	.word $FF98, $FFF2, $100, $1980
	.word $FFC8, $FFF2, $108, $1980
	.word $FFB8, $FFF0, $110, $980
	.word $FFE8, $FFEE, $114, $980
	.word $FFF8, $FFE0, $118, $980
	.word $FFA8, $12, $11C, $880
	.word $FFA8, $FFE2, $11E, $880
	.word $FFB8, $FFE0, $120, $880
	.word $FFC8, $FFE2, $122, $880
_mpwr_walk06_RIGHT_end:

_mpwr_kick01_RIGHT:
	.word _mpwr_kick01_RIGHT_end - _mpwr_kick01_RIGHT - 3	; data size
	.byte 7		; GFX bank index (chr7)

	.word $FFE8, $FFFB, $100, $1980
	.word $FF98, $05, $108, $980
	.word $FF98, $FFE5, $10C, $980
	.word $FFA8, $08, $110, $980
	.word $FFA8, $FFE8, $114, $980
	.word $FFB8, $FFF6, $118, $980
	.word $FFC8, $FFFC, $11C, $980
	.word $FFD8, $FFFF, $120, $980
	.word $FFD8, $FFDF, $124, $980
	.word $FFE8, $FFDB, $128, $980
	.word $FFB8, $17, $12C, $880
	.word $FFC8, $FFEC, $12E, $880
	.word $FFF8, $FFE1, $130, $880
_mpwr_kick01_RIGHT_end:

_mpwr_kick02_RIGHT:
	.word _mpwr_kick02_RIGHT_end - _mpwr_kick02_RIGHT - 3	; data size
	.byte 8		; GFX bank index (chr8)

	.word $FFD3, $00, $100, $1980
	.word $FF93, $FFED, $108, $980
	.word $FFA3, $FFFE, $10C, $980
	.word $FFB3, $FFF7, $110, $980
	.word $FFC3, $FFFD, $114, $980
	.word $FFF3, $FFFB, $118, $980
	.word $FFA3, $FFEE, $11C, $880
	.word $FFD3, $FFF0, $11E, $880
	.word $FFE3, $FFF0, $120, $880
_mpwr_kick02_RIGHT_end:

_mpwr_kick03_RIGHT:
	.word _mpwr_kick03_RIGHT_end - _mpwr_kick03_RIGHT - 3	; data size
	.byte 9		; GFX bank index (chr9)

	.word $FFAA, $14, $100, $1980
	.word $FFAA, $FFF4, $108, $1980
	.word $FFCA, $03, $110, $1980
	.word $FF9A, $08, $118, $980
	.word $FFCA, $FFE3, $11C, $980
	.word $FFEA, $FFFE, $120, $980
	.word $FFFA, $FFFB, $124, $980
	.word $FF9A, $33, $128, $880
	.word $FF9A, $FFF8, $12A, $880
	.word $FFAA, $34, $12C, $880
	.word $FFAA, $FFE4, $12E, $880
	.word $FFBA, $FFE4, $130, $880
_mpwr_kick03_RIGHT_end:

_mpwr_kick04_ref02_RIGHT:
	.word _mpwr_kick04_ref02_RIGHT_end - _mpwr_kick04_ref02_RIGHT - 3	; data size
	.byte 8		; GFX bank index (chr8)

	.word $FFD3, $00, $100, $1980
	.word $FF93, $FFED, $108, $980
	.word $FFA3, $FFFE, $10C, $980
	.word $FFB3, $FFF7, $110, $980
	.word $FFC3, $FFFD, $114, $980
	.word $FFF3, $FFFB, $118, $980
	.word $FFA3, $FFEE, $11C, $880
	.word $FFD3, $FFF0, $11E, $880
	.word $FFE3, $FFF0, $120, $880
_mpwr_kick04_ref02_RIGHT_end:

_mpwr_kick05_ref01_RIGHT:
	.word _mpwr_kick05_ref01_RIGHT_end - _mpwr_kick05_ref01_RIGHT - 3	; data size
	.byte 7		; GFX bank index (chr7)

	.word $FFE8, $FFFB, $100, $1980
	.word $FF98, $05, $108, $980
	.word $FF98, $FFE5, $10C, $980
	.word $FFA8, $08, $110, $980
	.word $FFA8, $FFE8, $114, $980
	.word $FFB8, $FFF6, $118, $980
	.word $FFC8, $FFFC, $11C, $980
	.word $FFD8, $FFFF, $120, $980
	.word $FFD8, $FFDF, $124, $980
	.word $FFE8, $FFDB, $128, $980
	.word $FFB8, $17, $12C, $880
	.word $FFC8, $FFEC, $12E, $880
	.word $FFF8, $FFE1, $130, $880
_mpwr_kick05_ref01_RIGHT_end:

_mpwr_idle01_LEFT:
	.word _mpwr_idle01_LEFT_end - _mpwr_idle01_LEFT - 3	; data size
	.byte 6		; GFX bank index (chr6)

	.word $FFCE, $FFE5, $100, $1180
	.word $FF9E, $FFE5, $108, $180
	.word $FFAE, $FFE1, $10C, $180
	.word $FFBE, $FFE4, $110, $180
	.word $FFEE, $FFE5, $114, $180
	.word $FFEE, $05, $118, $180
	.word $FF9E, $05, $11C, $80
	.word $FFAE, $01, $11E, $80
	.word $FFBE, $04, $120, $80
	.word $FFCE, $05, $122, $80
	.word $FFDE, $05, $124, $80
	.word $FFFE, $0C, $126, $80
_mpwr_idle01_LEFT_end:

_mpwr_walk01_LEFT:
	.word _mpwr_walk01_LEFT_end - _mpwr_walk01_LEFT - 3	; data size
	.byte 0		; GFX bank index (chr0)

	.word $FF97, $FFED, $100, $180
	.word $FFA7, $FFD8, $104, $180
	.word $FFA7, $FFF8, $108, $180
	.word $FFB7, $FFD9, $10C, $180
	.word $FFB7, $FFF9, $110, $180
	.word $FFC7, $FFF3, $114, $180
	.word $FFD7, $FFEF, $118, $180
	.word $FFE7, $07, $11C, $180
	.word $FFF7, $FFEB, $120, $180
	.word $FF97, $0D, $124, $80
	.word $FFA7, $18, $126, $80
	.word $FFD7, $0F, $128, $80
	.word $FFE7, $FFF1, $12A, $80
	.word $FFF7, $14, $12C, $80
_mpwr_walk01_LEFT_end:

_mpwr_walk02_LEFT:
	.word _mpwr_walk02_LEFT_end - _mpwr_walk02_LEFT - 3	; data size
	.byte 1		; GFX bank index (chr1)

	.word $FF96, $FFEE, $100, $1180
	.word $FFB6, $FFF1, $108, $180
	.word $FFC6, $FFF7, $10C, $180
	.word $FFD6, $FFF4, $110, $180
	.word $FFE6, $FFF6, $114, $180
	.word $FFF6, $FFF2, $118, $180
	.word $FFA6, $FFDE, $11C, $80
	.word $FFD6, $14, $11E, $80
	.word $FFE6, $16, $120, $80
	.word $FFF6, $12, $122, $80
_mpwr_walk02_LEFT_end:

_mpwr_walk03_LEFT:
	.word _mpwr_walk03_LEFT_end - _mpwr_walk03_LEFT - 3	; data size
	.byte 2		; GFX bank index (chr2)

	.word $FFC3, $FFE6, $100, $1180
	.word $FF93, $FFEE, $108, $180
	.word $FFA3, $FFE0, $10C, $180
	.word $FFB3, $FFEE, $110, $180
	.word $FFE3, $FFEA, $114, $180
	.word $FFF3, $09, $118, $180
	.word $FFA3, $00, $11C, $80
	.word $FFB3, $0E, $11E, $80
	.word $FFC3, $06, $120, $80
	.word $FFD3, $06, $122, $80
	.word $FFE3, $0A, $124, $80
_mpwr_walk03_LEFT_end:

_mpwr_walk04_LEFT:
	.word _mpwr_walk04_LEFT_end - _mpwr_walk04_LEFT - 3	; data size
	.byte 3		; GFX bank index (chr3)

	.word $FF97, $FFEE, $100, $1180
	.word $FFD7, $07, $108, $1180
	.word $FFE7, $FFE3, $110, $1180
	.word $FFB7, $FFE4, $118, $180
	.word $FFC7, $FFEA, $11C, $180
	.word $FFD7, $FFE7, $120, $180
	.word $FFA7, $FFDE, $124, $80
	.word $FFA7, $0E, $126, $80
	.word $FFB7, $04, $128, $80
	.word $FFC7, $0A, $12A, $80
	.word $FFF7, $19, $12C, $80
_mpwr_walk04_LEFT_end:

_mpwr_walk05_LEFT:
	.word _mpwr_walk05_LEFT_end - _mpwr_walk05_LEFT - 3	; data size
	.byte 4		; GFX bank index (chr4)

	.word $FFBA, $FFEE, $100, $1180
	.word $FF9A, $FFEE, $108, $180
	.word $FFAA, $FFE2, $10C, $180
	.word $FFDA, $FFED, $110, $180
	.word $FFEA, $FFEF, $114, $180
	.word $FFFA, $FFEE, $118, $180
	.word $FFAA, $02, $11C, $80
	.word $FFBA, $0E, $11E, $80
	.word $FFCA, $0E, $120, $80
	.word $FFDA, $0D, $122, $80
	.word $FFEA, $0F, $124, $80
	.word $FFFA, $16, $126, $80
_mpwr_walk05_LEFT_end:

_mpwr_walk06_LEFT:
	.word _mpwr_walk06_LEFT_end - _mpwr_walk06_LEFT - 3	; data size
	.byte 5		; GFX bank index (chr5)

	.word $FF98, $FFEE, $100, $1180
	.word $FFC8, $FFEE, $108, $1180
	.word $FFB8, $FFF0, $110, $180
	.word $FFE8, $FFF2, $114, $180
	.word $FFF8, $00, $118, $180
	.word $FFA8, $FFDE, $11C, $80
	.word $FFA8, $0E, $11E, $80
	.word $FFB8, $10, $120, $80
	.word $FFC8, $0E, $122, $80
_mpwr_walk06_LEFT_end:

_mpwr_kick01_LEFT:
	.word _mpwr_kick01_LEFT_end - _mpwr_kick01_LEFT - 3	; data size
	.byte 7		; GFX bank index (chr7)

	.word $FFE8, $FFE5, $100, $1180
	.word $FF98, $FFDB, $108, $180
	.word $FF98, $FFFB, $10C, $180
	.word $FFA8, $FFD8, $110, $180
	.word $FFA8, $FFF8, $114, $180
	.word $FFB8, $FFEA, $118, $180
	.word $FFC8, $FFE4, $11C, $180
	.word $FFD8, $FFE1, $120, $180
	.word $FFD8, $01, $124, $180
	.word $FFE8, $05, $128, $180
	.word $FFB8, $FFD9, $12C, $80
	.word $FFC8, $04, $12E, $80
	.word $FFF8, $0F, $130, $80
_mpwr_kick01_LEFT_end:

_mpwr_kick02_LEFT:
	.word _mpwr_kick02_LEFT_end - _mpwr_kick02_LEFT - 3	; data size
	.byte 8		; GFX bank index (chr8)

	.word $FFD3, $FFE0, $100, $1180
	.word $FF93, $FFF3, $108, $180
	.word $FFA3, $FFE2, $10C, $180
	.word $FFB3, $FFE9, $110, $180
	.word $FFC3, $FFE3, $114, $180
	.word $FFF3, $FFE5, $118, $180
	.word $FFA3, $02, $11C, $80
	.word $FFD3, $00, $11E, $80
	.word $FFE3, $00, $120, $80
_mpwr_kick02_LEFT_end:

_mpwr_kick03_LEFT:
	.word _mpwr_kick03_LEFT_end - _mpwr_kick03_LEFT - 3	; data size
	.byte 9		; GFX bank index (chr9)

	.word $FFAA, $FFCC, $100, $1180
	.word $FFAA, $FFEC, $108, $1180
	.word $FFCA, $FFDD, $110, $1180
	.word $FF9A, $FFD8, $118, $180
	.word $FFCA, $FFFD, $11C, $180
	.word $FFEA, $FFE2, $120, $180
	.word $FFFA, $FFE5, $124, $180
	.word $FF9A, $FFBD, $128, $80
	.word $FF9A, $FFF8, $12A, $80
	.word $FFAA, $FFBC, $12C, $80
	.word $FFAA, $0C, $12E, $80
	.word $FFBA, $0C, $130, $80
_mpwr_kick03_LEFT_end:

_mpwr_kick04_ref02_LEFT:
	.word _mpwr_kick04_ref02_LEFT_end - _mpwr_kick04_ref02_LEFT - 3	; data size
	.byte 8		; GFX bank index (chr8)

	.word $FFD3, $FFE0, $100, $1180
	.word $FF93, $FFF3, $108, $180
	.word $FFA3, $FFE2, $10C, $180
	.word $FFB3, $FFE9, $110, $180
	.word $FFC3, $FFE3, $114, $180
	.word $FFF3, $FFE5, $118, $180
	.word $FFA3, $02, $11C, $80
	.word $FFD3, $00, $11E, $80
	.word $FFE3, $00, $120, $80
_mpwr_kick04_ref02_LEFT_end:

_mpwr_kick05_ref01_LEFT:
	.word _mpwr_kick05_ref01_LEFT_end - _mpwr_kick05_ref01_LEFT - 3	; data size
	.byte 7		; GFX bank index (chr7)

	.word $FFE8, $FFE5, $100, $1180
	.word $FF98, $FFDB, $108, $180
	.word $FF98, $FFFB, $10C, $180
	.word $FFA8, $FFD8, $110, $180
	.word $FFA8, $FFF8, $114, $180
	.word $FFB8, $FFEA, $118, $180
	.word $FFC8, $FFE4, $11C, $180
	.word $FFD8, $FFE1, $120, $180
	.word $FFD8, $01, $124, $180
	.word $FFE8, $05, $128, $180
	.word $FFB8, $FFD9, $12C, $80
	.word $FFC8, $04, $12E, $80
	.word $FFF8, $0F, $130, $80
_mpwr_kick05_ref01_LEFT_end:

