;#######################################################
;
; Generated by MAPeD-PCE Copyright 2017-2022 0x8BitDev
;
;#######################################################


; *** GLOBAL DATA ***

_chr0:	.incbin "_tilemap__chr0.bin"		; (11392)
_chr1:	.incbin "_tilemap__chr1.bin"		; (8064)
_chr2:	.incbin "_tilemap__chr2.bin"		; (9952)


_mpd_CHRs_size:
	.word 11392	; (_chr0)
	.word 8064	; (_chr1)
	.word 9952	; (_chr2)

_mpd_Props:	.incbin "_tilemap_Props.bin"	; (2400) block properties array of all exported data banks ( 4 bytes per block )

_mpd_PropsOffs:
	.word 0	; (chr0)
	.word 900	; (chr1)
	.word 1524	; (chr2)
	.word 2400	; data end

_mpd_BlocksOffs:
	.word 0	; (chr0)
	.word 1800	; (chr1)
	.word 3048	; (chr2)

_mpd_Attrs:	.incbin "_tilemap_Attrs.bin"	; (4800) 2x2 tiles attributes array of all exported data banks ( 2 bytes per attribute )
_mpd_TilesScr:	.incbin "_tilemap_TilesScr.bin"	; (9632) 2x2 tiles array for each screen ( 224 bytes per screen \ 1 byte per tile )
_mpd_Plts:	.incbin "_tilemap_Plts.bin"	; (1536) palettes array of all exported data banks ( data offset = chr_id * 512 )
