//#######################################################
//
// Generated by MAPeD-PCE Copyright 2017-2022 0x8BitDev
//
//#######################################################


#incasm( "tilemap.asm" )

// export options:
//	- tiles 2x2/(columns)
//	- properties per CHR
//	- mode: bidirectional scrolling
//	- layout: adjacent screen indices (no marks)
//	- no entities


/* exported data flags: */

#define FLAG_TILES2X2                 1
#define FLAG_TILES4X4                 0
#define FLAG_RLE                      0
#define FLAG_DIR_COLUMNS              1
#define FLAG_DIR_ROWS                 0
#define FLAG_MODE_MULTIDIR_SCROLL     0
#define FLAG_MODE_BIDIR_SCROLL        1
#define FLAG_MODE_BIDIR_STAT_SCR      0
#define FLAG_MODE_STAT_SCR            0
#define FLAG_ENTITIES                 0
#define FLAG_ENTITY_SCR_COORDS        0
#define FLAG_ENTITY_MAP_COORS         0
#define FLAG_LAYOUT_ADJ_SCR           0
#define FLAG_LAYOUT_ADJ_SCR_INDS      1
#define FLAG_LAYOUT_MATRIX            0
#define FLAG_MARKS                    0
#define FLAG_PROP_ID_PER_BLOCK        0
#define FLAG_PROP_ID_PER_CHR          1

#define MAPS_CNT	3

#define BAT_INDEX	1
#define CHRS_OFFSET	64	// first CHR index from the beginning of VRAM

#define SCR_BLOCKS2x2_WIDTH	16	// number of screen blocks (2x2) in width
#define SCR_BLOCKS2x2_HEIGHT	14	// number of screen blocks (2x2) in height

#define ScrTilesWidth	16	// number of screen tiles (2x2) in width
#define ScrTilesHeight	14	// number of screen tiles (2x2) in height

#define ScrPixelsWidth	256	// screen width in pixels
#define ScrPixelsHeight	224	// screen height in pixels

/* screen data */

typedef struct
{
#if	FLAG_MODE_BIDIR_SCROLL + FLAG_MODE_STAT_SCR
	u8	chr_id;
#endif
#if	FLAG_MARKS
	//bits: 7-4 - bit mask of user defined adjacent screens ( Down(7)-Right(6)-Up(5)-Left(4) ); 3-0 - screen property
	u8	marks;
#endif
#if	FLAG_MODE_STAT_SCR
	u16	VDC_data_offset;
#endif
#if	FLAG_MODE_BIDIR_SCROLL + FLAG_MODE_STAT_SCR
	u8	scr_ind;
#endif
#if	FLAG_LAYOUT_ADJ_SCR
	// adjacent screen pointers
	void*	adj_scr[4];
#endif
#if	FLAG_LAYOUT_ADJ_SCR_INDS
	u8	adj_scr[4];
#endif
#if	FLAG_ENTITIES
	u8	ents_cnt;
	mpd_ENTITY_INSTANCE*	ents[];
#endif
} mpd_SCREEN;

extern u16*	chr0;
extern u16*	chr1;
extern u16*	chr2;

#asm
_mpd_CHRs:
	.word bank(_chr0)
	.word _chr0
	.word bank(_chr1)
	.word _chr1
	.word bank(_chr2)
	.word _chr2
#endasm

extern u16	mpd_CHRs[];
extern u16*	mpd_CHRs_size;
extern u8*	mpd_Props;
extern u16*	mpd_PropsOffs;
extern u16*	mpd_BlocksOffs;
extern u16*	mpd_Attrs;
extern u8*	mpd_TilesScr;
extern u16*	mpd_Plts;

// *** _Lev0 ***

extern mpd_SCREEN*	Lev0_ScrArr[];
extern mpd_SCREEN*	Lev0_StartScr;

#asm
_Lev0_StartScr:	.word _Lev0Scr44

_Lev0Scr2:
	.byte 0	; chr_id

	.byte 0	; screen index

; adjacent screen indices ( the valid values are $00 - $FE, $FF - means no screen )
; use the _Lev0_ScrArr array to get a screen description by adjacent screen index
	.byte $FF	; left adjacent screen index
	.byte $FF	; up adjacent screen index
	.byte $01	; right adjacent screen index
	.byte $05	; down adjacent screen index

_Lev0Scr3:
	.byte 0

	.byte 1

	.byte $00
	.byte $FF
	.byte $02
	.byte $FF

_Lev0Scr4:
	.byte 0

	.byte 2

	.byte $01
	.byte $FF
	.byte $FF
	.byte $FF

_Lev0Scr9:
	.byte 0

	.byte 3

	.byte $FF
	.byte $FF
	.byte $04
	.byte $06

_Lev0Scr10:
	.byte 0

	.byte 4

	.byte $03
	.byte $FF
	.byte $05
	.byte $FF

_Lev0Scr11:
	.byte 0

	.byte 5

	.byte $04
	.byte $00
	.byte $FF
	.byte $FF

_Lev0Scr18:
	.byte 0

	.byte 6

	.byte $FF
	.byte $03
	.byte $FF
	.byte $07

_Lev0Scr27:
	.byte 0

	.byte 7

	.byte $FF
	.byte $06
	.byte $08
	.byte $FF

_Lev0Scr28:
	.byte 0

	.byte 8

	.byte $07
	.byte $FF
	.byte $09
	.byte $FF

_Lev0Scr29:
	.byte 0

	.byte 9

	.byte $08
	.byte $FF
	.byte $0A
	.byte $FF

_Lev0Scr30:
	.byte 0

	.byte 10

	.byte $09
	.byte $FF
	.byte $FF
	.byte $0B

_Lev0Scr39:
	.byte 0

	.byte 11

	.byte $FF
	.byte $0A
	.byte $0C
	.byte $FF

_Lev0Scr40:
	.byte 0

	.byte 12

	.byte $0B
	.byte $FF
	.byte $0D
	.byte $FF

_Lev0Scr41:
	.byte 0

	.byte 13

	.byte $0C
	.byte $FF
	.byte $0E
	.byte $FF

_Lev0Scr42:
	.byte 0

	.byte 14

	.byte $0D
	.byte $FF
	.byte $0F
	.byte $FF

_Lev0Scr43:
	.byte 0

	.byte 15

	.byte $0E
	.byte $FF
	.byte $10
	.byte $FF

_Lev0Scr44:
	.byte 0

	.byte 16

	.byte $0F
	.byte $FF
	.byte $FF
	.byte $FF

; screens array
_Lev0_ScrArr:
	.word _Lev0Scr2
	.word _Lev0Scr3
	.word _Lev0Scr4
	.word _Lev0Scr9
	.word _Lev0Scr10
	.word _Lev0Scr11
	.word _Lev0Scr18
	.word _Lev0Scr27
	.word _Lev0Scr28
	.word _Lev0Scr29
	.word _Lev0Scr30
	.word _Lev0Scr39
	.word _Lev0Scr40
	.word _Lev0Scr41
	.word _Lev0Scr42
	.word _Lev0Scr43
	.word _Lev0Scr44

#endasm

// *** _Lev1 ***

extern mpd_SCREEN*	Lev1_ScrArr[];
extern mpd_SCREEN*	Lev1_StartScr;

#asm
_Lev1_StartScr:	.word _Lev1Scr30

_Lev1Scr7:
	.byte 1	; chr_id

	.byte 17	; screen index

; adjacent screen indices ( the valid values are $00 - $FE, $FF - means no screen )
; use the _Lev1_ScrArr array to get a screen description by adjacent screen index
	.byte $FF	; left adjacent screen index
	.byte $FF	; up adjacent screen index
	.byte $01	; right adjacent screen index
	.byte $07	; down adjacent screen index

_Lev1Scr8:
	.byte 1

	.byte 18

	.byte $00
	.byte $FF
	.byte $02
	.byte $FF

_Lev1Scr9:
	.byte 1

	.byte 19

	.byte $01
	.byte $FF
	.byte $FF
	.byte $FF

_Lev1Scr13:
	.byte 1

	.byte 20

	.byte $FF
	.byte $FF
	.byte $04
	.byte $0B

_Lev1Scr14:
	.byte 1

	.byte 21

	.byte $03
	.byte $FF
	.byte $05
	.byte $FF

_Lev1Scr15:
	.byte 1

	.byte 22

	.byte $04
	.byte $FF
	.byte $06
	.byte $FF

_Lev1Scr16:
	.byte 1

	.byte 23

	.byte $05
	.byte $FF
	.byte $07
	.byte $FF

_Lev1Scr17:
	.byte 1

	.byte 24

	.byte $06
	.byte $00
	.byte $FF
	.byte $FF

_Lev1Scr20:
	.byte 1

	.byte 25

	.byte $FF
	.byte $FF
	.byte $09
	.byte $0C

_Lev1Scr21:
	.byte 1

	.byte 26

	.byte $08
	.byte $FF
	.byte $0A
	.byte $FF

_Lev1Scr22:
	.byte 1

	.byte 27

	.byte $09
	.byte $FF
	.byte $0B
	.byte $FF

_Lev1Scr23:
	.byte 1

	.byte 28

	.byte $0A
	.byte $03
	.byte $FF
	.byte $FF

_Lev1Scr30:
	.byte 1

	.byte 29

	.byte $FF
	.byte $08
	.byte $FF
	.byte $FF

; screens array
_Lev1_ScrArr:
	.word _Lev1Scr7
	.word _Lev1Scr8
	.word _Lev1Scr9
	.word _Lev1Scr13
	.word _Lev1Scr14
	.word _Lev1Scr15
	.word _Lev1Scr16
	.word _Lev1Scr17
	.word _Lev1Scr20
	.word _Lev1Scr21
	.word _Lev1Scr22
	.word _Lev1Scr23
	.word _Lev1Scr30

#endasm

// *** _Lev2 ***

extern mpd_SCREEN*	Lev2_ScrArr[];
extern mpd_SCREEN*	Lev2_StartScr;

#asm
_Lev2_StartScr:	.word _Lev2Scr0

_Lev2Scr0:
	.byte 2	; chr_id

	.byte 30	; screen index

; adjacent screen indices ( the valid values are $00 - $FE, $FF - means no screen )
; use the _Lev2_ScrArr array to get a screen description by adjacent screen index
	.byte $FF	; left adjacent screen index
	.byte $FF	; up adjacent screen index
	.byte $01	; right adjacent screen index
	.byte $FF	; down adjacent screen index

_Lev2Scr1:
	.byte 2

	.byte 31

	.byte $00
	.byte $FF
	.byte $02
	.byte $FF

_Lev2Scr2:
	.byte 2

	.byte 32

	.byte $01
	.byte $FF
	.byte $03
	.byte $FF

_Lev2Scr3:
	.byte 2

	.byte 33

	.byte $02
	.byte $FF
	.byte $04
	.byte $FF

_Lev2Scr4:
	.byte 2

	.byte 34

	.byte $03
	.byte $FF
	.byte $05
	.byte $FF

_Lev2Scr5:
	.byte 2

	.byte 35

	.byte $04
	.byte $FF
	.byte $06
	.byte $FF

_Lev2Scr6:
	.byte 2

	.byte 36

	.byte $05
	.byte $FF
	.byte $07
	.byte $FF

_Lev2Scr7:
	.byte 2

	.byte 37

	.byte $06
	.byte $FF
	.byte $08
	.byte $FF

_Lev2Scr8:
	.byte 2

	.byte 38

	.byte $07
	.byte $FF
	.byte $09
	.byte $FF

_Lev2Scr9:
	.byte 2

	.byte 39

	.byte $08
	.byte $FF
	.byte $0A
	.byte $FF

_Lev2Scr10:
	.byte 2

	.byte 40

	.byte $09
	.byte $FF
	.byte $0B
	.byte $FF

_Lev2Scr11:
	.byte 2

	.byte 41

	.byte $0A
	.byte $FF
	.byte $0C
	.byte $FF

_Lev2Scr12:
	.byte 2

	.byte 42

	.byte $0B
	.byte $FF
	.byte $FF
	.byte $FF

; screens array
_Lev2_ScrArr:
	.word _Lev2Scr0
	.word _Lev2Scr1
	.word _Lev2Scr2
	.word _Lev2Scr3
	.word _Lev2Scr4
	.word _Lev2Scr5
	.word _Lev2Scr6
	.word _Lev2Scr7
	.word _Lev2Scr8
	.word _Lev2Scr9
	.word _Lev2Scr10
	.word _Lev2Scr11
	.word _Lev2Scr12

#endasm

extern mpd_SCREEN** mpd_MapsArr[];

#asm
_mpd_MapsArr:
	.word _Lev0_StartScr
	.word _Lev1_StartScr
	.word _Lev2_StartScr

#endasm

extern mpd_SCREEN** mpd_MapsScrArr[];

#asm
_mpd_MapsScrArr:
	.word _Lev0_ScrArr
	.word _Lev1_ScrArr
	.word _Lev2_ScrArr

#endasm
